
package com.mycompany.veterinaria.grupo4.view;

import com.mycompany.veterinaria.grupo4.view.auth.Background;
import javax.swing.JPanel;

/**
 *
 * @author juan
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public FrmPrincipal() {
        initComponents();
        
        this.setContentPane(bgPrincipal);
        setSize(1000,600);
        setLocationRelativeTo(null);
        setResizable(false);
    
        // Actualizamos la ventana
        this.revalidate();
        this.repaint();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrincipal = new javax.swing.JPanel();
        bgLogin = new com.mycompany.veterinaria.grupo4.view.auth.Background();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPrincipal.setLayout(new java.awt.BorderLayout());

        bgLogin.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/bg_veterinaria.png"))); // NOI18N
        bgPrincipal.add(bgLogin, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bgPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Background getBgLogin() {
        return bgLogin;
    }

    public JPanel getBgPrincipal() {
        return bgPrincipal;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.veterinaria.grupo4.view.auth.Background bgLogin;
    private javax.swing.JPanel bgPrincipal;
    // End of variables declaration//GEN-END:variables
}
