package com.mycompany.veterinaria.grupo4.view.mascota;

import com.formdev.flatlaf.FlatClientProperties;
import com.mycompany.veterinaria.grupo4.model.entity.Cliente;
import com.mycompany.veterinaria.grupo4.view.swing.Button;
import com.mycompany.veterinaria.grupo4.view.swing.MyTextField;
import com.mycompany.veterinaria.grupo4.view.swing.table.Table;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
/**
 *
 * @author juan
 */
public class PnlMascota extends javax.swing.JPanel {
    
    private javax.swing.JComboBox<Cliente> cmbClientes;
    
    /**
     * Creates new form pnlUsuario
     */
    public PnlMascota() {
        initComponents();
        setOpaque(true);
        putClientProperty(FlatClientProperties.STYLE, "background:$Panel.background");
        setBorder(new EmptyBorder(5, 5, 5, 5));
        
        pnlBg.setOpaque(true);
        pnlBg.putClientProperty(FlatClientProperties.STYLE, "background:$Panel.background");
        pnlBg.setBorder(new EmptyBorder(5, 5, 5, 5));
    }
    
    public JComboBox<Cliente> getCmbClientes() {
        return cmbClientes;
    }
    
    public Button getBtnBuscar() {
        return btnBuscar;
    }

    public Button getBtnNuevo() {
        return btnNuevo;
    }

    public Table getTblMascota() {
        return tblMascota;
    }

    public MyTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    public JScrollPane getScrollPane() {
        return scrollPane;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFiltrarCliente = new javax.swing.JLabel();  // NUEVO: etiqueta para el combo
        txtBusqueda = new com.mycompany.veterinaria.grupo4.view.swing.MyTextField();
        cmbClientes = new javax.swing.JComboBox<>();   // NUEVO: inicialización del combo
        btnNuevo = new com.mycompany.veterinaria.grupo4.view.swing.Button();
        scrollPane = new javax.swing.JScrollPane();
        tblMascota = new com.mycompany.veterinaria.grupo4.view.swing.table.Table();
        btnBuscar = new com.mycompany.veterinaria.grupo4.view.swing.Button();

        setPreferredSize(new java.awt.Dimension(806, 460));
        setLayout(new java.awt.BorderLayout());

        pnlBg.setPreferredSize(new java.awt.Dimension(806, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mascotas");

        // NUEVO: Configurar la etiqueta del filtro
        lblFiltrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblFiltrarCliente.setText("Filtrar por cliente:");

        txtBusqueda.setText("Buscar por nombre de mascota");
        txtBusqueda.setToolTipText("Buscar por nombre de mascota");

        // NUEVO: Configurar el ComboBox de clientes
        cmbClientes.setToolTipText("Seleccione un cliente para ver sus mascotas");
        cmbClientes.setPreferredSize(new java.awt.Dimension(180, 38));

        btnNuevo.setBackground(new java.awt.Color(255, 178, 39));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-one.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnNuevoComponentShown(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        tblMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPane.setViewportView(tblMascota);

        btnBuscar.setBackground(new java.awt.Color(255, 178, 39));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar mascota por nombre");

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addGroup(pnlBgLayout.createSequentialGroup()
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)  // Espacio entre botón Buscar y la etiqueta
                        .addComponent(lblFiltrarCliente)  // Etiqueta del filtro
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltrarCliente)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlBg, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void btnNuevoComponentShown(java.awt.event.ComponentEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    // Variables declaration - do not modify                     
    private com.mycompany.veterinaria.grupo4.view.swing.Button btnBuscar;
    private com.mycompany.veterinaria.grupo4.view.swing.Button btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFiltrarCliente;  // NUEVA variable
    private javax.swing.JPanel pnlBg;
    private javax.swing.JScrollPane scrollPane;
    private com.mycompany.veterinaria.grupo4.view.swing.table.Table tblMascota;
    private com.mycompany.veterinaria.grupo4.view.swing.MyTextField txtBusqueda;
    // Nota: cmbClientes ya está declarado al principio de la clase
    // End of variables declaration                   
}