-- ============================================================
--  MÓDULO 1 | Esquema de Tablas — db_veterinaria (MySQL)
-- ============================================================

DROP DATABASE IF EXISTS db_veterinaria;
CREATE DATABASE db_veterinaria;
USE db_veterinaria;
-- ─── Usuarios del sistema ────────────────────────────────────
CREATE TABLE USUARIO (
    ID_USUARIO          INT AUTO_INCREMENT PRIMARY KEY,
    CONTRASENA          VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO  VARCHAR(100) NOT NULL UNIQUE,
    ROL                 VARCHAR(20)  NOT NULL DEFAULT 'ADMINISTRADOR',
    FECHA_CREACION      DATETIME     DEFAULT NOW(),
    ESTADO              BOOLEAN      DEFAULT TRUE
);

-- ─── Recepcionistas ──────────────────────────────────────────
CREATE TABLE RECEPCIONISTA (
    ID_RECEPCIONISTA    INT AUTO_INCREMENT PRIMARY KEY,
    CEDULA              VARCHAR(10)  UNIQUE NOT NULL,
    NOMBRE              VARCHAR(50)  NOT NULL,
    APELLIDO            VARCHAR(50)  NOT NULL,
    TELEFONO            VARCHAR(15)  NOT NULL,
    DIRECCION           VARCHAR(100),
    CORREO_ELECTRONICO  VARCHAR(100) UNIQUE NOT NULL,
    FECHA_REGISTRO      DATETIME     DEFAULT NOW(),
    ESTADO              BOOLEAN      DEFAULT TRUE,
    CONSTRAINT FK_RECEPCIONISTA_USUARIO
        FOREIGN KEY (CORREO_ELECTRONICO)
        REFERENCES USUARIO(CORREO_ELECTRONICO)
        ON UPDATE CASCADE
);

-- ─── Clientes (dueños de mascotas) ───────────────────────────
CREATE TABLE CLIENTE (
    ID_CLIENTE          INT AUTO_INCREMENT PRIMARY KEY,
    CEDULA              VARCHAR(10)  UNIQUE NOT NULL,
    NOMBRE              VARCHAR(50)  NOT NULL,
    APELLIDO            VARCHAR(50)  NOT NULL,
    TELEFONO            VARCHAR(15)  NOT NULL,
    DIRECCION           VARCHAR(100),
    CORREO_ELECTRONICO  VARCHAR(100) UNIQUE,
    FECHA_REGISTRO      DATETIME     DEFAULT NOW()
);

-- ─── Especialidades veterinarias ─────────────────────────────
CREATE TABLE ESPECIALIDAD_VETERINARIA (
    ID_ESPECIALIDAD     INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ESPECIALIDAD VARCHAR(50) UNIQUE NOT NULL
);

-- ─── Veterinarios ────────────────────────────────────────────
CREATE TABLE VETERINARIO (
    ID_VETERINARIO      INT AUTO_INCREMENT PRIMARY KEY,
    CEDULA              VARCHAR(10) UNIQUE NOT NULL,
    NOMBRE              VARCHAR(50) NOT NULL,
    APELLIDO            VARCHAR(50) NOT NULL,
    TELEFONO            VARCHAR(15) NOT NULL,
    PAGO_MENSUAL        DECIMAL(10,2) DEFAULT 460.00,
    DIRECCION           VARCHAR(100),
    CORREO_ELECTRONICO  VARCHAR(100) NOT NULL UNIQUE,
    ID_ESPECIALIDAD     INT,
    FECHA_REGISTRO      DATETIME DEFAULT NOW(),
    CONSTRAINT FK_VETERINARIO_ESPECIALIDAD
        FOREIGN KEY (ID_ESPECIALIDAD)
        REFERENCES ESPECIALIDAD_VETERINARIA(ID_ESPECIALIDAD),
    CONSTRAINT FK_VETERINARIO_USUARIO
        FOREIGN KEY (CORREO_ELECTRONICO)
        REFERENCES USUARIO(CORREO_ELECTRONICO)
        ON UPDATE CASCADE
);
-- ─── Mascotas ────────────────────────────────────────────────
CREATE TABLE MASCOTA (
    ID_MASCOTA      INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE      INT           NOT NULL,
    NOMBRE          VARCHAR(50)   NOT NULL,
    ESPECIE         VARCHAR(30)   NOT NULL,
    RAZA            VARCHAR(50),
    SEXO            CHAR(1)       CHECK (SEXO IN ('M', 'H')),
    FECHA_NACIMIENTO DATE,
    PESO            DECIMAL(5,2),
    COLOR           VARCHAR(30),
    FOTO            LONGBLOB      NULL,
    FECHA_REGISTRO  DATETIME      DEFAULT NOW(),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- ─── Fichas médicas ──────────────────────────────────────────
CREATE TABLE FICHA_MEDICA (
    ID_FICHA              INT AUTO_INCREMENT PRIMARY KEY,
    ID_MASCOTA            INT NOT NULL,
    ALERGIAS              VARCHAR(255),
    ENFERMEDADES_CRONICAS VARCHAR(255),
    OBSERVACIONES         TEXT,
    ULTIMA_ACTUALIZACION  DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA)
);

-- ─── Servicios ───────────────────────────────────────────────
CREATE TABLE SERVICIO (
    ID_SERVICIO       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_SERVICIO   VARCHAR(50)   NOT NULL,
    DESCRIPCION       VARCHAR(255),
    PRECIO            DECIMAL(10,2) NOT NULL,
    DURACION_ESTIMADA INT,                          -- minutos
    ESTADO            BOOLEAN       DEFAULT TRUE
);

-- ─── Relación Servicio ↔ Veterinario (N:M) ───────────────────
CREATE TABLE SERVICIO_VETERINARIO (
    ID_SERVICIO_VETERINARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_SERVICIO             INT NOT NULL,
    ID_VETERINARIO          INT NOT NULL,
    FECHA_ASIGNACION        DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_SERVICIO)    REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT UQ_SERVICIO_VETERINARIO UNIQUE (ID_SERVICIO, ID_VETERINARIO)
);

-- ─── Citas ───────────────────────────────────────────────────
CREATE TABLE CITA (
    ID_CITA        INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE     INT NOT NULL,
    ID_MASCOTA     INT NOT NULL,
    ID_SERVICIO    INT NOT NULL,
    ID_VETERINARIO INT NOT NULL,
    FECHA_HORA     DATETIME NOT NULL,
    ESTADO         VARCHAR(20) DEFAULT 'PENDIENTE'
                   CHECK (ESTADO IN ('PENDIENTE','CANCELADA','REALIZADA')),
    OBSERVACIONES  VARCHAR(255),
    FECHA_REGISTRO DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_CLIENTE)  REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_MASCOTA)  REFERENCES MASCOTA(ID_MASCOTA),
    FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);

-- ─── Vacunas aplicadas ───────────────────────────────────────
CREATE TABLE VACUNA_APLICADA (
    ID_VACUNA        INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE           VARCHAR(50)  NOT NULL,
    DESCRIPCION      VARCHAR(255),
    PERIODO_MESES    INT          NOT NULL,
    FECHA_APLICACION DATE         NOT NULL,
    FECHA_PROXIMA    DATE         NOT NULL,
    ID_MASCOTA       INT,
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA)
);

-- ─── Método de pago ──────────────────────────────────────────
CREATE TABLE METODO_PAGO (
    ID_METODO_PAGO INT AUTO_INCREMENT PRIMARY KEY,
    METODO         VARCHAR(255) NOT NULL,
    VALOR_TOTAL    DECIMAL(10,2) NOT NULL,
    CUENTA_ORIGEN  VARCHAR(20),
    CUENTA_DESTINO VARCHAR(20),
    CONSTRAINT CHK_METODO CHECK (METODO IN ('EFECTIVO','TRANSFERENCIA BANCARIA'))
);

-- ─── Atención médica ─────────────────────────────────────────
CREATE TABLE ATENCION_MEDICA (
    ID_ATENCION_MEDICA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CITA            INT NOT NULL,
    FECHA              DATETIME DEFAULT NOW(),
    DIAGNOSTICO        TEXT,
    TRATAMIENTO        TEXT,
    OBSERVACIONES      TEXT,
    FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA)
);

-- ─── Medicamentos ────────────────────────────────────────────
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE         VARCHAR(100)  NOT NULL,
    DESCRIPCION    VARCHAR(255),
    PRECIO         DECIMAL(10,2) NOT NULL,
    STOCK          INT           DEFAULT 0,
    ESTADO         BOOLEAN       DEFAULT TRUE
);

-- ─── Medicamentos recetados ──────────────────────────────────
CREATE TABLE MEDICAMENTO_RECETADO (
    ID_MEDICAMENTO_RECETADO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ATENCION_MEDICA      INT NOT NULL,
    ID_MEDICAMENTO          INT NOT NULL,
    DOSIS                   VARCHAR(50),
    FRECUENCIA              VARCHAR(50),
    DURACION                VARCHAR(50),
    FOREIGN KEY (ID_ATENCION_MEDICA) REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA),
    FOREIGN KEY (ID_MEDICAMENTO)     REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);

-- ─── Instrumentos médicos ────────────────────────────────────
CREATE TABLE INSTRUMENTO_MEDICO (
    ID_INSTRUMENTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE         VARCHAR(100)  NOT NULL,
    DESCRIPCION    VARCHAR(255),
    COSTO_USO      DECIMAL(10,2) NOT NULL,
    ESTADO         BOOLEAN       DEFAULT TRUE
);

-- ─── Instrumentos usados ─────────────────────────────────────
CREATE TABLE INSTRUMENTO_USADO (
    ID_INSTRUMENTO_USADO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ATENCION_MEDICA   INT NOT NULL,
    ID_INSTRUMENTO       INT NOT NULL,
    FOREIGN KEY (ID_ATENCION_MEDICA) REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA),
    FOREIGN KEY (ID_INSTRUMENTO)     REFERENCES INSTRUMENTO_MEDICO(ID_INSTRUMENTO)
);

-- ─── Historial médico ────────────────────────────────────────
CREATE TABLE HISTORIAL_MEDICO ( 
    ID_HISTORIAL INT AUTO_INCREMENT PRIMARY KEY, 
    ID_MASCOTA INT NOT NULL, 
    ID_CITA INT, 
    FECHA DATETIME DEFAULT NOW(), 
    ID_ATENCION_MEDICA INT NULL, 
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA), 
    FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA), 
    FOREIGN KEY (ID_ATENCION_MEDICA) REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA) 
);

-- ─── Facturas ────────────────────────────────────────────────
CREATE TABLE FACTURA (
    ID_FACTURA     INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE     INT NOT NULL,
    FECHA          DATETIME      DEFAULT NOW(),
    SUBTOTAL       DECIMAL(10,2) NOT NULL,
    IVA            DECIMAL(10,2) NOT NULL,
    TOTAL          DECIMAL(10,2) NOT NULL,
    ESTADO         VARCHAR(20)   DEFAULT 'PENDIENTE'
                   CHECK (ESTADO IN ('PENDIENTE','PAGADA','ANULADA')),
    ID_METODO_PAGO INT,
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES CLIENTE(ID_CLIENTE)
);

-- ─── Detalle de factura ──────────────────────────────────────
CREATE TABLE DETALLE_FACTURA (
    ID_DETALLE         INT AUTO_INCREMENT PRIMARY KEY,
    ID_FACTURA         INT NOT NULL,
    ID_SERVICIO        INT NOT NULL,
    CANTIDAD           INT NOT NULL DEFAULT 1,
    PRECIO_UNITARIO    DECIMAL(10,2) NOT NULL,
    DESCUENTO          DECIMAL(10,2) DEFAULT 0,
    TOTAL              DECIMAL(10,2) NOT NULL,
    ID_ATENCION_MEDICA INT,
    FOREIGN KEY (ID_FACTURA)           REFERENCES FACTURA(ID_FACTURA),
    FOREIGN KEY (ID_SERVICIO)          REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_ATENCION_MEDICA)   REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA)
);

-- ─── Configuración de recordatorios ─────────────────────────
CREATE TABLE RECORDATORIO_CONFIG (
    ID_CONFIG         INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_RECORDATORIO VARCHAR(50)  NOT NULL,   -- 'VACUNA' | 'CITA'
    ANTICIPACION      VARCHAR(20)  NOT NULL,   -- '15_DIAS', '7_DIAS', etc.
    MENSAJE           VARCHAR(255) NOT NULL,
    ACTIVO            BOOLEAN      DEFAULT TRUE
);

-- ─── Recordatorios enviados ──────────────────────────────────
CREATE TABLE RECORDATORIO_ENVIADO (
    ID_RECORDATORIO   INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO        INT,
    ID_CITA           INT,
    ID_VACUNA         INT,
    TIPO              VARCHAR(20)  NOT NULL,   -- 'VACUNA' | 'CITA'
    MENSAJE           VARCHAR(500) NOT NULL,
    FECHA_ENVIO       DATETIME     DEFAULT NOW(),
    CONTADOR_MOSTRADO INT          DEFAULT 0,
    LEIDO             BOOLEAN      DEFAULT FALSE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CITA)    REFERENCES CITA(ID_CITA),
    FOREIGN KEY (ID_VACUNA)  REFERENCES VACUNA_APLICADA(ID_VACUNA)
);
-- ============================================================
--  MÓDULO 2 | SPs de Usuarios, Clientes y Veterinarios (MySQL)
-- ============================================================

-- ════════════════════════════════════════════════════════════
--  USUARIOS
-- ════════════════════════════════════════════════════════════

DELIMITER //


CREATE OR REPLACE PROCEDURE SP_VALIDAR_USUARIO(
    IN p_EMAIL VARCHAR(100),
    IN p_CONTRASENA VARCHAR(100)
)
BEGIN
    SELECT 
        U.ID_USUARIO, 
        U.CORREO_ELECTRONICO AS EMAIL,
        U.ROL,
        U.ESTADO,
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = p_EMAIL) 
                THEN 'VETERINARIO'
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = p_EMAIL) 
                THEN 'RECEPCIONISTA'
            ELSE U.ROL
        END AS ROL_EFECTIVO,
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = p_EMAIL) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM VETERINARIO WHERE CORREO_ELECTRONICO = p_EMAIL)
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = p_EMAIL) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = p_EMAIL)
            ELSE 'Administrador'
        END AS NOMBRE_COMPLETO
    FROM USUARIO U
    WHERE U.CORREO_ELECTRONICO = p_EMAIL
      AND U.CONTRASENA = p_CONTRASENA
      AND U.ESTADO = TRUE;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO(
    IN p_EMAIL VARCHAR(100),
    IN p_CONTRASENA VARCHAR(100),
    IN p_ROL VARCHAR(20)
)
BEGIN
    DECLARE v_ID_USUARIO INT;
    
    IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = p_EMAIL) THEN
        INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL)
        VALUES (p_EMAIL, p_CONTRASENA, IFNULL(p_ROL, 'ADMINISTRADOR'));
        SELECT LAST_INSERT_ID() AS ID_USUARIO;
    ELSE
        SELECT -1 AS ID_USUARIO;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_EXISTE_USUARIO(
    IN p_EMAIL VARCHAR(100)
)
BEGIN
    SELECT ID_USUARIO FROM USUARIO WHERE CORREO_ELECTRONICO = p_EMAIL;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_USUARIO(
    IN p_EMAIL VARCHAR(100)
)
BEGIN
    SELECT 
        U.ID_USUARIO,
        U.CORREO_ELECTRONICO,
        U.ROL,
        U.FECHA_CREACION,
        U.ESTADO,
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN 'VETERINARIO'
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN 'RECEPCIONISTA'
            ELSE U.ROL
        END AS ROL_EFECTIVO,
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO V WHERE V.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN (SELECT CONCAT(V.NOMBRE, ' ', V.APELLIDO) FROM VETERINARIO V WHERE V.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO)
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA R WHERE R.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN (SELECT CONCAT(R.NOMBRE, ' ', R.APELLIDO) FROM RECEPCIONISTA R WHERE R.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO)
            ELSE 'Administrador'
        END AS NOMBRE_COMPLETO
    FROM USUARIO U
    WHERE U.CORREO_ELECTRONICO = p_EMAIL;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CORREOS_USUARIOS()
BEGIN
    SELECT ID_USUARIO, CORREO_ELECTRONICO
    FROM USUARIO
    WHERE ESTADO = TRUE
    ORDER BY CORREO_ELECTRONICO;
END //

-- ════════════════════════════════════════════════════════════
--  CLIENTES
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE SP_INSERTAR_CLIENTE(
    IN p_CEDULA VARCHAR(10),
    IN p_NOMBRE VARCHAR(50),
    IN p_APELLIDO VARCHAR(50),
    IN p_TELEFONO VARCHAR(15),
    IN p_DIRECCION VARCHAR(100),
    IN p_CORREO_ELECTRONICO VARCHAR(100)
)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE CEDULA = p_CEDULA) THEN
        INSERT INTO CLIENTE (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
        VALUES (p_CEDULA, p_NOMBRE, p_APELLIDO, p_TELEFONO, p_DIRECCION, p_CORREO_ELECTRONICO);
        SELECT LAST_INSERT_ID() AS ID_CLIENTE;
    ELSE
        SELECT -1 AS ID_CLIENTE;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CLIENTE(
    IN p_ID_CLIENTE INT,
    IN p_CEDULA VARCHAR(10),
    IN p_NOMBRE VARCHAR(50),
    IN p_APELLIDO VARCHAR(50),
    IN p_TELEFONO VARCHAR(15),
    IN p_DIRECCION VARCHAR(100),
    IN p_CORREO_ELECTRONICO VARCHAR(100)
)
BEGIN
    UPDATE CLIENTE
    SET CEDULA = p_CEDULA, NOMBRE = p_NOMBRE, APELLIDO = p_APELLIDO,
        TELEFONO = p_TELEFONO, DIRECCION = p_DIRECCION,
        CORREO_ELECTRONICO = p_CORREO_ELECTRONICO
    WHERE ID_CLIENTE = p_ID_CLIENTE;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_CLIENTE(
    IN p_ID_CLIENTE INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    DELETE FROM CLIENTE WHERE ID_CLIENTE = p_ID_CLIENTE;
    COMMIT;
    SELECT 1 AS RESULTADO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CLIENTES()
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CEDULAS_CLIENTES()
BEGIN
    SELECT CEDULA FROM CLIENTE ORDER BY CEDULA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CLIENTE_POR_CEDULA(
    IN p_CEDULA VARCHAR(10)
)
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE CEDULA = p_CEDULA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CLIENTE_POR_ID(
    IN p_ID_CLIENTE INT
)
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE ID_CLIENTE = p_ID_CLIENTE;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CLIENTES_POR_NOMBRE(
    IN p_NOMBRE VARCHAR(50)
)
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE
    WHERE NOMBRE LIKE CONCAT('%', p_NOMBRE, '%') 
       OR APELLIDO LIKE CONCAT('%', p_NOMBRE, '%')
    ORDER BY NOMBRE, APELLIDO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CLIENTES_POR_MASCOTA(
    IN p_NOMBRE_MASCOTA VARCHAR(50),
    IN p_NOMBRE_CLIENTE VARCHAR(50)
)
BEGIN
    SELECT DISTINCT
        C.ID_CLIENTE, C.CEDULA, C.NOMBRE, C.APELLIDO, C.TELEFONO,
        C.DIRECCION, C.CORREO_ELECTRONICO, C.FECHA_REGISTRO
    FROM CLIENTE C
    INNER JOIN MASCOTA M ON C.ID_CLIENTE = M.ID_CLIENTE
    WHERE M.NOMBRE LIKE CONCAT('%', p_NOMBRE_MASCOTA, '%')
      AND (p_NOMBRE_CLIENTE IS NULL
           OR C.NOMBRE LIKE CONCAT('%', p_NOMBRE_CLIENTE, '%')
           OR C.APELLIDO LIKE CONCAT('%', p_NOMBRE_CLIENTE, '%'))
    ORDER BY C.NOMBRE, C.APELLIDO;
END //

-- ════════════════════════════════════════════════════════════
--  VETERINARIOS
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE SP_INSERTAR_VETERINARIO(
    IN p_CEDULA VARCHAR(10),
    IN p_NOMBRE VARCHAR(50),
    IN p_APELLIDO VARCHAR(50),
    IN p_TELEFONO VARCHAR(15),
    IN p_ID_ESPECIALIDAD INT,
    IN p_PAGO_MENSUAL DECIMAL(10,2),
    IN p_DIRECCION VARCHAR(100),
    IN p_CORREO_ELECTRONICO VARCHAR(100)
)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM VETERINARIO WHERE CEDULA = p_CEDULA) THEN
        INSERT INTO VETERINARIO (CEDULA, NOMBRE, APELLIDO, TELEFONO, ID_ESPECIALIDAD,
                                 PAGO_MENSUAL, DIRECCION, CORREO_ELECTRONICO)
        VALUES (p_CEDULA, p_NOMBRE, p_APELLIDO, p_TELEFONO, p_ID_ESPECIALIDAD,
                IFNULL(p_PAGO_MENSUAL, 460.00), p_DIRECCION, p_CORREO_ELECTRONICO);
        SELECT LAST_INSERT_ID() AS ID_VETERINARIO;
    ELSE
        SELECT -1 AS ID_VETERINARIO;
    END IF;
END //
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_VETERINARIO(
    IN p_ID_VETERINARIO     INT,
    IN p_CEDULA             VARCHAR(10),
    IN p_NOMBRE             VARCHAR(50),
    IN p_APELLIDO           VARCHAR(50),
    IN p_TELEFONO           VARCHAR(15),
    IN p_ID_ESPECIALIDAD    INT,
    IN p_PAGO_MENSUAL       DECIMAL(10,2),
    IN p_DIRECCION          VARCHAR(100),
    IN p_CORREO_ELECTRONICO VARCHAR(100)
)
BEGIN
    DECLARE v_EMAIL_ACTUAL VARCHAR(100);
    DECLARE v_FILAS_AFECTADAS INT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS FILAS_AFECTADAS;
    END;
    
    START TRANSACTION;
    
    -- 1. Obtener email actual del veterinario
    SELECT CORREO_ELECTRONICO INTO v_EMAIL_ACTUAL
    FROM VETERINARIO
    WHERE ID_VETERINARIO = p_ID_VETERINARIO;
    
    IF v_EMAIL_ACTUAL IS NULL THEN
        ROLLBACK;
        SELECT 0 AS FILAS_AFECTADAS;
        LEAVE;
    END IF;
    
    -- 2. Si el email cambió, actualizar en USUARIO
    --    La FK con ON UPDATE CASCADE actualizará VETERINARIO automáticamente
    IF v_EMAIL_ACTUAL <> p_CORREO_ELECTRONICO THEN
        -- Verificar que el nuevo email no esté en uso por OTRO usuario
        IF EXISTS (
            SELECT 1 FROM USUARIO
            WHERE CORREO_ELECTRONICO = p_CORREO_ELECTRONICO
        ) THEN
            ROLLBACK;
            SELECT 0 AS FILAS_AFECTADAS;
            LEAVE;
        END IF;
        
        -- Actualizar en USUARIO (ON UPDATE CASCADE actualizará VETERINARIO)
        UPDATE USUARIO
        SET CORREO_ELECTRONICO = p_CORREO_ELECTRONICO
        WHERE CORREO_ELECTRONICO = v_EMAIL_ACTUAL;
    END IF;
    
    -- 3. Actualizar el resto de campos de VETERINARIO
    UPDATE VETERINARIO
    SET CEDULA          = p_CEDULA,
        NOMBRE          = p_NOMBRE,
        APELLIDO        = p_APELLIDO,
        TELEFONO        = p_TELEFONO,
        ID_ESPECIALIDAD = p_ID_ESPECIALIDAD,
        PAGO_MENSUAL    = p_PAGO_MENSUAL,
        DIRECCION       = p_DIRECCION,
        CORREO_ELECTRONICO = p_CORREO_ELECTRONICO
    WHERE ID_VETERINARIO = p_ID_VETERINARIO;
    
    SET v_FILAS_AFECTADAS = ROW_COUNT();
    
    COMMIT;
    SELECT v_FILAS_AFECTADAS AS FILAS_AFECTADAS;
    
END //


CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIOS()
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA, 
        V.NOMBRE, 
        V.APELLIDO, 
        V.TELEFONO,
        V.PAGO_MENSUAL, 
        V.DIRECCION, 
        V.CORREO_ELECTRONICO, 
        V.FECHA_REGISTRO,
        V.ID_ESPECIALIDAD, 
        E.NOMBRE_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    ORDER BY V.NOMBRE, V.APELLIDO;
END //

CREATE OR REPLACE PROCEDURE SP_BUSCAR_VETERINARIOS(
    IN p_TERMINO VARCHAR(100)
)
BEGIN
    SELECT V.ID_VETERINARIO, 
           V.CEDULA, 
           V.NOMBRE, 
           V.APELLIDO, 
           V.TELEFONO,
           V.ID_ESPECIALIDAD,
           E.NOMBRE_ESPECIALIDAD,
           V.CORREO_ELECTRONICO
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.NOMBRE LIKE CONCAT('%', p_TERMINO, '%') 
       OR V.APELLIDO LIKE CONCAT('%', p_TERMINO, '%')
       OR V.CEDULA LIKE CONCAT('%', p_TERMINO, '%')
    ORDER BY V.NOMBRE ASC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIO_POR_CEDULA(
    IN p_CEDULA VARCHAR(10)
)
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           E.NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.CEDULA = p_CEDULA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIO_POR_ID(
    IN p_ID_VETERINARIO INT
)
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           E.NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.ID_VETERINARIO = p_ID_VETERINARIO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIOS_POR_NOMBRE(
    IN p_NOMBRE VARCHAR(50)
)
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           E.NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.NOMBRE LIKE CONCAT('%', p_NOMBRE, '%') 
       OR V.APELLIDO LIKE CONCAT('%', p_NOMBRE, '%')
    ORDER BY V.NOMBRE, V.APELLIDO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIOS_POR_ESPECIALIDAD(
    IN p_NOMBRE_ESPECIALIDAD VARCHAR(50)
)
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           E.NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    INNER JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE E.NOMBRE_ESPECIALIDAD LIKE CONCAT('%', p_NOMBRE_ESPECIALIDAD, '%');
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_ESPECIALIDADES()
BEGIN
    SELECT ID_ESPECIALIDAD, NOMBRE_ESPECIALIDAD
    FROM ESPECIALIDAD_VETERINARIA
    ORDER BY NOMBRE_ESPECIALIDAD;
END //

-- ════════════════════════════════════════════════════════════
--  RECEPCIONISTAS
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_RECEPCIONISTA(
    IN p_CEDULA VARCHAR(10),
    IN p_NOMBRE VARCHAR(50),
    IN p_APELLIDO VARCHAR(50),
    IN p_TELEFONO VARCHAR(15),
    IN p_DIRECCION VARCHAR(100),
    IN p_EMAIL VARCHAR(100),
    IN p_CONTRASENA VARCHAR(100)
)
BEGIN
    DECLARE v_ID_USUARIO INT;
    DECLARE v_ID_RECEPCIONISTA INT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT -3 AS RESULTADO, ERROR_MESSAGE() AS MENSAJE;
    END;
    
    START TRANSACTION;
    
    -- 1. Verificar que el email no exista en USUARIO
    IF EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = p_EMAIL) THEN
        SELECT -1 AS RESULTADO, 'El correo electrónico ya está registrado' AS MENSAJE;
        ROLLBACK;
        LEAVE;
    END IF;
    
    -- 2. Verificar que la cédula no exista en RECEPCIONISTA
    IF EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CEDULA = p_CEDULA) THEN
        SELECT -2 AS RESULTADO, 'La cédula ya está registrada' AS MENSAJE;
        ROLLBACK;
        LEAVE;
    END IF;
    
    -- 3. Insertar en USUARIO
    INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL)
    VALUES (p_EMAIL, p_CONTRASENA, 'RECEPCIONISTA');
    
    SET v_ID_USUARIO = LAST_INSERT_ID();
    
    -- 4. Insertar en RECEPCIONISTA
    INSERT INTO RECEPCIONISTA 
        (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
    VALUES 
        (p_CEDULA, p_NOMBRE, p_APELLIDO, p_TELEFONO, p_DIRECCION, p_EMAIL);
    
    SET v_ID_RECEPCIONISTA = LAST_INSERT_ID();
    
    COMMIT;
    SELECT 1 AS RESULTADO, 'Recepcionista registrado correctamente' AS MENSAJE, v_ID_RECEPCIONISTA AS ID;
END //

-- ════════════════════════════════════════════════════════════
--  RESTABLECER CONTRASEÑA
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE SP_RESTABLECER_CONTRASENA(
    IN p_EMAIL VARCHAR(100),
    IN p_NUEVA_CONTRASENA VARCHAR(100)
)
BEGIN
    IF EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = p_EMAIL AND ESTADO = TRUE) THEN
        UPDATE USUARIO
        SET CONTRASENA = p_NUEVA_CONTRASENA
        WHERE CORREO_ELECTRONICO = p_EMAIL;
        
        SELECT 1 AS RESULTADO, 'Contraseña actualizada correctamente' AS MENSAJE;
    ELSE
        SELECT 0 AS RESULTADO, 'Usuario no encontrado' AS MENSAJE;
    END IF;
END //

DELIMITER ;

-- ============================================================
--  MÓDULO 3 | SPs de Mascotas y Citas (MySQL)
-- ============================================================

DELIMITER //

-- ════════════════════════════════════════════════════════════
--  MASCOTAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_INSERTAR_MASCOTA(
    IN p_ID_CLIENTE INT,
    IN p_NOMBRE VARCHAR(50),
    IN p_ESPECIE VARCHAR(30),
    IN p_RAZA VARCHAR(50),
    IN p_SEXO CHAR(1),
    IN p_FECHA_NACIMIENTO DATE,
    IN p_PESO DECIMAL(5,2),
    IN p_COLOR VARCHAR(30),
    IN p_FOTO LONGBLOB
)
BEGIN
    INSERT INTO MASCOTA (ID_CLIENTE, NOMBRE, ESPECIE, RAZA, SEXO, FECHA_NACIMIENTO, PESO, COLOR, FOTO)
    VALUES (p_ID_CLIENTE, p_NOMBRE, p_ESPECIE, p_RAZA, p_SEXO, p_FECHA_NACIMIENTO, p_PESO, p_COLOR, p_FOTO);
    SELECT LAST_INSERT_ID() AS ID_MASCOTA;
END //

CREATE PROCEDURE SP_ACTUALIZAR_MASCOTA(
    IN p_ID_MASCOTA INT,
    IN p_ID_CLIENTE INT,
    IN p_NOMBRE VARCHAR(50),
    IN p_ESPECIE VARCHAR(30),
    IN p_RAZA VARCHAR(50),
    IN p_SEXO CHAR(1),
    IN p_FECHA_NACIMIENTO DATE,
    IN p_PESO DECIMAL(5,2),
    IN p_COLOR VARCHAR(30),
    IN p_FOTO LONGBLOB
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        RESIGNAL;
    END;
    
    UPDATE MASCOTA
    SET ID_CLIENTE = p_ID_CLIENTE,
        NOMBRE = p_NOMBRE,
        ESPECIE = p_ESPECIE,
        RAZA = IFNULL(p_RAZA, RAZA),
        SEXO = IFNULL(p_SEXO, SEXO),
        FECHA_NACIMIENTO = IFNULL(p_FECHA_NACIMIENTO, FECHA_NACIMIENTO),
        PESO = IFNULL(p_PESO, PESO),
        COLOR = IFNULL(p_COLOR, COLOR),
        FOTO = IFNULL(p_FOTO, FOTO)
    WHERE ID_MASCOTA = p_ID_MASCOTA;
    
    IF ROW_COUNT() = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No se actualizó ninguna mascota';
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_MASCOTA(
    IN p_ID_MASCOTA INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;
    
    START TRANSACTION;
    
    -- Verificar si la mascota tiene atenciones médicas (antecedentes clínicos)
    IF EXISTS (
        SELECT 1
        FROM ATENCION_MEDICA AM
        INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
        WHERE C.ID_MASCOTA = p_ID_MASCOTA
    ) THEN
        SIGNAL SQLSTATE '45000' 
            SET MESSAGE_TEXT = 'La mascota ya posee una cita médica realizada. No se puede eliminar.';
        ROLLBACK;
    END IF;
    
    -- Verificar si la mascota tiene citas pendientes
    IF EXISTS (SELECT 1 FROM CITA WHERE ID_MASCOTA = p_ID_MASCOTA AND ESTADO = 'PENDIENTE') THEN
        SIGNAL SQLSTATE '45000' 
            SET MESSAGE_TEXT = 'La mascota tiene citas pendientes. No se puede eliminar.';
        ROLLBACK;
    END IF;
    
    -- Eliminar ficha médica (solo si existe)
    DELETE FROM FICHA_MEDICA WHERE ID_MASCOTA = p_ID_MASCOTA;
    
    -- Eliminar mascota
    DELETE FROM MASCOTA WHERE ID_MASCOTA = p_ID_MASCOTA;
    
    COMMIT;
    SELECT 1 AS RESULTADO;
    
END //

CREATE PROCEDURE SP_OBTENER_MASCOTAS_POR_CLIENTE(IN p_ID_CLIENTE INT)
BEGIN
    IF p_ID_CLIENTE = 0 THEN
        SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
               M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
               CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_DUENO,
               C.CEDULA AS CEDULA_CLIENTE, C.ID_CLIENTE
        FROM MASCOTA M
        INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE;
    ELSE
        SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
               M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
               CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_DUENO,
               C.CEDULA AS CEDULA_CLIENTE, C.ID_CLIENTE
        FROM MASCOTA M
        INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
        WHERE M.ID_CLIENTE = p_ID_CLIENTE;
    END IF;
END //

CREATE PROCEDURE SP_OBTENER_MASCOTAS()
BEGIN
    SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           C.ID_CLIENTE,
           CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_DUENO,
           C.CEDULA AS CEDULA_CLIENTE,
           C.TELEFONO AS TELEFONO_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    ORDER BY M.NOMBRE;
END //

CREATE PROCEDURE SP_BUSCAR_MASCOTAS(IN p_TERMINO VARCHAR(100))
BEGIN
    SELECT M.ID_MASCOTA, M.ID_CLIENTE, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_CLIENTE,
           C.CEDULA AS CEDULA_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    WHERE M.NOMBRE LIKE CONCAT('%', p_TERMINO, '%') 
       OR C.CEDULA LIKE CONCAT('%', p_TERMINO, '%')
       OR C.NOMBRE LIKE CONCAT('%', p_TERMINO, '%')
       OR C.APELLIDO LIKE CONCAT('%', p_TERMINO, '%')
    ORDER BY M.NOMBRE;
END //

CREATE PROCEDURE SP_OBTENER_MASCOTA_POR_ID(IN p_ID_MASCOTA INT)
BEGIN
    SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           C.ID_CLIENTE,
           CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_DUENO,
           C.CEDULA AS CEDULA_CLIENTE,
           C.TELEFONO AS TELEFONO_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    WHERE M.ID_MASCOTA = p_ID_MASCOTA;
END //

CREATE PROCEDURE SP_OBTENER_FOTO_MASCOTA(IN p_ID_MASCOTA INT)
BEGIN
    SELECT FOTO FROM MASCOTA WHERE ID_MASCOTA = p_ID_MASCOTA;
END //

-- ════════════════════════════════════════════════════════════
--  CITAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_AGENDAR_CITA(
    IN p_ID_CLIENTE INT,
    IN p_ID_MASCOTA INT,
    IN p_ID_SERVICIO INT,
    IN p_ID_VETERINARIO INT,
    IN p_FECHA_HORA DATETIME,
    IN p_OBSERVACIONES VARCHAR(255)
)
BEGIN
    DECLARE v_ID_CITA INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT -2 AS ID_CITA;
    END;
    
    START TRANSACTION;
    
    IF EXISTS (
        SELECT 1 FROM CITA
        WHERE FECHA_HORA = p_FECHA_HORA 
        AND ID_VETERINARIO = p_ID_VETERINARIO
        AND ESTADO = 'PENDIENTE'
    ) THEN
        ROLLBACK;
        SELECT -1 AS ID_CITA;
    ELSE
        INSERT INTO CITA (ID_CLIENTE, ID_MASCOTA, ID_SERVICIO, ID_VETERINARIO, FECHA_HORA, OBSERVACIONES)
        VALUES (p_ID_CLIENTE, p_ID_MASCOTA, p_ID_SERVICIO, p_ID_VETERINARIO, p_FECHA_HORA, p_OBSERVACIONES);
        
        SET v_ID_CITA = LAST_INSERT_ID();
        COMMIT;
        SELECT v_ID_CITA AS ID_CITA;
    END IF;
END //

CREATE PROCEDURE SP_ACTUALIZAR_CITA_COMPLETA(
    IN p_ID_CITA INT,
    IN p_ID_CLIENTE INT,
    IN p_ID_MASCOTA INT,
    IN p_ID_SERVICIO INT,
    IN p_ID_VETERINARIO INT,
    IN p_FECHA_HORA DATETIME,
    IN p_ESTADO VARCHAR(20),
    IN p_OBSERVACIONES VARCHAR(255)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    UPDATE CITA
    SET ID_CLIENTE = p_ID_CLIENTE, 
        ID_MASCOTA = p_ID_MASCOTA, 
        ID_SERVICIO = p_ID_SERVICIO,
        ID_VETERINARIO = p_ID_VETERINARIO,
        FECHA_HORA = p_FECHA_HORA, 
        ESTADO = p_ESTADO,
        OBSERVACIONES = p_OBSERVACIONES
    WHERE ID_CITA = p_ID_CITA;
    COMMIT;
    SELECT 1 AS RESULTADO;
END //

CREATE PROCEDURE SP_CANCELAR_CITA(
    IN p_ID_CITA INT,
    IN p_MOTIVO VARCHAR(255)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    UPDATE CITA
    SET ESTADO = 'CANCELADA',
        OBSERVACIONES = CONCAT(IFNULL(OBSERVACIONES, ''), 
                               IF(OBSERVACIONES IS NULL, '', ' | '),
                               'Cancelación: ', IFNULL(p_MOTIVO, 'Sin motivo especificado'))
    WHERE ID_CITA = p_ID_CITA;
    
    IF ROW_COUNT() > 0 THEN
        COMMIT;
        SELECT 1 AS RESULTADO;
    ELSE
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END IF;
END //

CREATE PROCEDURE SP_ACTUALIZAR_ESTADO_CITA(
    IN p_ID_CITA INT,
    IN p_ESTADO VARCHAR(20)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    UPDATE CITA SET ESTADO = p_ESTADO WHERE ID_CITA = p_ID_CITA;
    
    IF ROW_COUNT() > 0 THEN
        COMMIT;
        SELECT 1 AS RESULTADO;
    ELSE
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END IF;
END //

CREATE PROCEDURE SP_ELIMINAR_CITA_COMPLETA(IN p_ID_CITA INT)
BEGIN
    DELETE FROM CITA WHERE ID_CITA = p_ID_CITA;
END //

CREATE PROCEDURE SP_OBTENER_TODAS_LAS_CITAS()
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES, C.FECHA_REGISTRO
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    ORDER BY C.FECHA_HORA DESC;
END //

CREATE PROCEDURE SP_OBTENER_CITAS_POR_FECHA(IN p_FECHA DATE)
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE DATE(C.FECHA_HORA) = p_FECHA
    ORDER BY C.FECHA_HORA;
END //

CREATE PROCEDURE SP_OBTENER_CITA_COMPLETA(IN p_ID_CITA INT)
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA, M.SEXO,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES, C.FECHA_REGISTRO
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE C.ID_CITA = p_ID_CITA;
END //

CREATE PROCEDURE SP_OBTENER_CITAS_PENDIENTES()
BEGIN
    SELECT C.ID_CITA,
           C.ESTADO, C.FECHA_HORA, C.OBSERVACIONES, C.FECHA_REGISTRO,
           CL.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE, CL.CEDULA AS CEDULA_CLIENTE,
           M.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE AS ESPECIE_MASCOTA,
           S.ID_SERVICIO, S.NOMBRE_SERVICIO,
           V.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           CONCAT(S.NOMBRE_SERVICIO, ' - ', DATE_FORMAT(C.FECHA_HORA, '%d/%m/%Y %H:%i'),
                  ' - ', M.NOMBRE, ' (Dr. ', V.APELLIDO, ')') AS DISPLAY_TEXT
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE C.ESTADO = 'PENDIENTE'
    ORDER BY C.FECHA_HORA ASC;
END //

CREATE PROCEDURE SP_VERIFICAR_CITA_PENDIENTE(IN p_ID_CITA INT)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ATENCION_MEDICA WHERE ID_CITA = p_ID_CITA) THEN
        SELECT 1 AS RESULTADO;
    ELSE
        SELECT 0 AS RESULTADO;
    END IF;
END //

CREATE PROCEDURE SP_OBTENER_ATENCIONES_POR_CITA(IN p_ID_CITA INT)
BEGIN
    SELECT AM.ID_ATENCION_MEDICA, AM.FECHA, AM.DIAGNOSTICO,
           AM.TRATAMIENTO, AM.OBSERVACIONES,
           CONCAT(V.NOMBRE, ' ', V.APELLIDO) AS VETERINARIO
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE AM.ID_CITA = p_ID_CITA
    ORDER BY AM.FECHA DESC;
END //

DELIMITER ;

-- ════════════════════════════════════════════════════════════
--  TRIGGER para actualizar estado de cita
-- ════════════════════════════════════════════════════════════

DELIMITER //

CREATE TRIGGER TR_ACTUALIZAR_ESTADO_CITA_INSERT
AFTER INSERT ON ATENCION_MEDICA
FOR EACH ROW
BEGIN
    UPDATE CITA C
    SET ESTADO = 'REALIZADA'
    WHERE C.ID_CITA = NEW.ID_CITA AND C.ESTADO <> 'CANCELADA';
END //

CREATE TRIGGER TR_ACTUALIZAR_ESTADO_CITA_DELETE
AFTER DELETE ON ATENCION_MEDICA
FOR EACH ROW
BEGIN
    IF NOT EXISTS (SELECT 1 FROM ATENCION_MEDICA WHERE ID_CITA = OLD.ID_CITA) THEN
        UPDATE CITA C
        SET ESTADO = 'PENDIENTE'
        WHERE C.ID_CITA = OLD.ID_CITA AND C.ESTADO <> 'CANCELADA';
    END IF;
END //

DELIMITER ;
-- ============================================================
--  MODULO 4 | SPs de Atencion Medica, Instrumentos y Medicamentos
-- ============================================================

DELIMITER //

-- ============================================================
--  ATENCION MEDICA
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_CITAS_POR_SERVICIO_VETERINARIO(
    IN p_ID_SERVICIO INT,
    IN p_ID_VETERINARIO INT,
    IN p_ESTADO VARCHAR(20)
)
BEGIN
    SELECT C.ID_CITA, C.ID_CLIENTE,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO, C.FECHA_HORA, C.ESTADO,
           CONCAT('Cliente: ', CL.NOMBRE, ' ', CL.APELLIDO,
                  ' - Fecha: ', DATE_FORMAT(C.FECHA_HORA, '%d/%m/%Y %H:%i:%s')) AS DESCRIPCION_CITA
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE C.ID_SERVICIO = p_ID_SERVICIO
      AND C.ID_VETERINARIO = p_ID_VETERINARIO
      AND C.ESTADO = p_ESTADO
    ORDER BY C.FECHA_HORA DESC;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_ATENCION_MEDICA(
    IN p_ID_CITA INT,
    IN p_DIAGNOSTICO TEXT,
    IN p_TRATAMIENTO TEXT,
    IN p_OBSERVACIONES TEXT
)
BEGIN
    DECLARE v_ID_ATENCION_MEDICA INT;
    
    IF EXISTS (SELECT 1 FROM CITA WHERE ID_CITA = p_ID_CITA AND ESTADO <> 'CANCELADA') THEN
        INSERT INTO ATENCION_MEDICA (ID_CITA, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES)
        VALUES (p_ID_CITA, p_DIAGNOSTICO, p_TRATAMIENTO, p_OBSERVACIONES);
        
        SELECT LAST_INSERT_ID() AS ID_ATENCION_MEDICA;
    ELSE
        SELECT 0 AS ID_ATENCION_MEDICA;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_TODAS_ATENCIONES_MEDICAS()
BEGIN
    SELECT AM.ID_ATENCION_MEDICA,
           M.NOMBRE AS NOMBRE_MASCOTA,
           CONCAT(V.NOMBRE, ' ', V.APELLIDO) AS NOMBRE_VETERINARIO,
           AM.FECHA, AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    ORDER BY AM.FECHA DESC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_DETALLES_ATENCION_MEDICA(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT AM.ID_ATENCION_MEDICA, AM.FECHA, AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES,
           M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE,
           CONCAT(V.NOMBRE, ' ', V.APELLIDO) AS NOMBRE_VETERINARIO,
           S.NOMBRE_SERVICIO, S.PRECIO AS PRECIO_SERVICIO
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE AM.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_ATENCION_MEDICA(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    DECLARE v_ID_CITA INT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;
    
    START TRANSACTION;
    
    SELECT ID_CITA INTO v_ID_CITA FROM ATENCION_MEDICA WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    DELETE FROM MEDICAMENTO_RECETADO WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    DELETE FROM INSTRUMENTO_USADO WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    DELETE FROM HISTORIAL_MEDICO WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    DELETE FROM ATENCION_MEDICA WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    IF v_ID_CITA IS NOT NULL THEN
        UPDATE CITA SET ESTADO = 'PENDIENTE' WHERE ID_CITA = v_ID_CITA;
    END IF;
    
    COMMIT;
END //

CREATE OR REPLACE PROCEDURE SP_VERIFICAR_ATENCION_MASCOTA(
    IN p_ID_CITA INT,
    IN p_ID_MASCOTA INT
)
BEGIN
    SELECT CASE WHEN EXISTS (
        SELECT 1 
        FROM ATENCION_MEDICA AM
        INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
        WHERE AM.ID_CITA = p_ID_CITA AND C.ID_MASCOTA = p_ID_MASCOTA
    ) THEN 1 ELSE 0 END AS ATENDIDA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_FICHA_MEDICA(
    IN p_ID_MASCOTA INT
)
BEGIN
    SELECT ID_FICHA, ID_MASCOTA, ALERGIAS, ENFERMEDADES_CRONICAS,
           OBSERVACIONES, ULTIMA_ACTUALIZACION
    FROM FICHA_MEDICA
    WHERE ID_MASCOTA = p_ID_MASCOTA;
END //

CREATE OR REPLACE PROCEDURE SP_PREPARAR_COBRO_ATENCION(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT S.NOMBRE_SERVICIO AS ITEM, S.PRECIO, 'SERVICIO' AS TIPO
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE AM.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA
    
    UNION ALL
    
    SELECT M.NOMBRE, M.PRECIO, 'MEDICAMENTO'
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA

    UNION ALL
    
    SELECT I.NOMBRE, I.COSTO_USO, 'INSTRUMENTO'
    FROM INSTRUMENTO_USADO IU
    INNER JOIN INSTRUMENTO_MEDICO I ON IU.ID_INSTRUMENTO = I.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
END //

-- ============================================================
--  INSTRUMENTOS MEDICOS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_INSTRUMENTOS_DISPONIBLES()
BEGIN
    SELECT ID_INSTRUMENTO, NOMBRE, DESCRIPCION, COSTO_USO
    FROM INSTRUMENTO_MEDICO WHERE ESTADO = 1;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_INSTRUMENTO_POR_ID(
    IN p_ID_INSTRUMENTO INT
)
BEGIN
    SELECT ID_INSTRUMENTO, NOMBRE, DESCRIPCION, COSTO_USO
    FROM INSTRUMENTO_MEDICO WHERE ID_INSTRUMENTO = p_ID_INSTRUMENTO;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_INSTRUMENTO_USADO(
    IN p_ID_ATENCION_MEDICA INT,
    IN p_ID_INSTRUMENTO INT
)
BEGIN
    INSERT INTO INSTRUMENTO_USADO (ID_ATENCION_MEDICA, ID_INSTRUMENTO)
    VALUES (p_ID_ATENCION_MEDICA, p_ID_INSTRUMENTO);
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_INSTRUMENTOS_POR_ATENCION(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT IM.NOMBRE, IM.COSTO_USO
    FROM INSTRUMENTO_USADO IU
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_ULTIMO_INSTRUMENTO_USADO(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT ID_INSTRUMENTO_USADO
    FROM INSTRUMENTO_USADO
    WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA
    ORDER BY ID_INSTRUMENTO_USADO DESC
    LIMIT 1;
END //

-- ============================================================
--  MEDICAMENTOS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_MEDICAMENTOS_DISPONIBLES()
BEGIN
    SELECT ID_MEDICAMENTO, NOMBRE, DESCRIPCION, PRECIO
    FROM MEDICAMENTO WHERE ESTADO = 1;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_MEDICAMENTO_POR_ID(
    IN p_ID_MEDICAMENTO INT
)
BEGIN
    SELECT ID_MEDICAMENTO, NOMBRE, DESCRIPCION, PRECIO
    FROM MEDICAMENTO WHERE ID_MEDICAMENTO = p_ID_MEDICAMENTO;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_MEDICAMENTO_RECETADO(
    IN p_ID_ATENCION_MEDICA INT,
    IN p_ID_MEDICAMENTO INT,
    IN p_DOSIS VARCHAR(50),
    IN p_FRECUENCIA VARCHAR(50),
    IN p_DURACION VARCHAR(50)
)
BEGIN
    INSERT INTO MEDICAMENTO_RECETADO
        (ID_ATENCION_MEDICA, ID_MEDICAMENTO, DOSIS, FRECUENCIA, DURACION)
    VALUES
        (p_ID_ATENCION_MEDICA, p_ID_MEDICAMENTO, p_DOSIS, p_FRECUENCIA, p_DURACION);
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_MEDICAMENTOS_POR_ATENCION(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT MED.NOMBRE, MR.DOSIS, MR.FRECUENCIA, MR.DURACION, MED.PRECIO
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_ULTIMO_MEDICAMENTO_RECETADO(
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    SELECT ID_MEDICAMENTO_RECETADO
    FROM MEDICAMENTO_RECETADO
    WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA
    ORDER BY ID_MEDICAMENTO_RECETADO DESC
    LIMIT 1;
END //

DELIMITER ;
-- ============================================================
--  MODULO 5 | SPs de Servicios y Facturas
-- ============================================================

DELIMITER //

-- ============================================================
--  SERVICIOS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_SERVICIOS()
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO ORDER BY NOMBRE_SERVICIO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_SERVICIOS_ACTIVOS()
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA
    FROM SERVICIO WHERE ESTADO = 1 ORDER BY NOMBRE_SERVICIO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_SERVICIO_POR_ID(
    IN p_ID_SERVICIO INT
)
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO WHERE ID_SERVICIO = p_ID_SERVICIO;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_SERVICIO(
    IN p_NOMBRE_SERVICIO VARCHAR(50),
    IN p_DESCRIPCION VARCHAR(255),
    IN p_PRECIO DECIMAL(10,2),
    IN p_DURACION_ESTIMADA INT,
    IN p_ESTADO BOOLEAN
)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = p_NOMBRE_SERVICIO) THEN
        INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
        VALUES (p_NOMBRE_SERVICIO, p_DESCRIPCION, p_PRECIO, p_DURACION_ESTIMADA, p_ESTADO);
        SELECT LAST_INSERT_ID() AS ID_SERVICIO;
    ELSE
        SELECT -1 AS ID_SERVICIO;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_SERVICIO(
    IN p_ID_SERVICIO INT,
    IN p_NOMBRE_SERVICIO VARCHAR(50),
    IN p_DESCRIPCION VARCHAR(255),
    IN p_PRECIO DECIMAL(10,2),
    IN p_DURACION_ESTIMADA INT,
    IN p_ESTADO BOOLEAN
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SELECT 0 AS FILAS_AFECTADAS;
    END;
    
    IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE ID_SERVICIO = p_ID_SERVICIO) THEN
        SELECT 0 AS FILAS_AFECTADAS;
    ELSEIF EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = p_NOMBRE_SERVICIO AND ID_SERVICIO <> p_ID_SERVICIO) THEN
        SELECT -1 AS FILAS_AFECTADAS;
    ELSE
        UPDATE SERVICIO
        SET NOMBRE_SERVICIO = p_NOMBRE_SERVICIO, DESCRIPCION = p_DESCRIPCION,
            PRECIO = p_PRECIO, DURACION_ESTIMADA = p_DURACION_ESTIMADA, ESTADO = p_ESTADO
        WHERE ID_SERVICIO = p_ID_SERVICIO;
        SELECT ROW_COUNT() AS FILAS_AFECTADAS;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_CAMBIAR_ESTADO_SERVICIO(
    IN p_ID_SERVICIO INT,
    IN p_ESTADO BOOLEAN
)
BEGIN
    UPDATE SERVICIO SET ESTADO = p_ESTADO WHERE ID_SERVICIO = p_ID_SERVICIO;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SERVICIO_COMPLETO(
    IN p_ID_SERVICIO INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO = p_ID_SERVICIO;
    DELETE FROM SERVICIO WHERE ID_SERVICIO = p_ID_SERVICIO;
    COMMIT;
    SELECT 1 AS RESULTADO;
END //

CREATE OR REPLACE PROCEDURE SP_ASIGNAR_VETERINARIO_SERVICIO(
    IN p_ID_SERVICIO INT,
    IN p_ID_VETERINARIO INT
)
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO_VETERINARIO
                   WHERE ID_SERVICIO = p_ID_SERVICIO AND ID_VETERINARIO = p_ID_VETERINARIO) THEN
        INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
        VALUES (p_ID_SERVICIO, p_ID_VETERINARIO);
        SELECT 1 AS RESULTADO;
    ELSE
        SELECT 0 AS RESULTADO;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_ASIGNAR_MULTIPLES_VETERINARIOS(
    IN p_ID_SERVICIO INT,
    IN p_IDS_VETERINARIOS TEXT
)
BEGIN
    DECLARE v_CONTADOR INT DEFAULT 0;
    DECLARE v_ID_VETERINARIO INT;
    DECLARE v_done INT DEFAULT FALSE;
    DECLARE v_cursor CURSOR FOR SELECT DISTINCT CAST(value AS UNSIGNED) FROM (SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(p_IDS_VETERINARIOS, ',', n), ',', -1) AS value
        FROM (SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) AS numbers
        WHERE CHAR_LENGTH(p_IDS_VETERINARIOS) - CHAR_LENGTH(REPLACE(p_IDS_VETERINARIOS, ',', '')) >= n-1) AS ids;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_done = TRUE;
    
    OPEN v_cursor;
    
    read_loop: LOOP
        FETCH v_cursor INTO v_ID_VETERINARIO;
        IF v_done THEN
            LEAVE read_loop;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO = p_ID_SERVICIO AND ID_VETERINARIO = v_ID_VETERINARIO) THEN
            INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
            VALUES (p_ID_SERVICIO, v_ID_VETERINARIO);
            SET v_CONTADOR = v_CONTADOR + 1;
        END IF;
    END LOOP;
    
    CLOSE v_cursor;
    SELECT v_CONTADOR AS ASIGNACIONES_REALIZADAS;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_ASIGNACION_VETERINARIO(
    IN p_ID_SERVICIO_VETERINARIO INT
)
BEGIN
    DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO_VETERINARIO = p_ID_SERVICIO_VETERINARIO;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIOS_POR_SERVICIO(
    IN p_ID_SERVICIO INT
)
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA,  
        V.NOMBRE, 
        V.APELLIDO,  
        V.TELEFONO,
        V.ID_ESPECIALIDAD,
        E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD,
        SV.FECHA_ASIGNACION 
    FROM SERVICIO_VETERINARIO SV 
    INNER JOIN VETERINARIO V ON SV.ID_VETERINARIO = V.ID_VETERINARIO 
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD 
    WHERE SV.ID_SERVICIO = p_ID_SERVICIO 
    ORDER BY V.NOMBRE, V.APELLIDO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VETERINARIOS_NO_ASIGNADOS(
    IN p_ID_SERVICIO INT
)
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA, 
        V.NOMBRE, 
        V.APELLIDO,
        V.TELEFONO,
        V.ID_ESPECIALIDAD,
        E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD 
    FROM VETERINARIO V 
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD 
    WHERE V.ID_VETERINARIO NOT IN ( 
        SELECT ID_VETERINARIO  
        FROM SERVICIO_VETERINARIO  
        WHERE ID_SERVICIO = p_ID_SERVICIO 
    ) 
    ORDER BY V.NOMBRE, V.APELLIDO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_SERVICIOS_POR_VETERINARIO(
    IN p_ID_VETERINARIO INT
)
BEGIN
    SELECT SV.ID_SERVICIO_VETERINARIO, S.ID_SERVICIO, S.NOMBRE_SERVICIO
    FROM SERVICIO_VETERINARIO SV
    INNER JOIN SERVICIO S ON SV.ID_SERVICIO = S.ID_SERVICIO
    WHERE SV.ID_VETERINARIO = p_ID_VETERINARIO
    ORDER BY S.NOMBRE_SERVICIO;
END //

-- ============================================================
--  FACTURAS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_FACTURAS_POR_CEDULA(
    IN p_CEDULA_CLIENTE VARCHAR(10)
)
BEGIN
    SELECT F.ID_FACTURA, F.FECHA, F.SUBTOTAL, F.IVA, F.TOTAL, F.ESTADO,
           MP.METODO, MP.VALOR_TOTAL, MP.CUENTA_ORIGEN, MP.CUENTA_DESTINO,
           CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_CLIENTE,
           C.CEDULA AS CEDULA_CLIENTE, C.TELEFONO AS TELEFONO_CLIENTE,
           C.DIRECCION AS DIRECCION_CLIENTE, C.CORREO_ELECTRONICO AS EMAIL_CLIENTE
    FROM FACTURA F
    INNER JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
    INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE C.CEDULA = p_CEDULA_CLIENTE
    ORDER BY F.FECHA DESC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_DETALLE_FACTURA(
    IN p_ID_FACTURA INT
)
BEGIN
    SELECT 
        F.ID_FACTURA,
        F.FECHA,
        F.SUBTOTAL,
        F.IVA,
        F.TOTAL,
        F.ESTADO,
        MP.METODO AS METODO_PAGO,
        CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS NOMBRE_CLIENTE,
        C.CEDULA,
        C.TELEFONO,
        C.DIRECCION,
        C.CORREO_ELECTRONICO
    FROM FACTURA F 
    INNER JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
    INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE F.ID_FACTURA = p_ID_FACTURA
    LIMIT 1;
    
    SELECT 
        S.NOMBRE_SERVICIO,
        IFNULL(S.DESCRIPCION, '') AS DESCRIPCION_SERVICIO,
        DF.PRECIO_UNITARIO,
        DF.TOTAL AS TOTAL_SERVICIO,
        IFNULL(CONCAT(V.NOMBRE, ' ', V.APELLIDO), 'No asignado') AS VETERINARIO
    FROM DETALLE_FACTURA DF
    INNER JOIN SERVICIO S ON DF.ID_SERVICIO = S.ID_SERVICIO
    LEFT JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    LEFT JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    LEFT JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE DF.ID_FACTURA = p_ID_FACTURA
      AND S.NOMBRE_SERVICIO NOT IN ('MEDICAMENTO', 'INSTRUMENTO')
    LIMIT 1;
    
    SELECT DISTINCT
        M.NOMBRE AS NOMBRE_MASCOTA,
        IFNULL(M.ESPECIE, '') AS ESPECIE,
        IFNULL(M.RAZA, '') AS RAZA,
        IFNULL(CAST(AM.DIAGNOSTICO AS CHAR), '') AS DIAGNOSTICO,
        IFNULL(CAST(AM.TRATAMIENTO AS CHAR), '') AS TRATAMIENTO
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    WHERE DF.ID_FACTURA = p_ID_FACTURA;
    
    SELECT DISTINCT
        MED.NOMBRE AS MEDICAMENTO,
        MED.PRECIO,
        IFNULL(MR.DOSIS, '') AS DOSIS,
        IFNULL(MR.FRECUENCIA, '') AS FRECUENCIA,
        IFNULL(MR.DURACION, '') AS DURACION
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO_RECETADO MR ON AM.ID_ATENCION_MEDICA = MR.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
    WHERE DF.ID_FACTURA = p_ID_FACTURA;
    
    SELECT DISTINCT
        IM.NOMBRE AS INSTRUMENTO,
        IM.COSTO_USO
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_USADO IU ON AM.ID_ATENCION_MEDICA = IU.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE DF.ID_FACTURA = p_ID_FACTURA;
    
    SELECT DISTINCT
        VA.NOMBRE AS NOMBRE_VACUNA,
        IFNULL(VA.DESCRIPCION, '') AS DESCRIPCION,
        VA.FECHA_APLICACION,
        VA.FECHA_PROXIMA
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN VACUNA_APLICADA VA ON M.ID_MASCOTA = VA.ID_MASCOTA
    WHERE DF.ID_FACTURA = p_ID_FACTURA;
END //


CREATE PROCEDURE SP_GENERAR_FACTURA_ATENCION(
    IN p_ID_ATENCION_MEDICA INT,
    IN p_METODO VARCHAR(255),
    IN p_CUENTA_ORIGEN VARCHAR(20),
    IN p_CUENTA_DESTINO VARCHAR(20)
)
BEGIN
    DECLARE v_ID_CLIENTE INT;
    DECLARE v_ID_SERVICIO INT;
    DECLARE v_ID_MASCOTA INT;
    DECLARE v_PRECIO_SERVICIO DECIMAL(10,2);
    DECLARE v_SUBTOTAL DECIMAL(10,2);
    DECLARE v_IVA DECIMAL(10,2);
    DECLARE v_TOTAL DECIMAL(10,2);
    DECLARE v_ID_FACTURA INT;
    DECLARE v_ID_METODO_PAGO INT;
    DECLARE v_ID_SERVICIO_MED INT;
    DECLARE v_ID_SERVICIO_INSTR INT;
    DECLARE v_ID_CITA INT;
    DECLARE v_ERROR_MENSAJE TEXT;
    DECLARE v_ERROR_NUMERO INT;
    DECLARE v_ERROR_LINEA INT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            v_ERROR_MENSAJE = MESSAGE_TEXT,
            v_ERROR_NUMERO = MYSQL_ERRNO;
        
        IF @@autocommit = 0 THEN
            ROLLBACK;
        END IF;
        
        SELECT -1 AS ID_FACTURA, v_ERROR_MENSAJE AS ERROR_MENSAJE, v_ERROR_NUMERO AS ERROR_NUMERO, v_ERROR_LINEA AS ERROR_LINEA;
    END;
    
    START TRANSACTION;
    
    SELECT ID_CITA INTO v_ID_CITA 
    FROM ATENCION_MEDICA 
    WHERE ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    IF v_ID_CITA IS NULL THEN
        SET v_ERROR_MENSAJE = CONCAT('No existe la atencion medica con ID: ', p_ID_ATENCION_MEDICA);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_ERROR_MENSAJE;
    END IF;
    
    SELECT ID_CLIENTE, ID_SERVICIO, ID_MASCOTA INTO v_ID_CLIENTE, v_ID_SERVICIO, v_ID_MASCOTA
    FROM CITA 
    WHERE ID_CITA = v_ID_CITA;
    
    SELECT IFNULL(PRECIO, 0) INTO v_PRECIO_SERVICIO
    FROM SERVICIO 
    WHERE ID_SERVICIO = v_ID_SERVICIO;
    
    IF v_ID_CLIENTE IS NULL THEN
        SET v_ERROR_MENSAJE = CONCAT('No se encontro el cliente para la cita ID: ', v_ID_CITA);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_ERROR_MENSAJE;
    END IF;
    
    IF v_ID_SERVICIO IS NULL THEN
        SET v_ERROR_MENSAJE = CONCAT('No se encontro el servicio para la cita ID: ', v_ID_CITA);
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_ERROR_MENSAJE;
    END IF;
    
    SELECT ID_SERVICIO INTO v_ID_SERVICIO_MED FROM SERVICIO WHERE NOMBRE_SERVICIO = 'MEDICAMENTO';
    SELECT ID_SERVICIO INTO v_ID_SERVICIO_INSTR FROM SERVICIO WHERE NOMBRE_SERVICIO = 'INSTRUMENTO';
    
    IF v_ID_SERVICIO_MED IS NULL THEN
        INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
        VALUES ('MEDICAMENTO', 'Medicamentos recetados', 0, 0, 1);
        SET v_ID_SERVICIO_MED = LAST_INSERT_ID();
    END IF;
    
    IF v_ID_SERVICIO_INSTR IS NULL THEN
        INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
        VALUES ('INSTRUMENTO', 'Instrumentos utilizados', 0, 0, 1);
        SET v_ID_SERVICIO_INSTR = LAST_INSERT_ID();
    END IF;
    
    SET v_SUBTOTAL = IFNULL(v_PRECIO_SERVICIO, 0);
    
    SELECT v_SUBTOTAL + IFNULL(SUM(M.PRECIO), 0) INTO v_SUBTOTAL
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    SELECT v_SUBTOTAL + IFNULL(SUM(IM.COSTO_USO), 0) INTO v_SUBTOTAL
    FROM INSTRUMENTO_USADO IU
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    SET v_IVA = v_SUBTOTAL * 0.12;
    SET v_TOTAL = v_SUBTOTAL + v_IVA;
    
    INSERT INTO METODO_PAGO (METODO, VALOR_TOTAL, CUENTA_ORIGEN, CUENTA_DESTINO)
    VALUES (p_METODO, v_TOTAL, p_CUENTA_ORIGEN, p_CUENTA_DESTINO);
    SET v_ID_METODO_PAGO = LAST_INSERT_ID();
    
    INSERT INTO FACTURA (ID_CLIENTE, SUBTOTAL, IVA, TOTAL, ESTADO, ID_METODO_PAGO)
    VALUES (v_ID_CLIENTE, v_SUBTOTAL, v_IVA, v_TOTAL, 'PAGADA', v_ID_METODO_PAGO);
    SET v_ID_FACTURA = LAST_INSERT_ID();
    
    INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
    VALUES (v_ID_FACTURA, v_ID_SERVICIO, 1, v_PRECIO_SERVICIO, v_PRECIO_SERVICIO, p_ID_ATENCION_MEDICA);
    
    INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
    SELECT v_ID_FACTURA, v_ID_SERVICIO_MED, 1, M.PRECIO, M.PRECIO, p_ID_ATENCION_MEDICA
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
    SELECT v_ID_FACTURA, v_ID_SERVICIO_INSTR, 1, IM.COSTO_USO, IM.COSTO_USO, p_ID_ATENCION_MEDICA
    FROM INSTRUMENTO_USADO IU
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = p_ID_ATENCION_MEDICA;
    
    COMMIT;
    SELECT v_ID_FACTURA AS ID_FACTURA;
END //


DELIMITER ;
-- ============================================================
--  MODULO 6 | SPs de Vacunas, Alertas y Recordatorios
-- ============================================================

DELIMITER //

-- ============================================================
--  VACUNAS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_VACUNAS_DISPONIBLES()
BEGIN
    SELECT 'Rabia' AS NOMBRE, 'Proteccion contra el virus de la rabia' AS DESCRIPCION, 12 AS PERIODO_MESES UNION ALL
    SELECT 'Vacuna Sextuple Canina', 'Moquillo, hepatitis, leptospirosis, parvovirus, parainfluenza', 12 UNION ALL
    SELECT 'Vacuna Quintuple Canina', 'Moquillo, hepatitis, leptospirosis, parvovirus', 12 UNION ALL
    SELECT 'Vacuna Triple Felina', 'Rinotraqueitis, calicivirus y panleucopenia felina', 12 UNION ALL
    SELECT 'Vacuna Contra Leucemia Felina', 'Proteccion contra FeLV', 12 UNION ALL
    SELECT 'Vacuna Contra Bordetella', 'Prevencion de la tos de las perreras', 12 UNION ALL
    SELECT 'Vacuna Contra Parvovirus Canino', 'Proteccion especifica contra parvovirus', 12 UNION ALL
    SELECT 'Vacuna Contra Moquillo Canino', 'Proteccion especifica contra moquillo', 12 UNION ALL
    SELECT 'Vacuna Contra Leptospirosis', 'Proteccion contra serotipos de leptospira', 12 UNION ALL
    SELECT 'Vacuna Contra Coronavirus Canino', 'Previene la infeccion por coronavirus canino', 12 UNION ALL
    SELECT 'Vacuna Contra Panleucopenia Felina', 'Proteccion especifica contra panleucopenia', 12 UNION ALL
    SELECT 'Vacuna Contra Calicivirus Felino', 'Proteccion especifica contra calicivirus felino', 12 UNION ALL
    SELECT 'Vacuna Contra Rinotraqueitis Felina', 'Proteccion especifica contra rinotraqueitis felina', 12
    ORDER BY NOMBRE;
END //

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_VACUNA_APLICADA(
    IN p_ID_MASCOTA INT,
    IN p_NOMBRE VARCHAR(50),
    IN p_DESCRIPCION VARCHAR(255),
    IN p_PERIODO_MESES INT,
    IN p_FECHA_APLICACION DATE
)
BEGIN
    DECLARE v_FECHA_PROXIMA DATE;
    SET v_FECHA_PROXIMA = DATE_ADD(p_FECHA_APLICACION, INTERVAL p_PERIODO_MESES MONTH);
    
    INSERT INTO VACUNA_APLICADA
        (ID_MASCOTA, NOMBRE, DESCRIPCION, PERIODO_MESES, FECHA_APLICACION, FECHA_PROXIMA)
    VALUES
        (p_ID_MASCOTA, p_NOMBRE, p_DESCRIPCION, p_PERIODO_MESES, p_FECHA_APLICACION, v_FECHA_PROXIMA);
    SELECT LAST_INSERT_ID() AS ID_VACUNA;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VACUNAS_APLICADAS_POR_MASCOTA(
    IN p_ID_MASCOTA INT
)
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.DESCRIPCION, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = p_ID_MASCOTA
    ORDER BY VA.FECHA_APLICACION DESC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_HISTORIAL_VACUNACION(
    IN p_ID_MASCOTA INT
)
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.DESCRIPCION, VA.FECHA_APLICACION, VA.FECHA_PROXIMA,
           CASE
               WHEN VA.FECHA_PROXIMA < NOW() THEN 'VENCIDA'
               WHEN DATEDIFF(VA.FECHA_PROXIMA, NOW()) <= 30 THEN 'POR VENCER'
               ELSE 'VIGENTE'
           END AS ESTADO,
           DATEDIFF(VA.FECHA_PROXIMA, NOW()) AS DIAS_RESTANTES
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = p_ID_MASCOTA
    ORDER BY VA.FECHA_APLICACION DESC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VACUNAS_PROXIMAS_A_VENCER(
    IN p_DIAS_ANTICIPACION INT
)
BEGIN
    IF p_DIAS_ANTICIPACION IS NULL THEN
        SET p_DIAS_ANTICIPACION = 30;
    END IF;
    
    SELECT 
        VA.ID_VACUNA, 
        VA.NOMBRE,
        IFNULL(VA.DESCRIPCION, '') AS DESCRIPCION,
        IFNULL(VA.PERIODO_MESES, 0) AS PERIODO_MESES,
        VA.FECHA_APLICACION, 
        VA.FECHA_PROXIMA,
        VA.ID_MASCOTA,
        IFNULL(M.NOMBRE, 'Mascota no disponible') AS NOMBRE_MASCOTA
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    WHERE VA.FECHA_PROXIMA BETWEEN NOW() AND DATE_ADD(NOW(), INTERVAL p_DIAS_ANTICIPACION DAY)
    ORDER BY VA.FECHA_PROXIMA ASC;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_VACUNAS_PROXIMAS()
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE AS TIPO_VACUNA,
           M.NOMBRE AS MASCOTA,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS CLIENTE,
           CL.CEDULA AS CEDULA_CLIENTE,
           VA.FECHA_PROXIMA, VA.FECHA_APLICACION, VA.DESCRIPCION,
           CONCAT(VA.NOMBRE, ' - ', DATE_FORMAT(VA.FECHA_PROXIMA, '%d/%m/%Y'), ' - ', M.NOMBRE) AS DISPLAY_TEXT
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
    WHERE VA.FECHA_PROXIMA >= NOW()
    ORDER BY VA.FECHA_PROXIMA;
END //

CREATE OR REPLACE PROCEDURE SP_VERIFICAR_VACUNA_APLICADA(
    IN p_ID_MASCOTA INT,
    IN p_NOMBRE_VACUNA VARCHAR(50)
)
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = p_ID_MASCOTA AND VA.NOMBRE = p_NOMBRE_VACUNA
    ORDER BY VA.FECHA_APLICACION DESC
    LIMIT 1;
END //

CREATE OR REPLACE PROCEDURE SP_VERIFICAR_VACUNA_APLICADA_POR_MASCOTA(
    IN p_ID_MASCOTA INT,
    IN p_NOMBRE_VACUNA VARCHAR(50)
)
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = p_ID_MASCOTA AND VA.NOMBRE = p_NOMBRE_VACUNA
    ORDER BY VA.FECHA_APLICACION DESC
    LIMIT 1;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_VACUNA_APLICADA(
    IN p_ID_VACUNA INT,
    IN p_NOMBRE VARCHAR(50),
    IN p_DESCRIPCION VARCHAR(255),
    IN p_PERIODO_MESES INT,
    IN p_FECHA_APLICACION DATE,
    IN p_FECHA_PROXIMA DATE
)
BEGIN
    UPDATE VACUNA_APLICADA
    SET NOMBRE = p_NOMBRE, DESCRIPCION = p_DESCRIPCION, PERIODO_MESES = p_PERIODO_MESES,
        FECHA_APLICACION = p_FECHA_APLICACION, FECHA_PROXIMA = p_FECHA_PROXIMA
    WHERE ID_VACUNA = p_ID_VACUNA;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_DETALLES_VACUNA(
    IN p_ID_VACUNA INT
)
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE AS NOMBRE_VACUNA, VA.DESCRIPCION,
           VA.FECHA_APLICACION, VA.FECHA_PROXIMA,
           M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           CL.TELEFONO, CL.CORREO_ELECTRONICO
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
    WHERE VA.ID_VACUNA = p_ID_VACUNA;
END //

-- ============================================================
--  ALERTAS Y RECORDATORIOS
-- ============================================================

CREATE OR REPLACE PROCEDURE SP_OBTENER_CITAS_POR_RANGO_FECHAS(
    IN p_FECHA_INICIO DATE,
    IN p_FECHA_FIN DATE
)
BEGIN
    SELECT C.ID_CITA, C.ID_CLIENTE,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES,
           CASE C.ESTADO
               WHEN 'PENDIENTE' THEN 'Pendiente'
               WHEN 'REALIZADA' THEN 'Realizada'
               WHEN 'CANCELADA' THEN 'Cancelada'
               ELSE C.ESTADO
           END AS ESTADO_DESCRIPCION,
           CASE WHEN S.NOMBRE_SERVICIO LIKE '%Vacuna%' THEN 'Vacunacion' ELSE 'Consulta' END AS TIPO_CITA
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE DATE(C.FECHA_HORA) BETWEEN p_FECHA_INICIO AND p_FECHA_FIN
    ORDER BY C.FECHA_HORA;
END //

CREATE OR REPLACE PROCEDURE SP_VERIFICAR_RECORDATORIOS(
    IN p_ID_USUARIO INT
)
BEGIN
    DECLARE v_ID_CITA INT;
    DECLARE v_ID_VACUNA INT;
    DECLARE v_TIPO VARCHAR(20);
    DECLARE v_FECHA_EVENTO DATETIME;
    DECLARE v_MENSAJE_BASE VARCHAR(255);
    DECLARE v_MENSAJE_FINAL VARCHAR(500);
    DECLARE v_NOMBRE_CLIENTE VARCHAR(100);
    DECLARE v_NOMBRE_MASCOTA VARCHAR(50);
    DECLARE v_CEDULA_CLIENTE VARCHAR(10);
    DECLARE v_NOMBRE_SERVICIO VARCHAR(50);
    DECLARE v_VETERINARIOS VARCHAR(255);
    DECLARE v_DONE INT DEFAULT FALSE;
    
    DECLARE v_cursor CURSOR FOR
        SELECT 'CITA' AS TIPO, C.ID_CITA AS ID_EVENTO, C.FECHA_HORA, RC.ANTICIPACION, RC.MENSAJE,
               CONCAT(CL.NOMBRE, ' ', CL.APELLIDO), M.NOMBRE, CL.CEDULA, S.NOMBRE_SERVICIO
        FROM CITA C
        INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
        INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
        INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
        CROSS JOIN RECORDATORIO_CONFIG RC
        WHERE C.ESTADO = 'PENDIENTE' AND RC.TIPO_RECORDATORIO = 'CITA' AND RC.ACTIVO = 1
          AND NOT EXISTS (
              SELECT 1 FROM RECORDATORIO_ENVIADO RE
              WHERE RE.ID_CITA = C.ID_CITA AND RE.TIPO = 'CITA'
                AND DATE(RE.FECHA_ENVIO) = DATE(NOW())
          )
          AND (
              (RC.ANTICIPACION = '15_DIAS' AND DATEDIFF(C.FECHA_HORA, NOW()) = 15) OR
              (RC.ANTICIPACION = '7_DIAS' AND DATEDIFF(C.FECHA_HORA, NOW()) = 7) OR
              (RC.ANTICIPACION = '1_MES' AND PERIOD_DIFF(DATE_FORMAT(C.FECHA_HORA, '%Y%m'), DATE_FORMAT(NOW(), '%Y%m')) = 1) OR
              (RC.ANTICIPACION = '12_HORAS' AND TIMESTAMPDIFF(HOUR, NOW(), C.FECHA_HORA) = 12) OR
              (RC.ANTICIPACION = '10_HORAS' AND TIMESTAMPDIFF(HOUR, NOW(), C.FECHA_HORA) = 10) OR
              (RC.ANTICIPACION = '5_MINUTOS' AND TIMESTAMPDIFF(MINUTE, NOW(), C.FECHA_HORA) = 5) OR
              (RC.ANTICIPACION = '30_SEGUNDOS' AND TIMESTAMPDIFF(SECOND, NOW(), C.FECHA_HORA) = 30)
          )
        UNION ALL
        SELECT 'VACUNA', VA.ID_VACUNA, VA.FECHA_PROXIMA, RC.ANTICIPACION, RC.MENSAJE,
               CONCAT(CL.NOMBRE, ' ', CL.APELLIDO), M.NOMBRE, CL.CEDULA, VA.NOMBRE
        FROM VACUNA_APLICADA VA
        INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
        INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
        CROSS JOIN RECORDATORIO_CONFIG RC
        WHERE RC.TIPO_RECORDATORIO = 'VACUNA' AND RC.ACTIVO = 1
          AND NOT EXISTS (
              SELECT 1 FROM RECORDATORIO_ENVIADO RE
              WHERE RE.ID_VACUNA = VA.ID_VACUNA AND RE.TIPO = 'VACUNA'
                AND RE.MENSAJE LIKE CONCAT(RC.MENSAJE, '%')
                AND DATE(RE.FECHA_ENVIO) = DATE(NOW())
          )
          AND (
              (RC.ANTICIPACION = '15_DIAS' AND DATEDIFF(VA.FECHA_PROXIMA, NOW()) = 15) OR
              (RC.ANTICIPACION = '7_DIAS' AND DATEDIFF(VA.FECHA_PROXIMA, NOW()) = 7) OR
              (RC.ANTICIPACION = '1_MES' AND PERIOD_DIFF(DATE_FORMAT(VA.FECHA_PROXIMA, '%Y%m'), DATE_FORMAT(NOW(), '%Y%m')) = 1) OR
              (RC.ANTICIPACION = '12_HORAS' AND TIMESTAMPDIFF(HOUR, NOW(), VA.FECHA_PROXIMA) = 12) OR
              (RC.ANTICIPACION = '10_HORAS' AND TIMESTAMPDIFF(HOUR, NOW(), VA.FECHA_PROXIMA) = 10) OR
              (RC.ANTICIPACION = '5_MINUTOS' AND TIMESTAMPDIFF(MINUTE, NOW(), VA.FECHA_PROXIMA) = 5) OR
              (RC.ANTICIPACION = '30_SEGUNDOS' AND TIMESTAMPDIFF(SECOND, NOW(), VA.FECHA_PROXIMA) = 30)
          );
    
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_DONE = TRUE;
    
    OPEN v_cursor;
    
    read_loop: LOOP
        FETCH v_cursor INTO v_TIPO, v_ID_CITA, v_FECHA_EVENTO, v_MENSAJE_BASE, v_MENSAJE_FINAL,
                           v_NOMBRE_CLIENTE, v_NOMBRE_MASCOTA, v_CEDULA_CLIENTE, v_NOMBRE_SERVICIO;
        IF v_DONE THEN
            LEAVE read_loop;
        END IF;
        
        IF v_TIPO = 'CITA' THEN
            SELECT CONCAT(V.NOMBRE, ' ', V.APELLIDO) INTO v_VETERINARIOS
            FROM CITA C
            INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
            WHERE C.ID_CITA = v_ID_CITA;
            
            SET v_MENSAJE_FINAL = CONCAT(v_MENSAJE_BASE, '. Detalles: ',
                DATE_FORMAT(v_FECHA_EVENTO, '%d/%m/%Y %H:%i'),
                ' - Servicio: ', v_NOMBRE_SERVICIO,
                '. Mascota: ', v_NOMBRE_MASCOTA,
                '. Veterinario: ', IFNULL(v_VETERINARIOS, 'Por asignar'));
        ELSE
            SET v_MENSAJE_FINAL = CONCAT(v_MENSAJE_BASE, '. Detalles: ',
                'Vacuna: ', v_NOMBRE_SERVICIO,
                ' - Proxima aplicacion: ', DATE_FORMAT(v_FECHA_EVENTO, '%d/%m/%Y'),
                ' - Mascota: ', v_NOMBRE_MASCOTA,
                ' - Cliente: ', v_NOMBRE_CLIENTE, ' (', v_CEDULA_CLIENTE, ')');
        END IF;
        
        INSERT INTO RECORDATORIO_ENVIADO (ID_USUARIO, ID_CITA, ID_VACUNA, TIPO, MENSAJE)
        VALUES (p_ID_USUARIO, IF(v_TIPO = 'CITA', v_ID_CITA, NULL), IF(v_TIPO = 'VACUNA', v_ID_CITA, NULL), v_TIPO, v_MENSAJE_FINAL);
    END LOOP;
    
    CLOSE v_cursor;
    
    IF p_ID_USUARIO IS NOT NULL THEN
        SELECT ID_RECORDATORIO, MENSAJE, FECHA_ENVIO, LEIDO
        FROM RECORDATORIO_ENVIADO
        WHERE ID_USUARIO = p_ID_USUARIO AND LEIDO = 0
        ORDER BY FECHA_ENVIO DESC;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_RECORDATORIOS_PENDIENTES(
    IN p_ID_USUARIO INT
)
BEGIN
    SELECT ID_RECORDATORIO, ID_USUARIO, ID_CITA, ID_VACUNA,
           TIPO, MENSAJE, FECHA_ENVIO, LEIDO
    FROM RECORDATORIO_ENVIADO
    WHERE ID_USUARIO = p_ID_USUARIO AND LEIDO = 0
    ORDER BY FECHA_ENVIO DESC;
END //

CREATE OR REPLACE PROCEDURE SP_MARCAR_RECORDATORIO_LEIDO(
    IN p_ID_RECORDATORIO INT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END;
    
    START TRANSACTION;
    UPDATE RECORDATORIO_ENVIADO
    SET LEIDO = 1, CONTADOR_MOSTRADO = 0
    WHERE ID_RECORDATORIO = p_ID_RECORDATORIO;
    
    IF ROW_COUNT() > 0 THEN
        COMMIT;
        SELECT 1 AS RESULTADO;
    ELSE
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END IF;
END //

CREATE OR REPLACE PROCEDURE SP_INCREMENTAR_CONTADOR_RECORDATORIO(
    IN p_ID_RECORDATORIO INT
)
BEGIN
    UPDATE RECORDATORIO_ENVIADO
    SET CONTADOR_MOSTRADO = CONTADOR_MOSTRADO + 1
    WHERE ID_RECORDATORIO = p_ID_RECORDATORIO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CONTADOR_RECORDATORIO(
    IN p_ID_RECORDATORIO INT
)
BEGIN
    SELECT CONTADOR_MOSTRADO FROM RECORDATORIO_ENVIADO WHERE ID_RECORDATORIO = p_ID_RECORDATORIO;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_TODOS_RECORDATORIOS(
    IN p_FECHA_INICIO DATETIME,
    IN p_FECHA_FIN DATETIME
)
BEGIN
    SELECT ID_RECORDATORIO, ID_USUARIO, ID_CITA, ID_VACUNA,
           TIPO, MENSAJE, FECHA_ENVIO, LEIDO, CONTADOR_MOSTRADO
    FROM RECORDATORIO_ENVIADO
    WHERE FECHA_ENVIO BETWEEN p_FECHA_INICIO AND p_FECHA_FIN
    ORDER BY FECHA_ENVIO DESC;
END //

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_RECORDATORIO(
    IN p_CORREO_USUARIO VARCHAR(100),
    IN p_ID_CITA INT,
    IN p_ID_VACUNA INT,
    IN p_TIPO VARCHAR(20),
    IN p_MENSAJE VARCHAR(500),
    IN p_ANTICIPACION VARCHAR(20)
)
BEGIN
    DECLARE v_ID_USUARIO INT DEFAULT NULL;
    DECLARE v_FECHA_EVENTO DATETIME;
    
    IF p_CORREO_USUARIO IS NOT NULL THEN
        SELECT ID_USUARIO INTO v_ID_USUARIO FROM USUARIO WHERE CORREO_ELECTRONICO = p_CORREO_USUARIO;
    END IF;
    
    IF p_TIPO = 'CITA' THEN
        SELECT FECHA_HORA INTO v_FECHA_EVENTO FROM CITA WHERE ID_CITA = p_ID_CITA;
    ELSE
        SELECT FECHA_PROXIMA INTO v_FECHA_EVENTO FROM VACUNA_APLICADA WHERE ID_VACUNA = p_ID_VACUNA;
    END IF;
    
    INSERT INTO RECORDATORIO_ENVIADO (ID_USUARIO, ID_CITA, ID_VACUNA, TIPO, MENSAJE, FECHA_ENVIO)
    VALUES (
        v_ID_USUARIO, p_ID_CITA, p_ID_VACUNA, p_TIPO, p_MENSAJE,
        CASE
            WHEN p_ANTICIPACION = '15_DIAS' THEN DATE_SUB(v_FECHA_EVENTO, INTERVAL 15 DAY)
            WHEN p_ANTICIPACION = '7_DIAS' THEN DATE_SUB(v_FECHA_EVENTO, INTERVAL 7 DAY)
            WHEN p_ANTICIPACION = '1_MES' THEN DATE_SUB(v_FECHA_EVENTO, INTERVAL 1 MONTH)
            ELSE NOW()
        END
    );
    SELECT LAST_INSERT_ID() AS ID_RECORDATORIO;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_RECORDATORIO(
    IN p_ID_RECORDATORIO INT,
    IN p_MENSAJE VARCHAR(500),
    IN p_LEIDO BOOLEAN
)
BEGIN
    UPDATE RECORDATORIO_ENVIADO
    SET MENSAJE = p_MENSAJE, LEIDO = IFNULL(p_LEIDO, LEIDO)
    WHERE ID_RECORDATORIO = p_ID_RECORDATORIO;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_RECORDATORIO(
    IN p_ID_RECORDATORIO INT
)
BEGIN
    DELETE FROM RECORDATORIO_ENVIADO WHERE ID_RECORDATORIO = p_ID_RECORDATORIO;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_CONFIG_RECORDATORIOS()
BEGIN
    SELECT ID_CONFIG, TIPO_RECORDATORIO, ANTICIPACION, MENSAJE, ACTIVO
    FROM RECORDATORIO_CONFIG
    ORDER BY TIPO_RECORDATORIO, ANTICIPACION;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_CONFIG_RECORDATORIO(
    IN p_ID_CONFIG INT,
    IN p_MENSAJE VARCHAR(255),
    IN p_ACTIVO BOOLEAN
)
BEGIN
    UPDATE RECORDATORIO_CONFIG
    SET MENSAJE = p_MENSAJE, ACTIVO = p_ACTIVO
    WHERE ID_CONFIG = p_ID_CONFIG;
    SELECT ROW_COUNT() AS FILAS_AFECTADAS;
END //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_CONFIG_RECORDATORIO(
    IN p_TIPO_RECORDATORIO VARCHAR(50),
    IN p_ANTICIPACION VARCHAR(20),
    IN p_MENSAJE VARCHAR(255),
    IN p_ACTIVO BOOLEAN
)
BEGIN
    IF EXISTS (SELECT 1 FROM RECORDATORIO_CONFIG 
               WHERE TIPO_RECORDATORIO = p_TIPO_RECORDATORIO 
               AND ANTICIPACION = p_ANTICIPACION) THEN
        SELECT -1 AS ID_CONFIG;
    ELSE
        INSERT INTO RECORDATORIO_CONFIG (TIPO_RECORDATORIO, ANTICIPACION, MENSAJE, ACTIVO)
        VALUES (p_TIPO_RECORDATORIO, p_ANTICIPACION, p_MENSAJE, p_ACTIVO);
        SELECT LAST_INSERT_ID() AS ID_CONFIG;
    END IF;
END //

DELIMITER ;
-- ============================================================
--  MODULO 7 | SPs de Historial Medico
-- ============================================================

DELIMITER //

CREATE OR REPLACE PROCEDURE SP_REGISTRAR_HISTORIAL(
    IN p_ID_MASCOTA INT,
    IN p_ID_CITA INT,
    IN p_ID_ATENCION_MEDICA INT
)
BEGIN
    INSERT INTO HISTORIAL_MEDICO (ID_MASCOTA, ID_CITA, FECHA, ID_ATENCION_MEDICA)
    VALUES (p_ID_MASCOTA, p_ID_CITA, NOW(), p_ID_ATENCION_MEDICA);
    SELECT LAST_INSERT_ID() AS ID_HISTORIAL;
END //

CREATE OR REPLACE PROCEDURE SP_OBTENER_HISTORIAL_MEDICO_POR_MASCOTA(
    IN p_ID_MASCOTA INT
)
BEGIN
    SELECT
        HM.ID_HISTORIAL,  
        AM.ID_ATENCION_MEDICA, 
        AM.FECHA, 
        C.ID_CITA, 
        S.NOMBRE_SERVICIO,
        CONCAT(V.NOMBRE, ' ', V.APELLIDO) AS VETERINARIO,
        AM.DIAGNOSTICO, 
        AM.TRATAMIENTO,
        AM.OBSERVACIONES AS OBSERVACIONES_ATENCION,
        (
            SELECT GROUP_CONCAT(IM.NOMBRE SEPARATOR ', ')
            FROM INSTRUMENTO_USADO IU
            JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
            WHERE IU.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
        ) AS INSTRUMENTOS_USADOS,
        (
            SELECT GROUP_CONCAT(
                CONCAT(MED.NOMBRE, ' (', MR.DOSIS, ', ', MR.FRECUENCIA, ', ', MR.DURACION, ')')
                SEPARATOR ' | '
            )
            FROM MEDICAMENTO_RECETADO MR
            JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
            WHERE MR.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
        ) AS MEDICAMENTOS_RECETADOS
    FROM HISTORIAL_MEDICO HM
    INNER JOIN ATENCION_MEDICA AM ON HM.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    LEFT JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    LEFT JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE HM.ID_MASCOTA = p_ID_MASCOTA
    ORDER BY AM.FECHA DESC;
END //

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_FICHA_MEDICA(
    IN p_ID_MASCOTA INT,
    IN p_ALERGIAS VARCHAR(255),
    IN p_ENFERMEDADES_CRONICAS VARCHAR(255),
    IN p_OBSERVACIONES TEXT
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        IF NOT @@autocommit THEN
            ROLLBACK;
        END IF;
        RESIGNAL;
    END;
    
    START TRANSACTION;
    
    IF NOT EXISTS (SELECT 1 FROM MASCOTA WHERE ID_MASCOTA = p_ID_MASCOTA) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La mascota especificada no existe';
        ROLLBACK;
    ELSE
        IF EXISTS (SELECT 1 FROM FICHA_MEDICA WHERE ID_MASCOTA = p_ID_MASCOTA) THEN
            UPDATE FICHA_MEDICA
            SET ALERGIAS = IFNULL(p_ALERGIAS, ALERGIAS),
                ENFERMEDADES_CRONICAS = IFNULL(p_ENFERMEDADES_CRONICAS, ENFERMEDADES_CRONICAS),
                OBSERVACIONES = IFNULL(p_OBSERVACIONES, OBSERVACIONES),
                ULTIMA_ACTUALIZACION = NOW()
            WHERE ID_MASCOTA = p_ID_MASCOTA;
        ELSE
            INSERT INTO FICHA_MEDICA (ID_MASCOTA, ALERGIAS, ENFERMEDADES_CRONICAS, OBSERVACIONES)
            VALUES (p_ID_MASCOTA, p_ALERGIAS, p_ENFERMEDADES_CRONICAS, p_OBSERVACIONES);
        END IF;
    END IF;
    
    COMMIT;
END //

DELIMITER ;

-- ============================================================
--  TRIGGER PARA INSERTAR HISTORIAL MEDICO
-- ============================================================

DELIMITER //

CREATE TRIGGER TR_INSERTAR_HISTORIAL_MEDICO
AFTER INSERT ON ATENCION_MEDICA
FOR EACH ROW
BEGIN
    INSERT INTO HISTORIAL_MEDICO (ID_MASCOTA, ID_CITA, ID_ATENCION_MEDICA, FECHA)
    SELECT 
        C.ID_MASCOTA,
        NEW.ID_CITA,
        NEW.ID_ATENCION_MEDICA,
        NOW()
    FROM CITA C
    WHERE C.ID_CITA = NEW.ID_CITA;
END //

DELIMITER ;
-- ============================================================
--  MODULO 8 | Datos Iniciales (Seed) - MySQL
-- ============================================================

-- ============================================================
--  USUARIOS
INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL) VALUES
('cjimenez@hotmail.com', '123456', 'VETERINARIO'),
('evera@hotmail.com', '123456', 'VETERINARIO'),
('lchavez@hotmail.com', '123456', 'VETERINARIO'),
('portega@hotmail.com', '123456', 'VETERINARIO'),
('amorales@hotmail.com', '123456', 'VETERINARIO'),
('lmejia@hotmail.com', '123456', 'VETERINARIO'),
('jvega@hotmail.com', '123456', 'VETERINARIO'),
('sgonzalez@hotmail.com', '123456', 'VETERINARIO'),
('mcastro@hotmail.com', '123456', 'VETERINARIO'),
('dperez@hotmail.com', '123456', 'VETERINARIO');

INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL) VALUES
('admin@vet.com', 'admin123', 'ADMINISTRADOR'),
('maria@vet.com', 'maria123', 'RECEPCIONISTA');
-- ============================================================
--  ESPECIALIDADES VETERINARIAS
-- ============================================================
INSERT INTO ESPECIALIDAD_VETERINARIA (NOMBRE_ESPECIALIDAD) VALUES
('Medicina General'),
('Cirugia Veterinaria'),
('Dermatologia'),
('Cardiologia'),
('Odontologia'),
('Oftalmologia'),
('Neurologia'),
('Urgencias'),
('Nutricion'),
('Vacunacion y Desparasitacion');

-- ============================================================
--  VETERINARIOS
-- ============================================================
INSERT INTO VETERINARIO
    (CEDULA, NOMBRE, APELLIDO, TELEFONO, PAGO_MENSUAL, DIRECCION, CORREO_ELECTRONICO, ID_ESPECIALIDAD)
VALUES
    ('1010101010','Carlos',   'Jimenez',  '0991112233',  900.00,'Quito Norte',       'cjimenez@hotmail.com',  1),
    ('2020202020','Elena',    'Vera',     '0992223344', 1300.00,'Quito Sur',          'evera@hotmail.com',     2),
    ('3030303030','Luis',     'Chavez',   '0993334455', 1100.00,'Guayaquil Centro',   'lchavez@hotmail.com',   3),
    ('4040404040','Patricia', 'Ortega',   '0994445566',  950.00,'Cuenca Norte',       'portega@hotmail.com',   4),
    ('5050505050','Andres',   'Morales',  '0995556677',  970.00,'Quito',              'amorales@hotmail.com',  5),
    ('6060606060','Lorena',   'Mejia',    '0996667788',  920.00,'Loja',               'lmejia@hotmail.com',    6),
    ('7070707070','Jorge',    'Vega',     '0997778899', 1000.00,'Riobamba',           'jvega@hotmail.com',     7),
    ('8080808080','Silvia',   'Gonzalez', '0998889900', 1400.00,'Ambato',             'sgonzalez@hotmail.com', 8),
    ('9090909090','Mario',    'Castro',   '0999990011',  880.00,'Ibarra',             'mcastro@hotmail.com',   9),
    ('1111111111','Daniela',  'Perez',    '0990001122',  870.00,'Manta',              'dperez@hotmail.com',   10);
INSERT INTO RECEPCIONISTA (CEDULA, NOMBRE, APELLIDO, TELEFONO, CORREO_ELECTRONICO)
VALUES 
('1734511890', 'María', 'Rizzo', '0993451189', 'maria@vet.com');
-- ============================================================
--  CLIENTE DE PRUEBA
-- ============================================================
INSERT INTO CLIENTE (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
VALUES ('1234567890','Ana','Ramirez','0987654321','Av. Siempre Viva 123','ana.ramirez@email.com');

-- ============================================================
--  MEDICAMENTOS
-- ============================================================
INSERT INTO MEDICAMENTO (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES
('Amoxicilina',       'Antibiotico de amplio espectro',          8.50, 100),
('Ivermectina',       'Antiparasitario interno y externo',       5.75, 200),
('Carprofeno',        'Analgesico y antiinflamatorio',          12.00,  75),
('Enrofloxacina',     'Antibacteriano veterinario',             10.00,  90),
('Prednisolona',      'Antiinflamatorio corticosteroide',        6.50,  80),
('Metronidazol',      'Antiparasitario y antibacteriano',        7.20, 120),
('Meloxicam',         'Analgesico para dolor e inflamacion',     9.80, 100),
('Ciprofloxacina',    'Antibiotico bactericida',                 6.90, 150),
('Suero Ringer Lactato','Solucion electrolitica',               4.00,  50),
('Ketamina',          'Anestesico general para cirugias',       18.00,  60);

-- ============================================================
--  INSTRUMENTOS MEDICOS
-- ============================================================
INSERT INTO INSTRUMENTO_MEDICO (NOMBRE, DESCRIPCION, COSTO_USO) VALUES
('Estetoscopio',         'Para auscultacion cardiaca y pulmonar',  0.50),
('Termometro Digital',   'Medicion de temperatura corporal',       0.30),
('Bisturi',              'Corte durante cirugias o procedimientos', 1.00),
('Pinzas Hemostaticas',  'Detencion de sangrado',                   0.80),
('Jeringuilla',          'Aplicacion de medicamentos o vacunas',    0.20),
('Tijeras Quirurgicas',  'Corte de tejidos o vendas',               0.40),
('Lampara de Exploracion','Iluminacion durante examenes',           0.60),
('Otoscopio',            'Exploracion de canal auditivo',           0.70),
('Balanza Digital',      'Medicion de peso del animal',             0.25),
('Microscopio',          'Analisis de muestras biologicas',         2.00);

-- ============================================================
--  SERVICIOS
-- ============================================================
INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO) VALUES
('Consulta General de Salud',    'Revision general de salud',          25.00, 30, 1),
('Cirugia de Esterilizacion',    'Esterilizacion quirurgica',         100.00, 90, 1),
('VACUNA',                       'Aplicacion de vacunas',              10.00, 10, 1),
('Tratamiento Pulgas/Garrapatas','Desparasitacion externa',            15.00, 20, 1),
('Consulta Dolor o Lesion',      'Evaluacion de dolor',                30.00, 30, 1),
('Desparasitacion Interna',      'Eliminar parasitos intestinales',    12.00, 15, 1),
('Limpieza Dental',              'Limpieza y revision dental',         40.00, 45, 1),
('Consulta Dermatologica',       'Enfermedades de la piel',            35.00, 30, 1),
('Control Nutricional',          'Asesoramiento alimenticio',          20.00, 20, 1),
('Emergencia Veterinaria',       'Atencion fuera de horario',          50.00, 60, 1);

-- ============================================================
--  ASIGNAR SERVICIOS A VETERINARIOS
-- ============================================================
INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO) VALUES
(1, 1), (2, 2), (8, 3), (4, 4), (7, 5),
(6, 6), (5, 7), (10,8), (9, 9), (3,10);

-- ============================================================
--  CONFIGURACION DE RECORDATORIOS
-- ============================================================
INSERT INTO RECORDATORIO_CONFIG (TIPO_RECORDATORIO, ANTICIPACION, MENSAJE) VALUES
('CITA',   '15_DIAS',     'Tiene una cita pendiente dentro de 15 dias'),
('CITA',   '7_DIAS',      'Tiene una cita pendiente dentro de 7 dias'),
('CITA',   '1_MES',       'Tiene una cita pendiente dentro de 1 mes'),
('CITA',   '12_HORAS',    'Tiene una cita pendiente dentro de 12 horas'),
('CITA',   '10_HORAS',    'Tiene una cita pendiente dentro de 10 horas'),
('CITA',   '5_MINUTOS',   'Tiene una cita pendiente dentro de 5 minutos'),
('CITA',   '30_SEGUNDOS', 'Tiene una cita pendiente dentro de 30 segundos'),
('VACUNA', '15_DIAS',     'Vacunacion proxima dentro de 15 dias'),
('VACUNA', '7_DIAS',      'Vacunacion proxima dentro de 7 dias'),
('VACUNA', '1_MES',       'Vacunacion proxima dentro de 1 mes'),
('VACUNA', '12_HORAS',    'Vacunacion proxima dentro de 12 horas'),
('VACUNA', '10_HORAS',    'Vacunacion proxima dentro de 10 horas'),
('VACUNA', '5_MINUTOS',   'Vacunacion proxima dentro de 5 minutos'),
('VACUNA', '30_SEGUNDOS', 'Vacunacion proxima dentro de 30 segundos');

-- ============================================================
--  DATOS DE EJEMPLO: MASCOTA, CITA Y ATENCION
-- ============================================================

DELIMITER //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_DATOS_EJEMPLO()
BEGIN
    DECLARE v_ID_CLIENTE INT;
    DECLARE v_ID_MASCOTA INT;
    DECLARE v_ID_CITA INT;
    DECLARE v_ID_ATENCION INT;
    DECLARE v_ID_METODO_PAGO INT;
    DECLARE v_ID_FACTURA INT;
    
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SELECT 'Error en datos de ejemplo' AS ERROR;
    END;
    
    START TRANSACTION;
    
    SELECT ID_CLIENTE INTO v_ID_CLIENTE FROM CLIENTE WHERE CEDULA = '1234567890';
    
    -- 1. Mascota
    INSERT INTO MASCOTA (ID_CLIENTE, NOMBRE, ESPECIE, RAZA, SEXO, FECHA_NACIMIENTO, PESO, COLOR)
    VALUES (v_ID_CLIENTE, 'Max', 'Perro', 'Labrador', 'M', '2020-09-22', 25.5, 'Marron');
    SET v_ID_MASCOTA = LAST_INSERT_ID();
    
    -- 2. Cita (con veterinario 10 - Daniela Perez para vacunacion - Servicio 3)
    INSERT INTO CITA (ID_CLIENTE, ID_MASCOTA, ID_SERVICIO, ID_VETERINARIO, FECHA_HORA, OBSERVACIONES, ESTADO)
    VALUES (v_ID_CLIENTE, v_ID_MASCOTA, 3, 10, NOW(), 'Vacunacion anual', 'PENDIENTE');
    SET v_ID_CITA = LAST_INSERT_ID();
    
    -- 3. Vacuna
    CALL SP_REGISTRAR_VACUNA_APLICADA(v_ID_MASCOTA, 'Rabia', 'Proteccion contra el virus de la rabia', 12, '2023-09-20');
    
    -- 4. Atencion medica
    INSERT INTO ATENCION_MEDICA (ID_CITA, FECHA, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES)
    VALUES (v_ID_CITA, NOW(), 'Vacunacion anual', 'Vacuna antirrabica aplicada', 'Mascota en buen estado');
    SET v_ID_ATENCION = LAST_INSERT_ID();
    
    -- 5. Facturacion
    INSERT INTO METODO_PAGO (METODO, VALOR_TOTAL) VALUES ('EFECTIVO', 11.20);
    SET v_ID_METODO_PAGO = LAST_INSERT_ID();
    
    INSERT INTO FACTURA (ID_CLIENTE, SUBTOTAL, IVA, TOTAL, ESTADO, ID_METODO_PAGO)
    VALUES (v_ID_CLIENTE, 10.00, 1.20, 11.20, 'PAGADA', v_ID_METODO_PAGO);
    SET v_ID_FACTURA = LAST_INSERT_ID();
    
    -- 6. Detalle Factura
    INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, TOTAL, ID_ATENCION_MEDICA)
    VALUES (v_ID_FACTURA, 3, 1, 10.00, 0.00, 10.00, v_ID_ATENCION);
    
    COMMIT;
    
    SELECT 'Datos de ejemplo insertados correctamente' AS MENSAJE;
END //

DELIMITER ;

CALL SP_INSERTAR_DATOS_EJEMPLO();

-- ============================================================
--  INSERTAR VACUNA CON FECHA PROXIMA A VENCER
-- ============================================================

DELIMITER //

CREATE OR REPLACE PROCEDURE SP_INSERTAR_VACUNA_PROXIMA()
BEGIN
    DECLARE v_ID_MASCOTA INT;
    
    SELECT ID_MASCOTA INTO v_ID_MASCOTA FROM MASCOTA WHERE NOMBRE = 'Max';
    
    IF v_ID_MASCOTA IS NULL THEN
        SELECT MIN(ID_MASCOTA) INTO v_ID_MASCOTA FROM MASCOTA;
    END IF;
    
    INSERT INTO VACUNA_APLICADA (ID_MASCOTA, NOMBRE, DESCRIPCION, PERIODO_MESES, FECHA_APLICACION, FECHA_PROXIMA)
    VALUES (
        v_ID_MASCOTA,
        'Vacuna Sextuple Canina',
        'Proteccion contra moquillo, hepatitis, leptospirosis, parvovirus, parainfluenza',
        12,
        DATE_SUB(NOW(), INTERVAL 350 DAY),
        DATE_ADD(NOW(), INTERVAL 15 DAY)
    );
    
    SELECT 'Vacuna insertada correctamente' AS MENSAJE;
END //

DELIMITER ;

CALL SP_INSERTAR_VACUNA_PROXIMA();

-- ============================================================
--  CREAR USUARIO DE BASE DE DATOS Y ASIGNAR PERMISOS
-- ============================================================
-- MySQL: Crear usuario y asignar permisos
CREATE USER IF NOT EXISTS 'veterinaria_user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON db_veterinaria.* TO 'veterinaria_user'@'localhost';
FLUSH PRIVILEGES;

-- ============================================================
--  RESUMEN FINAL
-- ============================================================
SELECT 'Resumen de objetos creados:' AS MENSAJE;
SELECT 
    CASE 
        WHEN TABLE_TYPE = 'BASE TABLE' THEN 'TABLE'
        WHEN TABLE_TYPE = 'VIEW' THEN 'VIEW'
    END AS TIPO,
    COUNT(*) AS CANTIDAD
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = DATABASE()
GROUP BY TABLE_TYPE;

SELECT 'PROCEDURE' AS TIPO, COUNT(*) AS CANTIDAD
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_SCHEMA = DATABASE() AND ROUTINE_TYPE = 'PROCEDURE';

SELECT 'TRIGGER' AS TIPO, COUNT(*) AS CANTIDAD
FROM INFORMATION_SCHEMA.TRIGGERS 
WHERE TRIGGER_SCHEMA = DATABASE();