package com.mycompany.veterinaria.grupo4.view.swing.table;

import com.mycompany.veterinaria.grupo4.view.swing.Button;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Raven
 */
public class Action extends javax.swing.JPanel {

    /**
     * Creates new form Action
     */
    public Action() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnView = new com.mycompany.veterinaria.grupo4.view.swing.Button();
        btnEdit = new com.mycompany.veterinaria.grupo4.view.swing.Button();
        btnDelete = new com.mycompany.veterinaria.grupo4.view.swing.Button();

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        btnView.setPreferredSize(new java.awt.Dimension(28, 28));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(28, 28));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnDelete.setPreferredSize(new java.awt.Dimension(28, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public Button getBtnDelete() {
        return btnDelete;
    }

    public Button getBtnEdit() {
        return btnEdit;
    }

    public Button getBtnView() {
        return btnView;
    }
    
    public void setModelAction(ModelAction model) {
        btnEdit.addActionListener(e -> {
            if (model.getOnEdit() != null) model.getOnEdit().run();
        });
        btnView.addActionListener(e -> {
            if (model.getOnView() != null) model.getOnView().run();
        });
        btnDelete.addActionListener(e -> {
            if (model.getOnDelete() != null) model.getOnDelete().run();
        });
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        grphcs.setColor(new Color(230, 230, 230));
        grphcs.drawLine(0, getHeight() - 1, getWidth(), getHeight() - 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.veterinaria.grupo4.view.swing.Button btnDelete;
    private com.mycompany.veterinaria.grupo4.view.swing.Button btnEdit;
    private com.mycompany.veterinaria.grupo4.view.swing.Button btnView;
    // End of variables declaration//GEN-END:variables
}
