
package com.mycompany.veterinaria.grupo4.view.swing.table;

import com.mycompany.veterinaria.grupo4.model.entity.EstadoCita;

/**
 *
 * @author juan
 */
public class CellCitaEstado extends javax.swing.JPanel {

    /**
     * Creates new form CellStatus
     * @param type
     */
    public CellCitaEstado(EstadoCita type) {
        initComponents();
        status.setEstadoCita(type);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new com.mycompany.veterinaria.grupo4.view.swing.table.TableCitaEstado();

        setBackground(new java.awt.Color(255, 255, 255));

        status.setText("tableStatus1");
        status.setMaximumSize(new java.awt.Dimension(90, 28));
        status.setPreferredSize(new java.awt.Dimension(90, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.veterinaria.grupo4.view.swing.table.TableCitaEstado status;
    // End of variables declaration//GEN-END:variables
}
