package com.mycompany.veterinaria.grupo4.view.swing.table;

import com.formdev.flatlaf.FlatClientProperties;
import com.mycompany.veterinaria.grupo4.view.swing.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Raven
 */
public class CellAction extends javax.swing.JPanel {

    /** Configuración de ícono y tooltip por tipo de acción. */
    private record BtnConfig(String icono, String tooltip) {}
 
    private static final Map<ModelAction.Tipo, BtnConfig> CONFIG = Map.of(
        ModelAction.Tipo.EDITAR,    new BtnConfig("/icon/edit.png",       "Editar"),
        ModelAction.Tipo.VER,       new BtnConfig("/icon/eye.png",        "Ver detalle"),
        ModelAction.Tipo.ELIMINAR,  new BtnConfig("/icon/delete.png",     "Eliminar"),
        ModelAction.Tipo.ATENCION,  new BtnConfig("/icon/medical-bag.png",    "Iniciar atención"),
        ModelAction.Tipo.HISTORIAL, new BtnConfig("/icon/pet-report.png", "Ver historial")
    );
 
    public CellAction() {
        setLayout(new FlowLayout(FlowLayout.LEFT, 4, 4));
        setOpaque(true);
        putClientProperty(FlatClientProperties.STYLE, "background:$Panel.background");
        setBorder(new EmptyBorder(0, 4, 0, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
   
    
    /**
     * Construye los botones según el modelo dado.
     * Los botones aparecen en el orden en que se agregaron al {@link ModelAction}.
     *
     * @param model modelo con las acciones a renderizar
     */
    public void setModelAction(ModelAction model) {
        model.getAcciones().forEach((tipo, accion) -> {
            BtnConfig cfg = CONFIG.get(tipo);
            if (cfg == null) return;
 
            Button btn = new Button();
            btn.setPreferredSize(new Dimension(28, 28));
            btn.setIcon(new ImageIcon(getClass().getResource(cfg.icono())));
            btn.setToolTipText(cfg.tooltip());
            btn.addActionListener(e -> accion.run());
            add(btn);
        });
 
        validate();
        repaint();
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        grphcs.setColor(new Color(230, 230, 230));
        grphcs.drawLine(0, getHeight() - 1, getWidth(), getHeight() - 1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
