/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.veterinaria.grupo4.view.auth;

import javax.swing.ImageIcon;

/**
 *
 * @author juan
 */
public class FrmPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public FrmPrincipal() {
        initComponents();
        
        this.setContentPane(bgPrincipal);
        setSize(1000,600);
        setLocationRelativeTo(null);
        setResizable(false);
    
        // Actualizamos la ventana
        this.revalidate();
        this.repaint();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrincipal = new com.mycompany.veterinaria.grupo4.view.auth.Background();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgPrincipal.setImage(new javax.swing.ImageIcon(getClass().getResource("/image/bg_veterinaria.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Background getBgPrincipal() {
        return bgPrincipal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.veterinaria.grupo4.view.auth.Background bgPrincipal;
    // End of variables declaration//GEN-END:variables
}
