package com.mycompany.veterinaria.grupo4.view.auth;

import com.mycompany.veterinaria.grupo4.view.swing.PanelCover;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.Timer;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author juan
 */
public class PnlBgLogin extends javax.swing.JPanel {
    private final DecimalFormat df = new DecimalFormat("##0.###", DecimalFormatSymbols.getInstance(Locale.US));
    private MigLayout layout;
    private PanelCover cover;
    private boolean isLogin = true;
    private final double addSize = 30;
    private final double coverSize = 40;
    private final double loginSize = 60;
    private Timer animator;
    private int frameCount = 0;
    private final int totalFrames = 60;
    /**
     * Creates new form PnlBgLogin
     */
    public PnlBgLogin() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new com.mycompany.veterinaria.grupo4.view.auth.PnlLogin();

        setMaximumSize(new java.awt.Dimension(625, 400));
        setPreferredSize(new java.awt.Dimension(625, 400));

        pnlLogin.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 250, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        layout = new MigLayout("fill, insets 0");
        cover = new PanelCover();

        // Timer reemplaza a Animator + TimingTargetAdapter
        animator = new Timer(10, (ActionEvent e) -> {
            frameCount++;
            float rawFraction = (float) frameCount / totalFrames;
            if (rawFraction > 1f) rawFraction = 1f;

            float fraction = easeInOut(rawFraction);

            // Calculamos las posiciones en PÍXELES exactos
            int coverX;
            int loginX;
            if (isLogin) {
                // Animamos: Cover hacia la Derecha, Login hacia la Izquierda
                coverX = (int)(fraction * 375);
                loginX = (int)(250 -(fraction * 250));
            } else {
                // Animamos: Cover hacia la Izquierda, Login hacia la Derecha
                coverX = (int) (375 - (fraction * 375));
                loginX = (int) (fraction * 250);
            }
            
            // 2. Animación del texto dentro del cover (Esto lo dejas igual)
            if (isLogin) {
                if (rawFraction <= 0.5f) {
                    cover.registerRight(fraction * 100);
                } else {
                    cover.loginRight((1f - fraction) * 100);
                }
            } else {
                if (rawFraction <= 0.5f) {
                    cover.registerLeft(fraction * 100);
                } else {
                    cover.loginLeft((1f - fraction) * 100);
                }
            }

            // Cambiar panel login/register a mitad de animación
            if (rawFraction >= 0.5f) {
                pnlLogin.showRegister(isLogin);
                cover.login(!isLogin);
            }

            // Mover ambos paneles juntos
            layout.setComponentConstraints(cover, "width 250!, height 400!, pos " + coverX + " 50%-200");
            layout.setComponentConstraints(pnlLogin, "width 375!, height 400!, pos " + loginX + " 50%-200");
            
            PnlBgLogin.this.revalidate();
            PnlBgLogin.this.repaint();

            if (frameCount >= totalFrames) {
                animator.stop();
                frameCount = 0;
                isLogin = !isLogin;
            }
        });

        this.setLayout(layout);
        int initialCoverX = isLogin ? 0 : 375;
        int initialLoginX = isLogin ? 250 : 0;
        this.add(cover, "width 250!, height 400!, pos " + initialCoverX + " 50%-200");
        this.add(pnlLogin, "width 375!, height 400!, pos " + initialLoginX + " 50%-200");
        
        // TRUCO DE Z-INDEX: Garantizamos que el panel verde siempre flote por encima del formulario
        this.setComponentZOrder(cover, 0);
        this.setComponentZOrder(pnlLogin, 1);
        
        pnlLogin.showRegister(!isLogin);
        cover.login(isLogin);

        cover.addEvent((ActionEvent ae) -> {
            if (!animator.isRunning()) {
                frameCount = 0; // Reset antes de iniciar
                animator.start();
            }
        });
    }
    
    private float easeInOut(float fraction) {
        // Simula setAcceleration y setDeceleration
        return fraction < 0.5f
            ? 2 * fraction * fraction
            : -1 + (4 - 2 * fraction) * fraction;
    }

    public PanelCover getCover() {
        return cover;
    }

    public PnlLogin getPnlLogin() {
        return pnlLogin;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.veterinaria.grupo4.view.auth.PnlLogin pnlLogin;
    // End of variables declaration//GEN-END:variables
}
