-- ============================================================
--  MÓDULO 1 | Esquema de Tablas — DB_VidaAnimal
-- ============================================================
USE DB_VidaAnimal;
GO

-- ─── Usuarios del sistema ────────────────────────────────────
CREATE TABLE USUARIO (
    ID_USUARIO          INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_USUARIO      VARCHAR(50)  NOT NULL,
    CONTRASENA          VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO  VARCHAR(100) NOT NULL,
    ROL                 VARCHAR(20)  NOT NULL DEFAULT 'ADMINISTRADOR',
    FECHA_CREACION      DATETIME     DEFAULT GETDATE(),
    ESTADO              BIT          DEFAULT 1
);
GO

-- ─── Clientes (dueños de mascotas) ───────────────────────────
CREATE TABLE CLIENTE (
    ID_CLIENTE          INT IDENTITY(1,1) PRIMARY KEY,
    CEDULA              VARCHAR(10)  UNIQUE NOT NULL,
    NOMBRE              VARCHAR(50)  NOT NULL,
    APELLIDO            VARCHAR(50)  NOT NULL,
    TELEFONO            VARCHAR(15)  NOT NULL,
    DIRECCION           VARCHAR(100),
    CORREO_ELECTRONICO  VARCHAR(100),
    FECHA_REGISTRO      DATETIME     DEFAULT GETDATE()
);
GO

-- ─── Especialidades veterinarias ─────────────────────────────
CREATE TABLE ESPECIALIDAD_VETERINARIA (
    ID_ESPECIALIDAD     INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_ESPECIALIDAD VARCHAR(50) UNIQUE NOT NULL
);
GO

-- ─── Veterinarios ────────────────────────────────────────────
CREATE TABLE VETERINARIO (
    ID_VETERINARIO      INT IDENTITY(1,1) PRIMARY KEY,
    CEDULA              VARCHAR(10)    UNIQUE NOT NULL,
    NOMBRE              VARCHAR(50)    NOT NULL,
    APELLIDO            VARCHAR(50)    NOT NULL,
    TELEFONO            VARCHAR(15)    NOT NULL,
    PAGO_MENSUAL        DECIMAL(10,2)  DEFAULT 460.00,
    DIRECCION           VARCHAR(100),
    CORREO_ELECTRONICO  VARCHAR(100),
    ID_ESPECIALIDAD     INT,
    FECHA_REGISTRO      DATETIME       DEFAULT GETDATE(),
    FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD_VETERINARIA(ID_ESPECIALIDAD)
);
GO

-- ─── Mascotas ────────────────────────────────────────────────
CREATE TABLE MASCOTA (
    ID_MASCOTA      INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE      INT           NOT NULL,
    NOMBRE          VARCHAR(50)   NOT NULL,
    ESPECIE         VARCHAR(30)   NOT NULL,
    RAZA            VARCHAR(50),
    SEXO            CHAR(1)       CHECK (SEXO IN ('M', 'H')),
    FECHA_NACIMIENTO DATE,
    PESO            DECIMAL(5,2),
    COLOR           VARCHAR(30),
    FOTO            VARBINARY(MAX) NULL,
    FECHA_REGISTRO  DATETIME      DEFAULT GETDATE(),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);
GO

-- ─── Fichas médicas ──────────────────────────────────────────
CREATE TABLE FICHA_MEDICA (
    ID_FICHA              INT IDENTITY(1,1) PRIMARY KEY,
    ID_MASCOTA            INT NOT NULL,
    ALERGIAS              VARCHAR(255),
    ENFERMEDADES_CRONICAS VARCHAR(255),
    OBSERVACIONES         TEXT,
    ULTIMA_ACTUALIZACION  DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA)
);
GO

-- ─── Servicios ───────────────────────────────────────────────
CREATE TABLE SERVICIO (
    ID_SERVICIO       INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_SERVICIO   VARCHAR(50)   NOT NULL,
    DESCRIPCION       VARCHAR(255),
    PRECIO            DECIMAL(10,2) NOT NULL,
    DURACION_ESTIMADA INT,                          -- minutos
    ESTADO            BIT           DEFAULT 1
);
GO

-- ─── Relación Servicio ↔ Veterinario (N:M) ───────────────────
CREATE TABLE SERVICIO_VETERINARIO (
    ID_SERVICIO_VETERINARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_SERVICIO             INT NOT NULL,
    ID_VETERINARIO          INT NOT NULL,
    FECHA_ASIGNACION        DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_SERVICIO)    REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO),
    CONSTRAINT UQ_SERVICIO_VETERINARIO UNIQUE (ID_SERVICIO, ID_VETERINARIO)
);
GO

-- ─── Citas ───────────────────────────────────────────────────
CREATE TABLE CITA (
    ID_CITA        INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE     INT NOT NULL,
    ID_MASCOTA     INT NOT NULL,
    ID_SERVICIO    INT NOT NULL,
    ID_VETERINARIO INT NOT NULL,
    FECHA_HORA     DATETIME NOT NULL,
    ESTADO         VARCHAR(20) DEFAULT 'PENDIENTE'
                   CHECK (ESTADO IN ('PENDIENTE','CANCELADA','REALIZADA')),
    OBSERVACIONES  VARCHAR(255),
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (ID_CLIENTE)  REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_MASCOTA)  REFERENCES MASCOTA(ID_MASCOTA),
    FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);
GO

-- ─── Vacunas aplicadas ───────────────────────────────────────
CREATE TABLE VACUNA_APLICADA (
    ID_VACUNA        INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE           VARCHAR(50)  NOT NULL,
    DESCRIPCION      VARCHAR(255),
    PERIODO_MESES    INT          NOT NULL,
    FECHA_APLICACION DATE         NOT NULL,
    FECHA_PROXIMA    DATE         NOT NULL,
    ID_MASCOTA       INT,
    FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA)
);
GO

-- ─── Método de pago ──────────────────────────────────────────
CREATE TABLE METODO_PAGO (
    ID_METODO_PAGO INT IDENTITY(1,1) PRIMARY KEY,
    METODO         VARCHAR(255)  CHECK (METODO IN ('EFECTIVO','TRANSFERENCIA BANCARIA')) NOT NULL,
    VALOR_TOTAL    DECIMAL(10,2) NOT NULL,
    CUENTA_ORIGEN  VARCHAR(20)   NULL,
    CUENTA_DESTINO VARCHAR(20)   NULL
);
GO

-- ─── Atención médica ─────────────────────────────────────────
CREATE TABLE ATENCION_MEDICA (
    ID_ATENCION_MEDICA INT IDENTITY(1,1) PRIMARY KEY,
    ID_CITA            INT NOT NULL,
    FECHA              DATETIME DEFAULT GETDATE(),
    DIAGNOSTICO        TEXT,
    TRATAMIENTO        TEXT,
    OBSERVACIONES      TEXT,
    FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA)
);
GO

-- ─── Medicamentos ────────────────────────────────────────────
CREATE TABLE MEDICAMENTO (
    ID_MEDICAMENTO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE         VARCHAR(100)  NOT NULL,
    DESCRIPCION    VARCHAR(255),
    PRECIO         DECIMAL(10,2) NOT NULL,
    STOCK          INT           DEFAULT 0,
    ESTADO         BIT           DEFAULT 1
);
GO

-- ─── Medicamentos recetados ──────────────────────────────────
CREATE TABLE MEDICAMENTO_RECETADO (
    ID_MEDICAMENTO_RECETADO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ATENCION_MEDICA      INT NOT NULL,
    ID_MEDICAMENTO          INT NOT NULL,
    DOSIS                   VARCHAR(50),
    FRECUENCIA              VARCHAR(50),
    DURACION                VARCHAR(50),
    FOREIGN KEY (ID_ATENCION_MEDICA) REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA),
    FOREIGN KEY (ID_MEDICAMENTO)     REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
GO

-- ─── Instrumentos médicos ────────────────────────────────────
CREATE TABLE INSTRUMENTO_MEDICO (
    ID_INSTRUMENTO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE         VARCHAR(100)  NOT NULL,
    DESCRIPCION    VARCHAR(255),
    COSTO_USO      DECIMAL(10,2) NOT NULL,
    ESTADO         BIT           DEFAULT 1
);
GO

-- ─── Instrumentos usados ─────────────────────────────────────
CREATE TABLE INSTRUMENTO_USADO (
    ID_INSTRUMENTO_USADO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ATENCION_MEDICA   INT NOT NULL,
    ID_INSTRUMENTO       INT NOT NULL,
    FOREIGN KEY (ID_ATENCION_MEDICA) REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA),
    FOREIGN KEY (ID_INSTRUMENTO)     REFERENCES INSTRUMENTO_MEDICO(ID_INSTRUMENTO)
);
GO

-- ─── Facturas ────────────────────────────────────────────────
CREATE TABLE FACTURA (
    ID_FACTURA     INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE     INT NOT NULL,
    FECHA          DATETIME      DEFAULT GETDATE(),
    SUBTOTAL       DECIMAL(10,2) NOT NULL,
    IVA            DECIMAL(10,2) NOT NULL,
    TOTAL          DECIMAL(10,2) NOT NULL,
    ESTADO         VARCHAR(20)   DEFAULT 'PENDIENTE'
                   CHECK (ESTADO IN ('PENDIENTE','PAGADA','ANULADA')),
    ID_METODO_PAGO INT,
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES CLIENTE(ID_CLIENTE)
);
GO

-- ─── Detalle de factura ──────────────────────────────────────
CREATE TABLE DETALLE_FACTURA (
    ID_DETALLE         INT IDENTITY(1,1) PRIMARY KEY,
    ID_FACTURA         INT NOT NULL,
    ID_SERVICIO        INT NOT NULL, -- Agregamos la columna que faltaba
    CANTIDAD           INT NOT NULL DEFAULT 1,
    PRECIO_UNITARIO    DECIMAL(10,2) NOT NULL,
    DESCUENTO          DECIMAL(10,2) DEFAULT 0,
    TOTAL              DECIMAL(10,2) NOT NULL,
    ID_ATENCION_MEDICA INT,
    FOREIGN KEY (ID_FACTURA)           REFERENCES FACTURA(ID_FACTURA),
    FOREIGN KEY (ID_SERVICIO)          REFERENCES SERVICIO(ID_SERVICIO),
    FOREIGN KEY (ID_ATENCION_MEDICA)   REFERENCES ATENCION_MEDICA(ID_ATENCION_MEDICA)
);
GO

-- ─── Configuración de recordatorios ─────────────────────────
CREATE TABLE RECORDATORIO_CONFIG (
    ID_CONFIG         INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_RECORDATORIO VARCHAR(50)  NOT NULL,   -- 'VACUNA' | 'CITA'
    ANTICIPACION      VARCHAR(20)  NOT NULL,   -- '15_DIAS', '7_DIAS', etc.
    MENSAJE           VARCHAR(255) NOT NULL,
    ACTIVO            BIT          DEFAULT 1
);
GO

-- ─── Recordatorios enviados ──────────────────────────────────
CREATE TABLE RECORDATORIO_ENVIADO (
    ID_RECORDATORIO   INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO        INT,
    ID_CITA           INT,
    ID_VACUNA         INT,
    TIPO              VARCHAR(20)  NOT NULL,   -- 'VACUNA' | 'CITA'
    MENSAJE           VARCHAR(500) NOT NULL,
    FECHA_ENVIO       DATETIME     DEFAULT GETDATE(),
    CONTADOR_MOSTRADO INT          DEFAULT 0,
    LEIDO             BIT          DEFAULT 0,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CITA)    REFERENCES CITA(ID_CITA),
    FOREIGN KEY (ID_VACUNA)  REFERENCES VACUNA_APLICADA(ID_VACUNA)
);
GO
