-- ============================================================
--  MÓDULO 2 | SPs de Usuarios, Clientes y Veterinarios
-- ============================================================
USE db_veterinaria;
GO

-- ════════════════════════════════════════════════════════════
--  USUARIOS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_VALIDAR_USUARIO
    @NOMBRE_USUARIO VARCHAR(50),
    @CONTRASENA     VARCHAR(100)
AS
BEGIN
    SELECT ID_USUARIO, NOMBRE_USUARIO, ROL
    FROM USUARIO
    WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO
      AND CONTRASENA     = @CONTRASENA
      AND ESTADO         = 1;
END;
GO

CREATE PROCEDURE SP_INSERTAR_USUARIO
    @NOMBRE_USUARIO    VARCHAR(50),
    @CONTRASENA        VARCHAR(100),
    @CORREO_ELECTRONICO VARCHAR(100),
    @ROL               VARCHAR(20) = 'ADMINISTRADOR'
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO)
    BEGIN
        INSERT INTO USUARIO (NOMBRE_USUARIO, CONTRASENA, CORREO_ELECTRONICO, ROL)
        VALUES (@NOMBRE_USUARIO, @CONTRASENA, @CORREO_ELECTRONICO, @ROL);
        SELECT SCOPE_IDENTITY() AS ID_USUARIO;
    END
    ELSE
        SELECT -1 AS ID_USUARIO;
END;
GO

CREATE PROCEDURE SP_EXISTE_USUARIO
    @NOMBRE_USUARIO VARCHAR(50)
AS
BEGIN
    SELECT ID_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_USUARIO
    @NOMBRE_USUARIO VARCHAR(50)
AS
BEGIN
    SELECT ID_USUARIO, NOMBRE_USUARIO, CORREO_ELECTRONICO, ROL, FECHA_CREACION, ESTADO
    FROM USUARIO
    WHERE NOMBRE_USUARIO = @NOMBRE_USUARIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_CORREOS_USUARIOS
AS
BEGIN
    SELECT ID_USUARIO, CORREO_ELECTRONICO
    FROM USUARIO
    WHERE ESTADO = 1
    ORDER BY CORREO_ELECTRONICO;
END;
GO

-- ════════════════════════════════════════════════════════════
--  CLIENTES
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_INSERTAR_CLIENTE
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE CEDULA = @CEDULA)
    BEGIN
        INSERT INTO CLIENTE (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
        VALUES (@CEDULA, @NOMBRE, @APELLIDO, @TELEFONO, @DIRECCION, @CORREO_ELECTRONICO);
        SELECT SCOPE_IDENTITY() AS ID_CLIENTE;
    END
    ELSE
        SELECT -1 AS ID_CLIENTE;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_CLIENTE
    @ID_CLIENTE         INT,
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    UPDATE CLIENTE
    SET CEDULA = @CEDULA, NOMBRE = @NOMBRE, APELLIDO = @APELLIDO,
        TELEFONO = @TELEFONO, DIRECCION = @DIRECCION,
        CORREO_ELECTRONICO = @CORREO_ELECTRONICO
    WHERE ID_CLIENTE = @ID_CLIENTE;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_CLIENTE
    @ID_CLIENTE INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE;
END;
GO

CREATE PROCEDURE SP_OBTENER_CEDULAS_CLIENTES
AS
BEGIN
    SELECT CEDULA FROM CLIENTE ORDER BY CEDULA;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTE_POR_CEDULA
    @CEDULA VARCHAR(10)
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE CEDULA = @CEDULA;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTE_POR_ID
    @ID_CLIENTE INT
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES_POR_NOMBRE
    @NOMBRE VARCHAR(50)
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE
    WHERE NOMBRE LIKE @NOMBRE OR APELLIDO LIKE @NOMBRE
    ORDER BY NOMBRE, APELLIDO;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES_POR_MASCOTA
    @NOMBRE_MASCOTA VARCHAR(50),
    @NOMBRE_CLIENTE VARCHAR(50) = NULL
AS
BEGIN
    SELECT DISTINCT
        C.ID_CLIENTE, C.CEDULA, C.NOMBRE, C.APELLIDO, C.TELEFONO,
        C.DIRECCION, C.CORREO_ELECTRONICO, C.FECHA_REGISTRO
    FROM CLIENTE C
    INNER JOIN MASCOTA M ON C.ID_CLIENTE = M.ID_CLIENTE
    WHERE M.NOMBRE LIKE @NOMBRE_MASCOTA
      AND (@NOMBRE_CLIENTE IS NULL
           OR C.NOMBRE  LIKE @NOMBRE_CLIENTE
           OR C.APELLIDO LIKE @NOMBRE_CLIENTE)
    ORDER BY C.NOMBRE, C.APELLIDO;
END;
GO

-- ════════════════════════════════════════════════════════════
--  VETERINARIOS
-- ════════════════════════════════════════════════════════════

CREATE OR ALTER PROCEDURE SP_INSERTAR_VETERINARIO
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @ID_ESPECIALIDAD    INT,
    @PAGO_MENSUAL       DECIMAL(10,2) = 460.00,
    @DIRECCION          VARCHAR(100)  = NULL,
    @CORREO_ELECTRONICO VARCHAR(100)  = NULL
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM VETERINARIO WHERE CEDULA = @CEDULA)
    BEGIN
        INSERT INTO VETERINARIO
            (CEDULA, NOMBRE, APELLIDO, TELEFONO, ID_ESPECIALIDAD,
             PAGO_MENSUAL, DIRECCION, CORREO_ELECTRONICO)
        VALUES
            (@CEDULA, @NOMBRE, @APELLIDO, @TELEFONO, @ID_ESPECIALIDAD,
             @PAGO_MENSUAL, @DIRECCION, @CORREO_ELECTRONICO);
        SELECT SCOPE_IDENTITY() AS ID_VETERINARIO;
    END
    ELSE
        SELECT -1 AS ID_VETERINARIO;
END;
GO

CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_VETERINARIO
    @ID_VETERINARIO     INT,
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @ID_ESPECIALIDAD    INT,
    @PAGO_MENSUAL       DECIMAL(10,2),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    UPDATE VETERINARIO
    SET CEDULA = @CEDULA, NOMBRE = @NOMBRE, APELLIDO = @APELLIDO,
        TELEFONO = @TELEFONO, ID_ESPECIALIDAD = @ID_ESPECIALIDAD,
        PAGO_MENSUAL = @PAGO_MENSUAL, DIRECCION = @DIRECCION,
        CORREO_ELECTRONICO = @CORREO_ELECTRONICO
    WHERE ID_VETERINARIO = @ID_VETERINARIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_VETERINARIO
    @ID_VETERINARIO INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM SERVICIO_VETERINARIO WHERE ID_VETERINARIO = @ID_VETERINARIO;
        DELETE FROM VETERINARIO           WHERE ID_VETERINARIO = @ID_VETERINARIO;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS
AS
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA, 
        V.NOMBRE, 
        V.APELLIDO, 
        V.TELEFONO,
        V.PAGO_MENSUAL, 
        V.DIRECCION, 
        V.CORREO_ELECTRONICO, 
        V.FECHA_REGISTRO,
        V.ID_ESPECIALIDAD AS ID_ESPECIALIDAD, 
        E.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE OR ALTER PROCEDURE SP_BUSCAR_VETERINARIOS
    @TERMINO VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT V.ID_VETERINARIO, 
           V.CEDULA, 
           V.NOMBRE, 
           V.APELLIDO, 
           V.TELEFONO,
           V.ID_ESPECIALIDAD,
           E.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD,
           V.CORREO_ELECTRONICO
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.NOMBRE   LIKE '%' + @TERMINO + '%' 
       OR V.APELLIDO LIKE '%' + @TERMINO + '%'
       OR V.CEDULA   LIKE '%' + @TERMINO + '%'
    ORDER BY V.NOMBRE ASC;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIO_POR_CEDULA
    @CEDULA VARCHAR(10)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.CEDULA = @CEDULA;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIO_POR_ID
    @ID_VETERINARIO INT
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.ID_VETERINARIO = @ID_VETERINARIO;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_POR_NOMBRE
    @NOMBRE VARCHAR(50)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.NOMBRE LIKE @NOMBRE OR V.APELLIDO LIKE @NOMBRE
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_POR_ESPECIALIDAD
    @NOMBRE_ESPECIALIDAD VARCHAR(50)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    INNER JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE EV.NOMBRE_ESPECIALIDAD LIKE @NOMBRE_ESPECIALIDAD;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_ESPECIALIDADES
AS
BEGIN
    SELECT ID_ESPECIALIDAD, NOMBRE_ESPECIALIDAD
    FROM ESPECIALIDAD_VETERINARIA
    ORDER BY NOMBRE_ESPECIALIDAD;
END;
GO