-- ============================================================
--  MÓDULO 2 | SPs de Usuarios, Clientes y Veterinarios
-- ============================================================
USE db_veterinaria;
GO

-- ════════════════════════════════════════════════════════════
--  USUARIOS
-- ════════════════════════════════════════════════════════════
CREATE OR ALTER PROCEDURE SP_VALIDAR_USUARIO
    @EMAIL              VARCHAR(100),
    @CONTRASENA         VARCHAR(100)
AS
BEGIN
    SELECT 
        ID_USUARIO, 
        CORREO_ELECTRONICO AS EMAIL,
        ROL,
        ESTADO,
        -- Determinar si es veterinario o recepcionista
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = @EMAIL) 
                THEN 'VETERINARIO'
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = @EMAIL) 
                THEN 'RECEPCIONISTA'
            ELSE ROL
        END AS ROL,
        -- Datos de la persona asociada
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = @EMAIL) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM VETERINARIO WHERE CORREO_ELECTRONICO = @EMAIL)
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = @EMAIL) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = @EMAIL)
            ELSE 'Administrador'
        END AS NOMBRE_COMPLETO
    FROM USUARIO
    WHERE CORREO_ELECTRONICO = @EMAIL
      AND CONTRASENA = @CONTRASENA
      AND ESTADO = 1;
END;
GO

CREATE OR ALTER PROCEDURE SP_INSERTAR_USUARIO
    @EMAIL              VARCHAR(100),
    @CONTRASENA         VARCHAR(100),
    @ROL                VARCHAR(20) = 'ADMINISTRADOR'
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = @EMAIL)
    BEGIN
        INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL)
        VALUES (@EMAIL, @CONTRASENA, @ROL);
        SELECT SCOPE_IDENTITY() AS ID_USUARIO;
    END
    ELSE
        SELECT -1 AS ID_USUARIO;
END;
GO

CREATE OR ALTER PROCEDURE SP_EXISTE_USUARIO
    @EMAIL VARCHAR(100)
AS
BEGIN
    SELECT ID_USUARIO FROM USUARIO WHERE CORREO_ELECTRONICO = @EMAIL;
END;
GO
-- ============================================================
--  SP_OBTENER_USUARIO - Ahora busca por email
-- ============================================================
CREATE OR ALTER PROCEDURE SP_OBTENER_USUARIO
    @EMAIL VARCHAR(100)
AS
BEGIN
    SELECT 
        U.ID_USUARIO,
        U.CORREO_ELECTRONICO,
        U.ROL,
        U.FECHA_CREACION,
        U.ESTADO,
        -- Datos de la persona asociada
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN 'VETERINARIO'
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN 'RECEPCIONISTA'
            ELSE U.ROL
        END AS ROL_EFECTIVO,
        CASE 
            WHEN EXISTS (SELECT 1 FROM VETERINARIO V WHERE V.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM VETERINARIO WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO)
            WHEN EXISTS (SELECT 1 FROM RECEPCIONISTA R WHERE R.CORREO_ELECTRONICO = U.CORREO_ELECTRONICO) 
                THEN (SELECT CONCAT(NOMBRE, ' ', APELLIDO) FROM RECEPCIONISTA WHERE CORREO_ELECTRONICO = U.CORREO_ELECTRONICO)
            ELSE 'Administrador'
        END AS NOMBRE_COMPLETO
    FROM USUARIO U
    WHERE U.CORREO_ELECTRONICO = @EMAIL;
END;
GO

CREATE PROCEDURE SP_OBTENER_CORREOS_USUARIOS
AS
BEGIN
    SELECT ID_USUARIO, CORREO_ELECTRONICO
    FROM USUARIO
    WHERE ESTADO = 1
    ORDER BY CORREO_ELECTRONICO;
END;
GO

-- ════════════════════════════════════════════════════════════
--  CLIENTES
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_INSERTAR_CLIENTE
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE CEDULA = @CEDULA)
    BEGIN
        INSERT INTO CLIENTE (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
        VALUES (@CEDULA, @NOMBRE, @APELLIDO, @TELEFONO, @DIRECCION, @CORREO_ELECTRONICO);
        SELECT SCOPE_IDENTITY() AS ID_CLIENTE;
    END
    ELSE
        SELECT -1 AS ID_CLIENTE;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_CLIENTE
    @ID_CLIENTE         INT,
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    UPDATE CLIENTE
    SET CEDULA = @CEDULA, NOMBRE = @NOMBRE, APELLIDO = @APELLIDO,
        TELEFONO = @TELEFONO, DIRECCION = @DIRECCION,
        CORREO_ELECTRONICO = @CORREO_ELECTRONICO
    WHERE ID_CLIENTE = @ID_CLIENTE;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_CLIENTE
    @ID_CLIENTE INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE;
END;
GO

CREATE PROCEDURE SP_OBTENER_CEDULAS_CLIENTES
AS
BEGIN
    SELECT CEDULA FROM CLIENTE ORDER BY CEDULA;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTE_POR_CEDULA
    @CEDULA VARCHAR(10)
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE CEDULA = @CEDULA;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTE_POR_ID
    @ID_CLIENTE INT
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES_POR_NOMBRE
    @NOMBRE VARCHAR(50)
AS
BEGIN
    SELECT ID_CLIENTE, CEDULA, NOMBRE, APELLIDO, TELEFONO,
           DIRECCION, CORREO_ELECTRONICO, FECHA_REGISTRO
    FROM CLIENTE
    WHERE NOMBRE LIKE @NOMBRE OR APELLIDO LIKE @NOMBRE
    ORDER BY NOMBRE, APELLIDO;
END;
GO

CREATE PROCEDURE SP_OBTENER_CLIENTES_POR_MASCOTA
    @NOMBRE_MASCOTA VARCHAR(50),
    @NOMBRE_CLIENTE VARCHAR(50) = NULL
AS
BEGIN
    SELECT DISTINCT
        C.ID_CLIENTE, C.CEDULA, C.NOMBRE, C.APELLIDO, C.TELEFONO,
        C.DIRECCION, C.CORREO_ELECTRONICO, C.FECHA_REGISTRO
    FROM CLIENTE C
    INNER JOIN MASCOTA M ON C.ID_CLIENTE = M.ID_CLIENTE
    WHERE M.NOMBRE LIKE @NOMBRE_MASCOTA
      AND (@NOMBRE_CLIENTE IS NULL
           OR C.NOMBRE  LIKE @NOMBRE_CLIENTE
           OR C.APELLIDO LIKE @NOMBRE_CLIENTE)
    ORDER BY C.NOMBRE, C.APELLIDO;
END;
GO

-- ════════════════════════════════════════════════════════════
--  VETERINARIOS
-- ════════════════════════════════════════════════════════════

CREATE OR ALTER PROCEDURE SP_INSERTAR_VETERINARIO
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @ID_ESPECIALIDAD    INT,
    @PAGO_MENSUAL       DECIMAL(10,2) = 460.00,
    @DIRECCION          VARCHAR(100)  = NULL,
    @CORREO_ELECTRONICO VARCHAR(100)  = NULL
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM VETERINARIO WHERE CEDULA = @CEDULA)
    BEGIN
        INSERT INTO VETERINARIO
            (CEDULA, NOMBRE, APELLIDO, TELEFONO, ID_ESPECIALIDAD,
             PAGO_MENSUAL, DIRECCION, CORREO_ELECTRONICO)
        VALUES
            (@CEDULA, @NOMBRE, @APELLIDO, @TELEFONO, @ID_ESPECIALIDAD,
             @PAGO_MENSUAL, @DIRECCION, @CORREO_ELECTRONICO);
        SELECT SCOPE_IDENTITY() AS ID_VETERINARIO;
    END
    ELSE
        SELECT -1 AS ID_VETERINARIO;
END;
GO
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_VETERINARIO
    @ID_VETERINARIO     INT,
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @ID_ESPECIALIDAD    INT,
    @PAGO_MENSUAL       DECIMAL(10,2),
    @DIRECCION          VARCHAR(100) = NULL,
    @CORREO_ELECTRONICO VARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @EMAIL_ACTUAL VARCHAR(100);

    BEGIN TRY
        BEGIN TRANSACTION;

        -- 1. Obtener email actual del veterinario
        SELECT @EMAIL_ACTUAL = CORREO_ELECTRONICO
        FROM VETERINARIO
        WHERE ID_VETERINARIO = @ID_VETERINARIO;

        IF @EMAIL_ACTUAL IS NULL
        BEGIN
            RAISERROR('No existe un veterinario con ese ID.', 16, 1);
            ROLLBACK TRANSACTION;
            RETURN;
        END

        -- 2. Si el email cambió, verificar que no esté en uso por OTRO usuario
        IF @EMAIL_ACTUAL <> @CORREO_ELECTRONICO
        BEGIN
            IF EXISTS (
                SELECT 1 FROM USUARIO
                WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO
            )
            BEGIN
                RAISERROR('El correo electrónico ya está registrado por otro usuario.', 16, 1);
                ROLLBACK TRANSACTION;
                SELECT 0 AS FILAS_AFECTADAS;
                RETURN;
            END

            -- Actualizar USUARIO: la cascada actualiza VETERINARIO automáticamente
            UPDATE USUARIO
            SET CORREO_ELECTRONICO = @CORREO_ELECTRONICO
            WHERE CORREO_ELECTRONICO = @EMAIL_ACTUAL;
        END

        -- 3. Actualizar el resto de campos de VETERINARIO
        UPDATE VETERINARIO
        SET CEDULA          = @CEDULA,
            NOMBRE          = @NOMBRE,
            APELLIDO        = @APELLIDO,
            TELEFONO        = @TELEFONO,
            ID_ESPECIALIDAD = @ID_ESPECIALIDAD,
            PAGO_MENSUAL    = @PAGO_MENSUAL,
            DIRECCION       = @DIRECCION
        WHERE ID_VETERINARIO = @ID_VETERINARIO;

        COMMIT TRANSACTION;
        SELECT 1 AS FILAS_AFECTADAS;

    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ErrorMessage, 16, 1);
        SELECT 0 AS FILAS_AFECTADAS;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_ELIMINAR_VETERINARIO
    @ID_VETERINARIO INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM SERVICIO_VETERINARIO WHERE ID_VETERINARIO = @ID_VETERINARIO;
        DELETE FROM VETERINARIO           WHERE ID_VETERINARIO = @ID_VETERINARIO;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS
AS
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA, 
        V.NOMBRE, 
        V.APELLIDO, 
        V.TELEFONO,
        V.PAGO_MENSUAL, 
        V.DIRECCION, 
        V.CORREO_ELECTRONICO, 
        V.FECHA_REGISTRO,
        V.ID_ESPECIALIDAD AS ID_ESPECIALIDAD, 
        E.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE OR ALTER PROCEDURE SP_BUSCAR_VETERINARIOS
    @TERMINO VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT V.ID_VETERINARIO, 
           V.CEDULA, 
           V.NOMBRE, 
           V.APELLIDO, 
           V.TELEFONO,
           V.ID_ESPECIALIDAD,
           E.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD,
           V.CORREO_ELECTRONICO
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.NOMBRE   LIKE '%' + @TERMINO + '%' 
       OR V.APELLIDO LIKE '%' + @TERMINO + '%'
       OR V.CEDULA   LIKE '%' + @TERMINO + '%'
    ORDER BY V.NOMBRE ASC;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIO_POR_CEDULA
    @CEDULA VARCHAR(10)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.CEDULA = @CEDULA;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIO_POR_ID
    @ID_VETERINARIO INT
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.ID_VETERINARIO = @ID_VETERINARIO;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_POR_NOMBRE
    @NOMBRE VARCHAR(50)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE V.NOMBRE LIKE @NOMBRE OR V.APELLIDO LIKE @NOMBRE
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_POR_ESPECIALIDAD
    @NOMBRE_ESPECIALIDAD VARCHAR(50)
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO, V.TELEFONO,
           EV.NOMBRE_ESPECIALIDAD AS NOMBRE_ESPECIALIDAD, V.PAGO_MENSUAL,
           V.DIRECCION, V.CORREO_ELECTRONICO, V.FECHA_REGISTRO,
           V.ID_ESPECIALIDAD
    FROM VETERINARIO V
    INNER JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD = EV.ID_ESPECIALIDAD
    WHERE EV.NOMBRE_ESPECIALIDAD LIKE @NOMBRE_ESPECIALIDAD;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_ESPECIALIDADES
AS
BEGIN
    SELECT ID_ESPECIALIDAD, NOMBRE_ESPECIALIDAD
    FROM ESPECIALIDAD_VETERINARIA
    ORDER BY NOMBRE_ESPECIALIDAD;
END;
GO
--  SP_REGISTRAR_RECEPCIONISTA
-- ============================================================
CREATE OR ALTER PROCEDURE SP_REGISTRAR_RECEPCIONISTA
    @CEDULA             VARCHAR(10),
    @NOMBRE             VARCHAR(50),
    @APELLIDO           VARCHAR(50),
    @TELEFONO           VARCHAR(15),
    @DIRECCION          VARCHAR(100) = NULL,
    @EMAIL              VARCHAR(100),
    @CONTRASENA         VARCHAR(100)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        
        -- 1. Verificar que el email no exista en USUARIO
        IF EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = @EMAIL)
        BEGIN
            SELECT -1 AS RESULTADO, 'El correo electrónico ya está registrado' AS MENSAJE;
            ROLLBACK;
            RETURN;
        END;
        
        -- 2. Verificar que la cédula no exista en RECEPCIONISTA
        IF EXISTS (SELECT 1 FROM RECEPCIONISTA WHERE CEDULA = @CEDULA)
        BEGIN
            SELECT -2 AS RESULTADO, 'La cédula ya está registrada' AS MENSAJE;
            ROLLBACK;
            RETURN;
        END;
        
        -- 3. Insertar en USUARIO
        INSERT INTO USUARIO (CORREO_ELECTRONICO, CONTRASENA, ROL)
        VALUES (@EMAIL, @CONTRASENA, 'RECEPCIONISTA');
        
        DECLARE @ID_USUARIO INT = SCOPE_IDENTITY();
        
        -- 4. Insertar en RECEPCIONISTA
        INSERT INTO RECEPCIONISTA 
            (CEDULA, NOMBRE, APELLIDO, TELEFONO, DIRECCION, CORREO_ELECTRONICO)
        VALUES 
            (@CEDULA, @NOMBRE, @APELLIDO, @TELEFONO, @DIRECCION, @EMAIL);
        
        DECLARE @ID_RECEPCIONISTA INT = SCOPE_IDENTITY();
        
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO, 'Recepcionista registrado correctamente' AS MENSAJE, @ID_RECEPCIONISTA AS ID;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT -3 AS RESULTADO, ERROR_MESSAGE() AS MENSAJE;
    END CATCH
END;
GO
CREATE OR ALTER PROCEDURE SP_RESTABLECER_CONTRASENA
    @EMAIL              VARCHAR(100),
    @NUEVA_CONTRASENA   VARCHAR(100)
AS
BEGIN
    IF EXISTS (SELECT 1 FROM USUARIO WHERE CORREO_ELECTRONICO = @EMAIL AND ESTADO = 1)
    BEGIN
        UPDATE USUARIO
        SET CONTRASENA = @NUEVA_CONTRASENA
        WHERE CORREO_ELECTRONICO = @EMAIL;
        
        SELECT 1 AS RESULTADO, 'Contraseña actualizada correctamente' AS MENSAJE;
    END
    ELSE
    BEGIN
        SELECT 0 AS RESULTADO, 'Usuario no encontrado' AS MENSAJE;
    END
END;
GO