-- ============================================================
--  MÓDULO 3 | SPs de Mascotas y Citas
-- ============================================================
USE db_veterinaria;
GO

-- ════════════════════════════════════════════════════════════
--  MASCOTAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_INSERTAR_MASCOTA
    @ID_CLIENTE      INT,
    @NOMBRE          VARCHAR(50),
    @ESPECIE         VARCHAR(30),
    @RAZA            VARCHAR(50)    = NULL,
    @SEXO            CHAR(1),
    @FECHA_NACIMIENTO DATE          = NULL,
    @PESO            DECIMAL(5,2)   = NULL,
    @COLOR           VARCHAR(30)    = NULL,
    @FOTO            VARBINARY(MAX) = NULL
AS
BEGIN
    INSERT INTO MASCOTA
        (ID_CLIENTE, NOMBRE, ESPECIE, RAZA, SEXO, FECHA_NACIMIENTO, PESO, COLOR, FOTO)
    VALUES
        (@ID_CLIENTE, @NOMBRE, @ESPECIE, @RAZA, @SEXO, @FECHA_NACIMIENTO, @PESO, @COLOR, @FOTO);
    SELECT SCOPE_IDENTITY() AS ID_MASCOTA;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_MASCOTA
    @ID_MASCOTA      INT,
    @ID_CLIENTE      INT,
    @NOMBRE          VARCHAR(50),
    @ESPECIE         VARCHAR(30),
    @RAZA            VARCHAR(50)    = NULL,
    @SEXO            CHAR(1)        = NULL,
    @FECHA_NACIMIENTO DATE          = NULL,
    @PESO            DECIMAL(5,2)   = NULL,
    @COLOR           VARCHAR(30)    = NULL,
    @FOTO            VARBINARY(MAX) = NULL
AS
BEGIN
    BEGIN TRY
        UPDATE MASCOTA
        SET ID_CLIENTE       = @ID_CLIENTE,
            NOMBRE           = @NOMBRE,
            ESPECIE          = @ESPECIE,
            RAZA             = ISNULL(@RAZA, RAZA),
            SEXO             = ISNULL(@SEXO, SEXO),
            FECHA_NACIMIENTO = ISNULL(@FECHA_NACIMIENTO, FECHA_NACIMIENTO),
            PESO             = ISNULL(@PESO, PESO),
            COLOR            = ISNULL(@COLOR, COLOR),
            FOTO             = ISNULL(@FOTO, FOTO)
        WHERE ID_MASCOTA = @ID_MASCOTA;
        IF @@ROWCOUNT = 0 RETURN 0;
        RETURN 1;
    END TRY
    BEGIN CATCH
        THROW;
        RETURN 0;
    END CATCH
END;
GO
USE db_veterinaria;
GO
CREATE OR ALTER PROCEDURE SP_ELIMINAR_MASCOTA
    @ID_MASCOTA INT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        -- Verificar si la mascota tiene atenciones médicas (antecedentes clínicos)
        IF EXISTS (
            SELECT 1
            FROM ATENCION_MEDICA AM
            INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
            WHERE C.ID_MASCOTA = @ID_MASCOTA
        )
        BEGIN
            ROLLBACK TRANSACTION;
            -- Lanzar error con RAISERROR
            RAISERROR('La mascota ya posee una cita médica realizada. No se puede eliminar.', 16, 1);
            RETURN;
        END

        -- Verificar si la mascota tiene citas pendientes
        IF EXISTS (SELECT 1 FROM CITA WHERE ID_MASCOTA = @ID_MASCOTA AND ESTADO = 'PENDIENTE')
        BEGIN
            ROLLBACK TRANSACTION;
            RAISERROR('La mascota tiene citas pendientes. No se puede eliminar.', 16, 1);
            RETURN;
        END

        -- Eliminar ficha médica
        DELETE FROM FICHA_MEDICA WHERE ID_MASCOTA = @ID_MASCOTA;

        -- Eliminar mascota
        DELETE FROM MASCOTA WHERE ID_MASCOTA = @ID_MASCOTA;

        COMMIT TRANSACTION;
        
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ErrorMessage, 16, 1);
    END CATCH
END;
GO

CREATE PROCEDURE SP_OBTENER_MASCOTAS_POR_CLIENTE
    @ID_CLIENTE INT
AS
BEGIN
    IF @ID_CLIENTE = 0
        SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
               M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
               C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_DUENO,
               C.CEDULA AS CEDULA_CLIENTE, C.ID_CLIENTE
        FROM MASCOTA M
        INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE;
    ELSE
        SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
               M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
               C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_DUENO,
               C.CEDULA AS CEDULA_CLIENTE, C.ID_CLIENTE
        FROM MASCOTA M
        INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
        WHERE M.ID_CLIENTE = @ID_CLIENTE;
END;
GO

CREATE PROCEDURE SP_OBTENER_MASCOTAS
AS
BEGIN
    SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           C.ID_CLIENTE,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_DUENO,
           C.CEDULA   AS CEDULA_CLIENTE,
           C.TELEFONO AS TELEFONO_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    ORDER BY M.NOMBRE;
END;
GO

CREATE OR ALTER PROCEDURE SP_BUSCAR_MASCOTAS
    @TERMINO VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT M.ID_MASCOTA, M.ID_CLIENTE, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
           C.CEDULA AS CEDULA_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    WHERE M.NOMBRE LIKE '%' + @TERMINO + '%' 
       OR C.CEDULA LIKE '%' + @TERMINO + '%'
       OR C.NOMBRE LIKE '%' + @TERMINO + '%'
       OR C.APELLIDO LIKE '%' + @TERMINO + '%'
    ORDER BY M.NOMBRE;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_MASCOTA_POR_ID
    @ID_MASCOTA INT
AS
BEGIN
    SELECT M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR, M.FOTO, M.FECHA_REGISTRO,
           C.ID_CLIENTE,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_DUENO,
           C.CEDULA   AS CEDULA_CLIENTE,
           C.TELEFONO AS TELEFONO_CLIENTE
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    WHERE M.ID_MASCOTA = @ID_MASCOTA;
END;
GO

CREATE PROCEDURE SP_OBTENER_FOTO_MASCOTA
    @ID_MASCOTA INT
AS
BEGIN
    SELECT FOTO FROM MASCOTA WHERE ID_MASCOTA = @ID_MASCOTA;
END;
GO

-- ════════════════════════════════════════════════════════════
--  CITAS
-- ════════════════════════════════════════════════════════════
CREATE PROCEDURE SP_AGENDAR_CITA
    @ID_CLIENTE    INT,
    @ID_MASCOTA    INT,
    @ID_SERVICIO   INT,
    @ID_VETERINARIO INT,
    @FECHA_HORA    DATETIME,
    @OBSERVACIONES VARCHAR(255) = NULL
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (
            SELECT 1 FROM CITA
            WHERE FECHA_HORA = @FECHA_HORA 
            AND ID_VETERINARIO = @ID_VETERINARIO
            AND ESTADO = 'PENDIENTE'
        )
        BEGIN
            ROLLBACK;
            SELECT -1 AS ID_CITA;  -- horario ocupado
            RETURN;
        END

        INSERT INTO CITA (ID_CLIENTE, ID_MASCOTA, ID_SERVICIO, ID_VETERINARIO, FECHA_HORA, OBSERVACIONES)
        VALUES (@ID_CLIENTE, @ID_MASCOTA, @ID_SERVICIO, @ID_VETERINARIO, @FECHA_HORA, @OBSERVACIONES);

        DECLARE @ID_CITA INT = SCOPE_IDENTITY();

        COMMIT;
        SELECT @ID_CITA AS ID_CITA;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        SELECT -2 AS ID_CITA;  -- error general
    END CATCH
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_CITA_COMPLETA
    @ID_CITA       INT,
    @ID_CLIENTE    INT,
    @ID_MASCOTA    INT,
    @ID_SERVICIO   INT,
    @ID_VETERINARIO INT,
    @FECHA_HORA    DATETIME,
    @ESTADO        VARCHAR(20),
    @OBSERVACIONES VARCHAR(255)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE CITA
        SET ID_CLIENTE = @ID_CLIENTE, 
            ID_MASCOTA = @ID_MASCOTA, 
            ID_SERVICIO = @ID_SERVICIO,
            ID_VETERINARIO = @ID_VETERINARIO,
            FECHA_HORA = @FECHA_HORA, 
            ESTADO = @ESTADO,
            OBSERVACIONES = @OBSERVACIONES
        WHERE ID_CITA = @ID_CITA;

        COMMIT;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_CANCELAR_CITA
    @ID_CITA INT,
    @MOTIVO  VARCHAR(255) = NULL
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE CITA
        SET ESTADO = 'CANCELADA',
            OBSERVACIONES = ISNULL(OBSERVACIONES + ' | ', '') +
                            'Cancelación: ' + ISNULL(@MOTIVO, 'Sin motivo especificado')
        WHERE ID_CITA = @ID_CITA;
        
        IF @@ROWCOUNT > 0
        BEGIN
            COMMIT TRANSACTION;
            SELECT 1 AS RESULTADO;
        END
        ELSE
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT 0 AS RESULTADO;
        END
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_ESTADO_CITA
    @ID_CITA INT,
    @ESTADO  VARCHAR(20)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE CITA SET ESTADO = @ESTADO WHERE ID_CITA = @ID_CITA;
        IF @@ROWCOUNT > 0
        BEGIN
            COMMIT TRANSACTION;
            SELECT 1 AS RESULTADO;
        END
        ELSE
        BEGIN
            ROLLBACK TRANSACTION;
            SELECT 0 AS RESULTADO;
        END
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_ELIMINAR_CITA_COMPLETA
    @ID_CITA INT
AS
BEGIN
    DELETE FROM CITA WHERE ID_CITA = @ID_CITA;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_TODAS_LAS_CITAS
AS
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES, C.FECHA_REGISTRO
    FROM CITA C
    INNER JOIN CLIENTE     CL ON C.ID_CLIENTE     = CL.ID_CLIENTE
    INNER JOIN MASCOTA     M  ON C.ID_MASCOTA     = M.ID_MASCOTA
    INNER JOIN SERVICIO    S  ON C.ID_SERVICIO    = S.ID_SERVICIO
    INNER JOIN VETERINARIO V  ON C.ID_VETERINARIO = V.ID_VETERINARIO
    ORDER BY C.FECHA_HORA DESC;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_CITAS_POR_FECHA
    @FECHA DATE
AS
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES
    FROM CITA C
    INNER JOIN CLIENTE     CL ON C.ID_CLIENTE     = CL.ID_CLIENTE
    INNER JOIN MASCOTA     M  ON C.ID_MASCOTA     = M.ID_MASCOTA
    INNER JOIN SERVICIO    S  ON C.ID_SERVICIO    = S.ID_SERVICIO
    INNER JOIN VETERINARIO V  ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE CONVERT(DATE, C.FECHA_HORA) = @FECHA
    ORDER BY C.FECHA_HORA;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_CITA_COMPLETA
    @ID_CITA INT
AS
BEGIN
    SELECT C.ID_CITA, 
           C.ID_CLIENTE, CL.NOMBRE + ' ' + CL.APELLIDO AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA, M.SEXO,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.ID_VETERINARIO, V.NOMBRE AS NOMBRE_VETERINARIO, V.APELLIDO AS APELLIDO_VETERINARIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES, C.FECHA_REGISTRO
    FROM CITA C
    INNER JOIN CLIENTE     CL ON C.ID_CLIENTE     = CL.ID_CLIENTE
    INNER JOIN MASCOTA     M  ON C.ID_MASCOTA     = M.ID_MASCOTA
    INNER JOIN SERVICIO    S  ON C.ID_SERVICIO    = S.ID_SERVICIO
    INNER JOIN VETERINARIO V  ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE C.ID_CITA = @ID_CITA;
END;
GO
CREATE OR ALTER PROCEDURE SP_OBTENER_CITAS_PENDIENTES
AS
BEGIN
    SELECT C.ID_CITA,
           C.ESTADO,                                           
           C.FECHA_HORA,
           C.OBSERVACIONES,
           C.FECHA_REGISTRO,                                   

           -- Cliente
           CL.ID_CLIENTE,                                      
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE, 
           CL.CEDULA AS CEDULA_CLIENTE,

           -- Mascota
           M.ID_MASCOTA,                                       
           M.NOMBRE AS NOMBRE_MASCOTA,
           M.ESPECIE AS ESPECIE_MASCOTA,
           
           -- Servicio
           S.ID_SERVICIO,                                      
           S.NOMBRE_SERVICIO,

           -- Veterinario
           V.ID_VETERINARIO,
           V.NOMBRE  AS NOMBRE_VETERINARIO,
           V.APELLIDO AS APELLIDO_VETERINARIO,

           CONCAT(S.NOMBRE_SERVICIO, ' - ',
                  FORMAT(C.FECHA_HORA, 'dd/MM/yyyy HH:mm'),
                  ' - ', M.NOMBRE, ' (Dr. ', V.APELLIDO, ')') AS DISPLAY_TEXT
    FROM CITA C
    INNER JOIN CLIENTE     CL ON C.ID_CLIENTE     = CL.ID_CLIENTE
    INNER JOIN MASCOTA     M  ON C.ID_MASCOTA     = M.ID_MASCOTA
    INNER JOIN SERVICIO     S  ON C.ID_SERVICIO    = S.ID_SERVICIO
    INNER JOIN VETERINARIO V  ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE C.ESTADO = 'PENDIENTE'
    ORDER BY C.FECHA_HORA ASC;
END;
GO

CREATE OR ALTER PROCEDURE SP_VERIFICAR_CITA_PENDIENTE
    @ID_CITA INT
AS
BEGIN
    SET NOCOUNT ON;
    -- Si no existe ninguna atención médica para esta cita, sigue pendiente
    IF NOT EXISTS (SELECT 1 FROM ATENCION_MEDICA WHERE ID_CITA = @ID_CITA)
    BEGIN
        RETURN 1;  -- Sigue pendiente
    END
    RETURN 0;  -- Ya fue atendida
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_ATENCIONES_POR_CITA
    @ID_CITA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT AM.ID_ATENCION_MEDICA, AM.FECHA, AM.DIAGNOSTICO,
           AM.TRATAMIENTO, AM.OBSERVACIONES,
           V.NOMBRE + ' ' + V.APELLIDO AS VETERINARIO -- Nombre del médico asignado a la cita
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA -- Puente necesario
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO -- El médico viene de la CITA
    WHERE AM.ID_CITA = @ID_CITA
    ORDER BY AM.FECHA DESC;
END;
GO

CREATE OR ALTER TRIGGER TR_ACTUALIZAR_ESTADO_CITA
ON ATENCION_MEDICA
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    
    -- Recolectar IDs de las citas afectadas (ya sea por INSERT o DELETE)
    DECLARE @CitasAfectadas TABLE (ID_CITA INT);
    INSERT INTO @CitasAfectadas
    SELECT DISTINCT ID_CITA FROM inserted
    UNION
    SELECT DISTINCT ID_CITA FROM deleted;

    -- Actualizar el estado de la cita
    UPDATE C
    SET ESTADO = CASE
        -- Si hay un registro en atención médica para esta cita, se completó
        WHEN EXISTS (SELECT 1 FROM ATENCION_MEDICA AM WHERE AM.ID_CITA = C.ID_CITA) THEN 'REALIZADA'
        ELSE 'PENDIENTE'
    END
    FROM CITA C
    INNER JOIN @CitasAfectadas CA ON C.ID_CITA = CA.ID_CITA
    WHERE C.ESTADO <> 'CANCELADA'; -- Evitamos revivir citas que fueron canceladas manualmente
END;
GO