-- ============================================================
--  MÓDULO 4 | SPs de Atención Médica, Instrumentos y Medicamentos
-- ============================================================
USE db_veterinaria;
GO

-- ════════════════════════════════════════════════════════════
--  ATENCIÓN MÉDICA
-- ════════════════════════════════════════════════════════════

CREATE OR ALTER PROCEDURE SP_OBTENER_CITAS_POR_SERVICIO_VETERINARIO
    @ID_SERVICIO    INT,
    @ID_VETERINARIO INT,
    @ESTADO         VARCHAR(20)
AS
BEGIN
    SELECT C.ID_CITA, C.ID_CLIENTE,
           CL.NOMBRE + ' ' + CL.APELLIDO AS NOMBRE_CLIENTE,
           C.ID_SERVICIO, S.NOMBRE_SERVICIO, C.FECHA_HORA, C.ESTADO,
           'Cliente: ' + CL.NOMBRE + ' ' + CL.APELLIDO +
           ' - Fecha: ' + CONVERT(VARCHAR, C.FECHA_HORA, 103) + ' ' +
                          CONVERT(VARCHAR, C.FECHA_HORA, 108) AS DESCRIPCION_CITA
    FROM CITA C
    INNER JOIN CLIENTE  CL ON C.ID_CLIENTE  = CL.ID_CLIENTE
    INNER JOIN SERVICIO S  ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE C.ID_SERVICIO     = @ID_SERVICIO
      AND C.ID_VETERINARIO  = @ID_VETERINARIO
      AND C.ESTADO          = @ESTADO
    ORDER BY C.FECHA_HORA DESC;
END;
GO

CREATE OR ALTER PROCEDURE SP_INSERTAR_ATENCION_MEDICA
    @ID_CITA        INT,
    @DIAGNOSTICO    TEXT,
    @TRATAMIENTO    TEXT,
    @OBSERVACIONES  TEXT = NULL
AS
BEGIN
    -- Validamos que la cita exista y no esté cancelada
    IF EXISTS (SELECT 1 FROM CITA WHERE ID_CITA = @ID_CITA AND ESTADO <> 'CANCELADA')
    BEGIN
        INSERT INTO ATENCION_MEDICA (ID_CITA, DIAGNOSTICO, TRATAMIENTO, OBSERVACIONES)
        VALUES (@ID_CITA, @DIAGNOSTICO, @TRATAMIENTO, @OBSERVACIONES);
        
        SELECT SCOPE_IDENTITY() AS ID_ATENCION_MEDICA;
    END
    ELSE
        SELECT 0 AS ID_ATENCION_MEDICA;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_TODAS_ATENCIONES_MEDICAS
AS
BEGIN
    SET NOCOUNT ON;
    SELECT AM.ID_ATENCION_MEDICA,
           M.NOMBRE AS NOMBRE_MASCOTA,
           V.NOMBRE + ' ' + V.APELLIDO AS NOMBRE_VETERINARIO,
           AM.FECHA, AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA        C ON AM.ID_CITA        = C.ID_CITA -- Salto a Cita
    INNER JOIN MASCOTA     M ON C.ID_MASCOTA      = M.ID_MASCOTA -- De Cita a Mascota
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO -- De Cita a Vet
    ORDER BY AM.FECHA DESC;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_DETALLES_ATENCION_MEDICA
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    SELECT AM.ID_ATENCION_MEDICA, AM.FECHA, AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES,
           M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE,
           V.NOMBRE + ' ' + V.APELLIDO AS NOMBRE_VETERINARIO,
           S.NOMBRE_SERVICIO, S.PRECIO AS PRECIO_SERVICIO
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA        C ON AM.ID_CITA        = C.ID_CITA
    INNER JOIN MASCOTA     M ON C.ID_MASCOTA      = M.ID_MASCOTA
    INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    INNER JOIN SERVICIO    S ON C.ID_SERVICIO    = S.ID_SERVICIO
    WHERE AM.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_ATENCION_MEDICA
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DECLARE @ID_CITA INT;
        SELECT @ID_CITA = ID_CITA FROM ATENCION_MEDICA WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        DELETE FROM MEDICAMENTO_RECETADO WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        DELETE FROM INSTRUMENTO_USADO    WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        DELETE FROM HISTORIAL_MEDICO     WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        DELETE FROM ATENCION_MEDICA      WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        IF @ID_CITA IS NOT NULL
            UPDATE CITA SET ESTADO = 'PENDIENTE' WHERE ID_CITA = @ID_CITA;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO

CREATE OR ALTER PROCEDURE SP_VERIFICAR_ATENCION_MASCOTA
    @ID_CITA    INT,
    @ID_MASCOTA INT
AS
BEGIN
    SELECT CASE WHEN EXISTS (
        SELECT 1 
        FROM ATENCION_MEDICA AM
        INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
        WHERE AM.ID_CITA = @ID_CITA AND C.ID_MASCOTA = @ID_MASCOTA
    ) THEN 1 ELSE 0 END AS ATENDIDA;
END;
GO

CREATE PROCEDURE SP_OBTENER_FICHA_MEDICA
    @ID_MASCOTA INT
AS
BEGIN
    SELECT ID_FICHA, ID_MASCOTA, ALERGIAS, ENFERMEDADES_CRONICAS,
           OBSERVACIONES, ULTIMA_ACTUALIZACION
    FROM FICHA_MEDICA
    WHERE ID_MASCOTA = @ID_MASCOTA;
END;
GO

CREATE OR ALTER PROCEDURE SP_PREPARAR_COBRO_ATENCION
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    -- 1. Traer el Servicio Base
    SELECT S.NOMBRE_SERVICIO AS ITEM, S.PRECIO, 'SERVICIO' AS TIPO
    FROM ATENCION_MEDICA AM
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN SERVICIO S ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE AM.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA
    
    UNION ALL

    -- 2. Traer Medicamentos
    SELECT M.NOMBRE, M.PRECIO, 'MEDICAMENTO'
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA

    UNION ALL

    -- 3. Traer Instrumentos
    SELECT I.NOMBRE, I.COSTO_USO, 'INSTRUMENTO'
    FROM INSTRUMENTO_USADO IU
    INNER JOIN INSTRUMENTO_MEDICO I ON IU.ID_INSTRUMENTO = I.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
END;
GO
-- ════════════════════════════════════════════════════════════
--  INSTRUMENTOS MÉDICOS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_INSTRUMENTOS_DISPONIBLES
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_INSTRUMENTO, NOMBRE, DESCRIPCION, COSTO_USO
    FROM INSTRUMENTO_MEDICO WHERE ESTADO = 1;
END;
GO

CREATE PROCEDURE SP_OBTENER_INSTRUMENTO_POR_ID
    @ID_INSTRUMENTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_INSTRUMENTO, NOMBRE, DESCRIPCION, COSTO_USO
    FROM INSTRUMENTO_MEDICO WHERE ID_INSTRUMENTO = @ID_INSTRUMENTO;
END;
GO

CREATE PROCEDURE SP_INSERTAR_INSTRUMENTO_USADO
    @ID_ATENCION_MEDICA INT,
    @ID_INSTRUMENTO     INT
AS
BEGIN
    INSERT INTO INSTRUMENTO_USADO (ID_ATENCION_MEDICA, ID_INSTRUMENTO)
    VALUES (@ID_ATENCION_MEDICA, @ID_INSTRUMENTO);
END;
GO

CREATE PROCEDURE SP_OBTENER_INSTRUMENTOS_POR_ATENCION
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT IM.NOMBRE, IM.COSTO_USO
    FROM INSTRUMENTO_USADO    IU
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
END;
GO

CREATE PROCEDURE SP_OBTENER_ULTIMO_INSTRUMENTO_USADO
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 1 ID_INSTRUMENTO_USADO
    FROM INSTRUMENTO_USADO
    WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA
    ORDER BY ID_INSTRUMENTO_USADO DESC;
END;
GO

-- ════════════════════════════════════════════════════════════
--  MEDICAMENTOS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_MEDICAMENTOS_DISPONIBLES
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_MEDICAMENTO, NOMBRE, DESCRIPCION, PRECIO
    FROM MEDICAMENTO WHERE ESTADO = 1;
END;
GO

CREATE PROCEDURE SP_OBTENER_MEDICAMENTO_POR_ID
    @ID_MEDICAMENTO INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT ID_MEDICAMENTO, NOMBRE, DESCRIPCION, PRECIO
    FROM MEDICAMENTO WHERE ID_MEDICAMENTO = @ID_MEDICAMENTO;
END;
GO

CREATE PROCEDURE SP_INSERTAR_MEDICAMENTO_RECETADO
    @ID_ATENCION_MEDICA INT,
    @ID_MEDICAMENTO     INT,
    @DOSIS              VARCHAR(50),
    @FRECUENCIA         VARCHAR(50),
    @DURACION           VARCHAR(50)
AS
BEGIN
    INSERT INTO MEDICAMENTO_RECETADO
        (ID_ATENCION_MEDICA, ID_MEDICAMENTO, DOSIS, FRECUENCIA, DURACION)
    VALUES
        (@ID_ATENCION_MEDICA, @ID_MEDICAMENTO, @DOSIS, @FRECUENCIA, @DURACION);
END;
GO

CREATE PROCEDURE SP_OBTENER_MEDICAMENTOS_POR_ATENCION
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MED.NOMBRE, MR.DOSIS, MR.FRECUENCIA, MR.DURACION, MED.PRECIO
    FROM MEDICAMENTO_RECETADO MR
    INNER JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
    WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
END;
GO

CREATE PROCEDURE SP_OBTENER_ULTIMO_MEDICAMENTO_RECETADO
    @ID_ATENCION_MEDICA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 1 ID_MEDICAMENTO_RECETADO
    FROM MEDICAMENTO_RECETADO
    WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA
    ORDER BY ID_MEDICAMENTO_RECETADO DESC;
END;
GO
