-- ============================================================
--  MÓDULO 5 | SPs de Servicios y Facturas
-- ============================================================
USE DB_VidaAnimal;
GO

-- ════════════════════════════════════════════════════════════
--  SERVICIOS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_SERVICIOS
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO ORDER BY NOMBRE_SERVICIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_SERVICIOS_ACTIVOS
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA
    FROM SERVICIO WHERE ESTADO = 1 ORDER BY NOMBRE_SERVICIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_SERVICIO_POR_ID
    @ID_SERVICIO INT
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO WHERE ID_SERVICIO = @ID_SERVICIO;
END;
GO

CREATE PROCEDURE SP_INSERTAR_SERVICIO
    @NOMBRE_SERVICIO  VARCHAR(50),
    @DESCRIPCION      VARCHAR(255),
    @PRECIO           DECIMAL(10,2),
    @DURACION_ESTIMADA INT,
    @ESTADO           BIT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = @NOMBRE_SERVICIO)
    BEGIN
        INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
        VALUES (@NOMBRE_SERVICIO, @DESCRIPCION, @PRECIO, @DURACION_ESTIMADA, @ESTADO);
        SELECT SCOPE_IDENTITY() AS ID_SERVICIO;
    END
    ELSE
        SELECT -1 AS ID_SERVICIO;  -- ya existe
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_SERVICIO
    @ID_SERVICIO       INT,
    @NOMBRE_SERVICIO   VARCHAR(50),
    @DESCRIPCION       VARCHAR(255),
    @PRECIO            DECIMAL(10,2),
    @DURACION_ESTIMADA INT,
    @ESTADO            BIT
AS
BEGIN
    BEGIN TRY
        IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE ID_SERVICIO = @ID_SERVICIO)
        BEGIN SELECT 0 AS FILAS_AFECTADAS; RETURN; END

        IF EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = @NOMBRE_SERVICIO AND ID_SERVICIO <> @ID_SERVICIO)
        BEGIN SELECT -1 AS FILAS_AFECTADAS; RETURN; END  -- nombre en uso

        UPDATE SERVICIO
        SET NOMBRE_SERVICIO = @NOMBRE_SERVICIO, DESCRIPCION = @DESCRIPCION,
            PRECIO = @PRECIO, DURACION_ESTIMADA = @DURACION_ESTIMADA, ESTADO = @ESTADO
        WHERE ID_SERVICIO = @ID_SERVICIO;
        SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
    END TRY
    BEGIN CATCH
        SELECT 0 AS FILAS_AFECTADAS;
    END CATCH
END;
GO

CREATE PROCEDURE SP_CAMBIAR_ESTADO_SERVICIO
    @ID_SERVICIO INT,
    @ESTADO      BIT
AS
BEGIN
    UPDATE SERVICIO SET ESTADO = @ESTADO WHERE ID_SERVICIO = @ID_SERVICIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_SERVICIO_COMPLETO
    @ID_SERVICIO INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO = @ID_SERVICIO;
        DELETE FROM SERVICIO             WHERE ID_SERVICIO = @ID_SERVICIO;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_ASIGNAR_VETERINARIO_SERVICIO
    @ID_SERVICIO    INT,
    @ID_VETERINARIO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO_VETERINARIO
                   WHERE ID_SERVICIO = @ID_SERVICIO AND ID_VETERINARIO = @ID_VETERINARIO)
    BEGIN
        INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
        VALUES (@ID_SERVICIO, @ID_VETERINARIO);
        SELECT 1 AS RESULTADO;
    END
    ELSE
        SELECT 0 AS RESULTADO;
END;
GO

CREATE PROCEDURE SP_ASIGNAR_MULTIPLES_VETERINARIOS
    @ID_SERVICIO      INT,
    @IDS_VETERINARIOS VARCHAR(MAX)
AS
BEGIN
    DECLARE @TEMP TABLE (ID_VETERINARIO INT);
    INSERT INTO @TEMP SELECT value FROM STRING_SPLIT(@IDS_VETERINARIOS, ',');
    INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
    SELECT @ID_SERVICIO, ID_VETERINARIO FROM @TEMP T
    WHERE NOT EXISTS (
        SELECT 1 FROM SERVICIO_VETERINARIO
        WHERE ID_SERVICIO = @ID_SERVICIO AND ID_VETERINARIO = T.ID_VETERINARIO
    );
    SELECT @@ROWCOUNT AS ASIGNACIONES_REALIZADAS;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_ASIGNACION_VETERINARIO
    @ID_SERVICIO_VETERINARIO INT
AS
BEGIN
    DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO_VETERINARIO = @ID_SERVICIO_VETERINARIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO
CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_POR_SERVICIO
    @ID_SERVICIO INT
AS
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA,  
        V.NOMBRE, 
        V.APELLIDO,  
        V.TELEFONO,
        V.ID_ESPECIALIDAD AS ID_ESPECIALIDAD,
        E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD,
        SV.FECHA_ASIGNACION 
    FROM SERVICIO_VETERINARIO SV 
    INNER JOIN VETERINARIO V ON SV.ID_VETERINARIO = V.ID_VETERINARIO 
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD 
    WHERE SV.ID_SERVICIO = @ID_SERVICIO 
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO
CREATE OR ALTER PROCEDURE SP_OBTENER_VETERINARIOS_NO_ASIGNADOS
    @ID_SERVICIO INT
AS
BEGIN
    SELECT 
        V.ID_VETERINARIO, 
        V.CEDULA, 
        V.NOMBRE, 
        V.APELLIDO,
        V.TELEFONO,
        V.ID_ESPECIALIDAD,
        E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD 
    FROM VETERINARIO V 
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD 
    WHERE V.ID_VETERINARIO NOT IN ( 
        SELECT ID_VETERINARIO  
        FROM SERVICIO_VETERINARIO  
        WHERE ID_SERVICIO = @ID_SERVICIO 
    ) 
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE PROCEDURE SP_OBTENER_SERVICIOS_POR_VETERINARIO
    @ID_VETERINARIO INT
AS
BEGIN
    SELECT SV.ID_SERVICIO_VETERINARIO, S.ID_SERVICIO, S.NOMBRE_SERVICIO
    FROM SERVICIO_VETERINARIO SV
    INNER JOIN SERVICIO S ON SV.ID_SERVICIO = S.ID_SERVICIO
    WHERE SV.ID_VETERINARIO = @ID_VETERINARIO
    ORDER BY S.NOMBRE_SERVICIO;
END;
GO
-- ════════════════════════════════════════════════════════════
--  FACTURAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_FACTURAS_POR_CEDULA
    @CEDULA_CLIENTE VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT F.ID_FACTURA, F.FECHA, F.SUBTOTAL, F.IVA, F.TOTAL, F.ESTADO,
           MP.METODO, MP.VALOR_TOTAL, MP.CUENTA_ORIGEN, MP.CUENTA_DESTINO,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
           C.CEDULA AS CEDULA_CLIENTE, C.TELEFONO AS TELEFONO_CLIENTE,
           C.DIRECCION AS DIRECCION_CLIENTE, C.CORREO_ELECTRONICO AS EMAIL_CLIENTE
    FROM FACTURA F
    INNER JOIN CLIENTE     C  ON F.ID_CLIENTE     = C.ID_CLIENTE
    INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE C.CEDULA = @CEDULA_CLIENTE
    ORDER BY F.FECHA DESC;
END;
GO

CREATE OR ALTER PROCEDURE SP_OBTENER_DETALLE_FACTURA
    @ID_FACTURA INT
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Datos del cliente y factura - DEVOLVER FECHA COMO DATETIME
    SELECT TOP 1
        F.ID_FACTURA,
        F.FECHA,  -- ← Cambiado: enviar como DATETIME, no como VARCHAR
        F.SUBTOTAL,
        F.IVA,
        F.TOTAL,
        F.ESTADO,
        MP.METODO AS METODO_PAGO,
        C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
        C.CEDULA,
        C.TELEFONO,
        C.DIRECCION,
        C.CORREO_ELECTRONICO
    FROM FACTURA F 
    INNER JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
    INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE F.ID_FACTURA = @ID_FACTURA;

    -- 2. Servicios (solo el servicio principal, no medicamentos ni instrumentos)
    SELECT TOP 1
        S.NOMBRE_SERVICIO,
        ISNULL(S.DESCRIPCION, '') AS DESCRIPCION_SERVICIO,
        DF.PRECIO_UNITARIO,
        DF.TOTAL AS TOTAL_SERVICIO,
        ISNULL(V.NOMBRE + ' ' + V.APELLIDO, 'No asignado') AS VETERINARIO
    FROM DETALLE_FACTURA DF
    INNER JOIN SERVICIO S ON DF.ID_SERVICIO = S.ID_SERVICIO
    LEFT JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    LEFT JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    LEFT JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
    WHERE DF.ID_FACTURA = @ID_FACTURA
      AND S.NOMBRE_SERVICIO NOT IN ('MEDICAMENTO', 'INSTRUMENTO');

    -- 3. Mascotas
    SELECT DISTINCT
        M.NOMBRE AS NOMBRE_MASCOTA,
        ISNULL(M.ESPECIE, '') AS ESPECIE,
        ISNULL(M.RAZA, '') AS RAZA,
        ISNULL(CAST(AM.DIAGNOSTICO AS VARCHAR(MAX)), '') AS DIAGNOSTICO,
        ISNULL(CAST(AM.TRATAMIENTO AS VARCHAR(MAX)), '') AS TRATAMIENTO
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 4. Medicamentos
    SELECT DISTINCT
        MED.NOMBRE AS MEDICAMENTO,
        MED.PRECIO,
        ISNULL(MR.DOSIS, '') AS DOSIS,
        ISNULL(MR.FRECUENCIA, '') AS FRECUENCIA,
        ISNULL(MR.DURACION, '') AS DURACION
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO_RECETADO MR ON AM.ID_ATENCION_MEDICA = MR.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 5. Instrumentos
    SELECT DISTINCT
        IM.NOMBRE AS INSTRUMENTO,
        IM.COSTO_USO
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_USADO IU ON AM.ID_ATENCION_MEDICA = IU.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 6. Vacunas aplicadas
    SELECT DISTINCT
        VA.NOMBRE AS NOMBRE_VACUNA,
        ISNULL(VA.DESCRIPCION, '') AS DESCRIPCION,
        VA.FECHA_APLICACION,
        VA.FECHA_PROXIMA
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
    INNER JOIN MASCOTA M ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN VACUNA_APLICADA VA ON M.ID_MASCOTA = VA.ID_MASCOTA
    WHERE DF.ID_FACTURA = @ID_FACTURA;
END;
GO
CREATE OR ALTER PROCEDURE SP_GENERAR_FACTURA_ATENCION
    @ID_ATENCION_MEDICA INT,
    @METODO             VARCHAR(255),
    @CUENTA_ORIGEN      VARCHAR(20) = NULL,
    @CUENTA_DESTINO     VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @ID_CLIENTE INT, @ID_SERVICIO INT, @ID_MASCOTA INT,
            @PRECIO_SERVICIO DECIMAL(10,2), @SUBTOTAL DECIMAL(10,2),
            @IVA DECIMAL(10,2), @TOTAL DECIMAL(10,2),
            @ID_FACTURA INT, @ID_METODO_PAGO INT,
            @ID_SERVICIO_MED INT, @ID_SERVICIO_INSTR INT,
            @ID_CITA INT;
    
    BEGIN TRY
        BEGIN TRANSACTION;

        -- Obtener ID_CITA primero
        SELECT @ID_CITA = ID_CITA 
        FROM ATENCION_MEDICA 
        WHERE ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        
        IF @ID_CITA IS NULL
        BEGIN
            RAISERROR('No existe la atención médica con ID: %d', 16, 1, @ID_ATENCION_MEDICA);
        END

        -- Obtener datos de la cita
        SELECT @ID_CLIENTE = ID_CLIENTE,
               @ID_SERVICIO = ID_SERVICIO,
               @ID_MASCOTA = ID_MASCOTA
        FROM CITA 
        WHERE ID_CITA = @ID_CITA;
        
        -- Obtener precio del servicio
        SELECT @PRECIO_SERVICIO = ISNULL(PRECIO, 0)
        FROM SERVICIO 
        WHERE ID_SERVICIO = @ID_SERVICIO;

        -- Verificar que se obtuvieron los datos
        IF @ID_CLIENTE IS NULL
        BEGIN
            RAISERROR('No se encontró el cliente para la cita ID: %d', 16, 1, @ID_CITA);
        END

        IF @ID_SERVICIO IS NULL
        BEGIN
            RAISERROR('No se encontró el servicio para la cita ID: %d', 16, 1, @ID_CITA);
        END

        -- Obtener IDs auxiliares para servicios de medicamentos e instrumentos
        SELECT @ID_SERVICIO_MED = ID_SERVICIO FROM SERVICIO WHERE NOMBRE_SERVICIO = 'MEDICAMENTO';
        SELECT @ID_SERVICIO_INSTR = ID_SERVICIO FROM SERVICIO WHERE NOMBRE_SERVICIO = 'INSTRUMENTO';
        
        IF @ID_SERVICIO_MED IS NULL
        BEGIN
            INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
            VALUES ('MEDICAMENTO', 'Medicamentos recetados', 0, 0, 1);
            SET @ID_SERVICIO_MED = SCOPE_IDENTITY();
        END
        
        IF @ID_SERVICIO_INSTR IS NULL
        BEGIN
            INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
            VALUES ('INSTRUMENTO', 'Instrumentos utilizados', 0, 0, 1);
            SET @ID_SERVICIO_INSTR = SCOPE_IDENTITY();
        END

        -- Calcular SUBTOTAL (inicia con el precio del servicio)
        SET @SUBTOTAL = ISNULL(@PRECIO_SERVICIO, 0);
        
        -- Sumar medicamentos
        SELECT @SUBTOTAL = @SUBTOTAL + ISNULL(SUM(M.PRECIO), 0)
        FROM MEDICAMENTO_RECETADO MR
        INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
        WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        
        -- Sumar instrumentos
        SELECT @SUBTOTAL = @SUBTOTAL + ISNULL(SUM(IM.COSTO_USO), 0)
        FROM INSTRUMENTO_USADO IU
        INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
        WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;
        
        -- Calcular IVA (12%) y TOTAL
        SET @IVA = @SUBTOTAL * 0.12;
        SET @TOTAL = @SUBTOTAL + @IVA;

        -- Insertar Pago
        INSERT INTO METODO_PAGO (METODO, VALOR_TOTAL, CUENTA_ORIGEN, CUENTA_DESTINO)
        VALUES (@METODO, @TOTAL, @CUENTA_ORIGEN, @CUENTA_DESTINO);
        SET @ID_METODO_PAGO = SCOPE_IDENTITY();

        -- Insertar Factura
        INSERT INTO FACTURA (ID_CLIENTE, SUBTOTAL, IVA, TOTAL, ESTADO, ID_METODO_PAGO)
        VALUES (@ID_CLIENTE, @SUBTOTAL, @IVA, @TOTAL, 'PAGADA', @ID_METODO_PAGO);
        SET @ID_FACTURA = SCOPE_IDENTITY();

        -- Detalle: Servicio Principal
        INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
        VALUES (@ID_FACTURA, @ID_SERVICIO, 1, @PRECIO_SERVICIO, @PRECIO_SERVICIO, @ID_ATENCION_MEDICA);

        -- Detalle: Medicamentos
        INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
        SELECT @ID_FACTURA, @ID_SERVICIO_MED, 1, M.PRECIO, M.PRECIO, @ID_ATENCION_MEDICA
        FROM MEDICAMENTO_RECETADO MR
        INNER JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
        WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        -- Detalle: Instrumentos
        INSERT INTO DETALLE_FACTURA (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_ATENCION_MEDICA)
        SELECT @ID_FACTURA, @ID_SERVICIO_INSTR, 1, IM.COSTO_USO, IM.COSTO_USO, @ID_ATENCION_MEDICA
        FROM INSTRUMENTO_USADO IU
        INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
        WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        COMMIT TRANSACTION;
        SELECT @ID_FACTURA AS ID_FACTURA;
        RETURN;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        
        SELECT 
            -1 AS ID_FACTURA,
            ERROR_MESSAGE() AS ERROR_MENSAJE,
            ERROR_NUMBER() AS ERROR_NUMERO,
            ERROR_LINE() AS ERROR_LINEA;
        
        PRINT 'ERROR EN SP_GENERAR_FACTURA_ATENCION:';
        PRINT 'Mensaje: ' + ERROR_MESSAGE();
        PRINT 'Número: ' + CAST(ERROR_NUMBER() AS VARCHAR);
        PRINT 'Línea: ' + CAST(ERROR_LINE() AS VARCHAR);
    END CATCH
END;
GO
