-- ============================================================
--  MÓDULO 5 | SPs de Servicios y Facturas
-- ============================================================
USE DB_VidaAnimal;
GO

-- ════════════════════════════════════════════════════════════
--  SERVICIOS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_SERVICIOS
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO ORDER BY NOMBRE_SERVICIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_SERVICIOS_ACTIVOS
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA
    FROM SERVICIO WHERE ESTADO = 1 ORDER BY NOMBRE_SERVICIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_SERVICIO_POR_ID
    @ID_SERVICIO INT
AS
BEGIN
    SELECT ID_SERVICIO, NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO
    FROM SERVICIO WHERE ID_SERVICIO = @ID_SERVICIO;
END;
GO

CREATE PROCEDURE SP_INSERTAR_SERVICIO
    @NOMBRE_SERVICIO  VARCHAR(50),
    @DESCRIPCION      VARCHAR(255),
    @PRECIO           DECIMAL(10,2),
    @DURACION_ESTIMADA INT,
    @ESTADO           BIT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = @NOMBRE_SERVICIO)
    BEGIN
        INSERT INTO SERVICIO (NOMBRE_SERVICIO, DESCRIPCION, PRECIO, DURACION_ESTIMADA, ESTADO)
        VALUES (@NOMBRE_SERVICIO, @DESCRIPCION, @PRECIO, @DURACION_ESTIMADA, @ESTADO);
        SELECT SCOPE_IDENTITY() AS ID_SERVICIO;
    END
    ELSE
        SELECT -1 AS ID_SERVICIO;  -- ya existe
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_SERVICIO
    @ID_SERVICIO       INT,
    @NOMBRE_SERVICIO   VARCHAR(50),
    @DESCRIPCION       VARCHAR(255),
    @PRECIO            DECIMAL(10,2),
    @DURACION_ESTIMADA INT,
    @ESTADO            BIT
AS
BEGIN
    BEGIN TRY
        IF NOT EXISTS (SELECT 1 FROM SERVICIO WHERE ID_SERVICIO = @ID_SERVICIO)
        BEGIN SELECT 0 AS FILAS_AFECTADAS; RETURN; END

        IF EXISTS (SELECT 1 FROM SERVICIO WHERE NOMBRE_SERVICIO = @NOMBRE_SERVICIO AND ID_SERVICIO <> @ID_SERVICIO)
        BEGIN SELECT -1 AS FILAS_AFECTADAS; RETURN; END  -- nombre en uso

        UPDATE SERVICIO
        SET NOMBRE_SERVICIO = @NOMBRE_SERVICIO, DESCRIPCION = @DESCRIPCION,
            PRECIO = @PRECIO, DURACION_ESTIMADA = @DURACION_ESTIMADA, ESTADO = @ESTADO
        WHERE ID_SERVICIO = @ID_SERVICIO;
        SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
    END TRY
    BEGIN CATCH
        SELECT 0 AS FILAS_AFECTADAS;
    END CATCH
END;
GO

CREATE PROCEDURE SP_CAMBIAR_ESTADO_SERVICIO
    @ID_SERVICIO INT,
    @ESTADO      BIT
AS
BEGIN
    UPDATE SERVICIO SET ESTADO = @ESTADO WHERE ID_SERVICIO = @ID_SERVICIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_SERVICIO_COMPLETO
    @ID_SERVICIO INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO = @ID_SERVICIO;
        DELETE FROM SERVICIO             WHERE ID_SERVICIO = @ID_SERVICIO;
        COMMIT TRANSACTION;
        SELECT 1 AS RESULTADO;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_ASIGNAR_VETERINARIO_SERVICIO
    @ID_SERVICIO    INT,
    @ID_VETERINARIO INT
AS
BEGIN
    IF NOT EXISTS (SELECT 1 FROM SERVICIO_VETERINARIO
                   WHERE ID_SERVICIO = @ID_SERVICIO AND ID_VETERINARIO = @ID_VETERINARIO)
    BEGIN
        INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
        VALUES (@ID_SERVICIO, @ID_VETERINARIO);
        SELECT 1 AS RESULTADO;
    END
    ELSE
        SELECT 0 AS RESULTADO;
END;
GO

CREATE PROCEDURE SP_ASIGNAR_MULTIPLES_VETERINARIOS
    @ID_SERVICIO      INT,
    @IDS_VETERINARIOS VARCHAR(MAX)
AS
BEGIN
    DECLARE @TEMP TABLE (ID_VETERINARIO INT);
    INSERT INTO @TEMP SELECT value FROM STRING_SPLIT(@IDS_VETERINARIOS, ',');
    INSERT INTO SERVICIO_VETERINARIO (ID_SERVICIO, ID_VETERINARIO)
    SELECT @ID_SERVICIO, ID_VETERINARIO FROM @TEMP T
    WHERE NOT EXISTS (
        SELECT 1 FROM SERVICIO_VETERINARIO
        WHERE ID_SERVICIO = @ID_SERVICIO AND ID_VETERINARIO = T.ID_VETERINARIO
    );
    SELECT @@ROWCOUNT AS ASIGNACIONES_REALIZADAS;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_ASIGNACION_VETERINARIO
    @ID_SERVICIO_VETERINARIO INT
AS
BEGIN
    DELETE FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO_VETERINARIO = @ID_SERVICIO_VETERINARIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_OBTENER_VETERINARIOS_POR_SERVICIO
    @ID_SERVICIO INT
AS
BEGIN
    SELECT SV.ID_SERVICIO_VETERINARIO, V.ID_VETERINARIO, V.CEDULA,
           V.NOMBRE, V.APELLIDO,
           E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD, SV.FECHA_ASIGNACION
    FROM SERVICIO_VETERINARIO SV
    INNER JOIN VETERINARIO V ON SV.ID_VETERINARIO = V.ID_VETERINARIO
    LEFT  JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE SV.ID_SERVICIO = @ID_SERVICIO
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

CREATE PROCEDURE SP_OBTENER_VETERINARIOS_NO_ASIGNADOS
    @ID_SERVICIO INT
AS
BEGIN
    SELECT V.ID_VETERINARIO, V.CEDULA, V.NOMBRE, V.APELLIDO,
           E.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD
    FROM VETERINARIO V
    LEFT JOIN ESPECIALIDAD_VETERINARIA E ON V.ID_ESPECIALIDAD = E.ID_ESPECIALIDAD
    WHERE V.ID_VETERINARIO NOT IN (
        SELECT ID_VETERINARIO FROM SERVICIO_VETERINARIO WHERE ID_SERVICIO = @ID_SERVICIO
    )
    ORDER BY V.NOMBRE, V.APELLIDO;
END;
GO

-- ════════════════════════════════════════════════════════════
--  FACTURAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_FACTURAS_POR_CEDULA
    @CEDULA_CLIENTE VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT F.ID_FACTURA, F.FECHA, F.SUBTOTAL, F.IVA, F.TOTAL, F.ESTADO,
           MP.METODO, MP.VALOR_TOTAL, MP.CUENTA_ORIGEN, MP.CUENTA_DESTINO,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
           C.CEDULA AS CEDULA_CLIENTE, C.TELEFONO AS TELEFONO_CLIENTE,
           C.DIRECCION AS DIRECCION_CLIENTE, C.CORREO_ELECTRONICO AS EMAIL_CLIENTE
    FROM FACTURA F
    INNER JOIN CLIENTE     C  ON F.ID_CLIENTE     = C.ID_CLIENTE
    INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE C.CEDULA = @CEDULA_CLIENTE
    ORDER BY F.FECHA DESC;
END;
GO

CREATE PROCEDURE SP_OBTENER_DETALLE_FACTURA
    @ID_FACTURA INT
AS
BEGIN
    SET NOCOUNT ON;

    -- 1. Datos del cliente
    SELECT C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
           C.CEDULA, C.TELEFONO, C.DIRECCION, C.CORREO_ELECTRONICO, F.ID_FACTURA
    FROM FACTURA F INNER JOIN CLIENTE C ON F.ID_CLIENTE = C.ID_CLIENTE
    WHERE F.ID_FACTURA = @ID_FACTURA;

    -- 2. Datos de la factura y método de pago
    SELECT F.ID_FACTURA, F.FECHA, F.SUBTOTAL, F.IVA, F.TOTAL, F.ESTADO,
           MP.METODO, MP.VALOR_TOTAL, MP.CUENTA_ORIGEN, MP.CUENTA_DESTINO
    FROM FACTURA F INNER JOIN METODO_PAGO MP ON F.ID_METODO_PAGO = MP.ID_METODO_PAGO
    WHERE F.ID_FACTURA = @ID_FACTURA;

    -- 3. Detalle de servicios
    SELECT DISTINCT DF.ID_DETALLE, S.NOMBRE_SERVICIO, S.DESCRIPCION AS DESCRIPCION_SERVICIO,
           DF.CANTIDAD, DF.PRECIO_UNITARIO, DF.DESCUENTO, DF.TOTAL AS TOTAL_SERVICIO,
           DF.ID_ATENCION_MEDICA, DF.ID_MASCOTA,
           V.NOMBRE + ' ' + V.APELLIDO AS VETERINARIO,
           EV.NOMBRE_ESPECIALIDAD AS ESPECIALIDAD
    FROM DETALLE_FACTURA DF
    INNER JOIN SERVICIO               S  ON DF.ID_SERVICIO           = S.ID_SERVICIO
    INNER JOIN ATENCION_MEDICA        AM ON DF.ID_ATENCION_MEDICA    = AM.ID_ATENCION_MEDICA
    INNER JOIN SERVICIO_VETERINARIO   SV ON S.ID_SERVICIO            = SV.ID_SERVICIO
    INNER JOIN VETERINARIO            V  ON SV.ID_VETERINARIO        = V.ID_VETERINARIO
    INNER JOIN ESPECIALIDAD_VETERINARIA EV ON V.ID_ESPECIALIDAD      = EV.ID_ESPECIALIDAD
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 4. Mascotas atendidas
    SELECT M.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA, M.SEXO,
           M.FECHA_NACIMIENTO, M.PESO, M.COLOR,
           CAST(AM.DIAGNOSTICO  AS NVARCHAR(MAX)) AS DIAGNOSTICO,
           CAST(AM.TRATAMIENTO  AS NVARCHAR(MAX)) AS TRATAMIENTO,
           CAST(AM.OBSERVACIONES AS NVARCHAR(MAX)) AS OBSERVACIONES_ATENCION,
           AM.FECHA AS FECHA_ATENCION
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN MASCOTA         M  ON AM.ID_MASCOTA        = M.ID_MASCOTA
    WHERE DF.ID_FACTURA = @ID_FACTURA
    GROUP BY M.ID_MASCOTA, M.NOMBRE, M.ESPECIE, M.RAZA, M.SEXO,
             M.FECHA_NACIMIENTO, M.PESO, M.COLOR,
             CAST(AM.DIAGNOSTICO AS NVARCHAR(MAX)),
             CAST(AM.TRATAMIENTO AS NVARCHAR(MAX)),
             CAST(AM.OBSERVACIONES AS NVARCHAR(MAX)), AM.FECHA;

    -- 5. Medicamentos recetados
    SELECT DISTINCT MED.NOMBRE AS MEDICAMENTO, MED.DESCRIPCION, MED.PRECIO,
           MR.DOSIS, MR.FRECUENCIA, MR.DURACION
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA      AM  ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO_RECETADO MR  ON AM.ID_ATENCION_MEDICA = MR.ID_ATENCION_MEDICA
    INNER JOIN MEDICAMENTO          MED ON MR.ID_MEDICAMENTO     = MED.ID_MEDICAMENTO
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 6. Instrumentos usados
    SELECT DISTINCT IM.NOMBRE AS INSTRUMENTO, IM.DESCRIPCION, IM.COSTO_USO
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA    AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_USADO  IU ON AM.ID_ATENCION_MEDICA = IU.ID_ATENCION_MEDICA
    INNER JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO     = IM.ID_INSTRUMENTO
    WHERE DF.ID_FACTURA = @ID_FACTURA;

    -- 7. Vacunas aplicadas
    SELECT DISTINCT M.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA,
           VA.ID_VACUNA, VA.NOMBRE AS NOMBRE_VACUNA, VA.DESCRIPCION,
           VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM DETALLE_FACTURA DF
    INNER JOIN ATENCION_MEDICA AM ON DF.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    INNER JOIN MASCOTA         M  ON AM.ID_MASCOTA         = M.ID_MASCOTA
    INNER JOIN VACUNA_APLICADA VA ON M.ID_MASCOTA          = VA.ID_MASCOTA
    WHERE DF.ID_FACTURA = @ID_FACTURA
    ORDER BY M.ID_MASCOTA, VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_GENERAR_FACTURA_ATENCION
    @ID_ATENCION_MEDICA INT,
    @METODO             VARCHAR(255),
    @CUENTA_ORIGEN      VARCHAR(20) = NULL,
    @CUENTA_DESTINO     VARCHAR(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @ID_CLIENTE      INT, @ID_SERVICIO    INT,
                @PRECIO_SERVICIO DECIMAL(10,2), @SUBTOTAL DECIMAL(10,2),
                @IVA             DECIMAL(10,2), @TOTAL    DECIMAL(10,2),
                @ID_FACTURA      INT,           @ID_METODO_PAGO INT,
                @ID_MASCOTA      INT,           @ID_CITA  INT;

        SELECT @ID_CLIENTE  = C.ID_CLIENTE,
               @ID_SERVICIO = C.ID_SERVICIO,
               @ID_MASCOTA  = AM.ID_MASCOTA,
               @ID_CITA     = AM.ID_CITA
        FROM ATENCION_MEDICA AM
        INNER JOIN CITA C ON AM.ID_CITA = C.ID_CITA
        WHERE AM.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        SELECT @PRECIO_SERVICIO = PRECIO FROM SERVICIO WHERE ID_SERVICIO = @ID_SERVICIO;

        SET @SUBTOTAL = @PRECIO_SERVICIO
            + ISNULL((SELECT SUM(M.PRECIO)
                      FROM MEDICAMENTO_RECETADO MR
                      JOIN MEDICAMENTO M ON MR.ID_MEDICAMENTO = M.ID_MEDICAMENTO
                      WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA), 0)
            + ISNULL((SELECT SUM(IM.COSTO_USO)
                      FROM INSTRUMENTO_USADO IU
                      JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
                      WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA), 0);

        SET @IVA   = @SUBTOTAL * 0.12;
        SET @TOTAL = @SUBTOTAL + @IVA;

        INSERT INTO METODO_PAGO (METODO, VALOR_TOTAL, CUENTA_ORIGEN, CUENTA_DESTINO)
        VALUES (@METODO, @TOTAL,
                CASE WHEN @METODO = 'TRANSFERENCIA BANCARIA' THEN @CUENTA_ORIGEN  ELSE NULL END,
                CASE WHEN @METODO = 'TRANSFERENCIA BANCARIA' THEN @CUENTA_DESTINO ELSE NULL END);
        SET @ID_METODO_PAGO = SCOPE_IDENTITY();

        INSERT INTO FACTURA (ID_CLIENTE, SUBTOTAL, IVA, TOTAL, ESTADO, ID_METODO_PAGO)
        VALUES (@ID_CLIENTE, @SUBTOTAL, @IVA, @TOTAL, 'PAGADA', @ID_METODO_PAGO);
        SET @ID_FACTURA = SCOPE_IDENTITY();

        -- Detalle: servicio principal
        INSERT INTO DETALLE_FACTURA
            (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, TOTAL, ID_ATENCION_MEDICA, ID_MASCOTA)
        SELECT @ID_FACTURA, @ID_SERVICIO, 1, @PRECIO_SERVICIO, 0, @PRECIO_SERVICIO,
               AM.ID_ATENCION_MEDICA, AM.ID_MASCOTA
        FROM ATENCION_MEDICA AM WHERE AM.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        -- Detalle: medicamentos
        INSERT INTO DETALLE_FACTURA
            (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, TOTAL, ID_ATENCION_MEDICA, ID_MASCOTA)
        SELECT @ID_FACTURA, @ID_SERVICIO, 1, M.PRECIO, 0, M.PRECIO,
               MR.ID_ATENCION_MEDICA, AM.ID_MASCOTA
        FROM MEDICAMENTO_RECETADO MR
        JOIN MEDICAMENTO       M  ON MR.ID_MEDICAMENTO     = M.ID_MEDICAMENTO
        JOIN ATENCION_MEDICA   AM ON MR.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
        WHERE MR.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        -- Detalle: instrumentos
        INSERT INTO DETALLE_FACTURA
            (ID_FACTURA, ID_SERVICIO, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, TOTAL, ID_ATENCION_MEDICA, ID_MASCOTA)
        SELECT @ID_FACTURA, @ID_SERVICIO, 1, IM.COSTO_USO, 0, IM.COSTO_USO,
               IU.ID_ATENCION_MEDICA, AM.ID_MASCOTA
        FROM INSTRUMENTO_USADO    IU
        JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO     = IM.ID_INSTRUMENTO
        JOIN ATENCION_MEDICA    AM ON IU.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
        WHERE IU.ID_ATENCION_MEDICA = @ID_ATENCION_MEDICA;

        COMMIT TRANSACTION;
        SELECT @ID_FACTURA AS ID_FACTURA;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO
