-- ============================================================
--  MÓDULO 6 | SPs de Vacunas, Alertas y Recordatorios
-- ============================================================
USE DB_VidaAnimal;
GO

-- ════════════════════════════════════════════════════════════
--  VACUNAS
-- ════════════════════════════════════════════════════════════

CREATE PROCEDURE SP_OBTENER_VACUNAS_DISPONIBLES
AS
BEGIN
    SELECT 'Rabia'                            AS NOMBRE, 'Protección contra el virus de la rabia'                    AS DESCRIPCION, 12 AS PERIODO_MESES UNION ALL
    SELECT 'Vacuna Séxtuple Canina',           'Moquillo, hepatitis, leptospirosis, parvovirus, parainfluenza',         12 UNION ALL
    SELECT 'Vacuna Quíntuple Canina',          'Moquillo, hepatitis, leptospirosis, parvovirus',                         12 UNION ALL
    SELECT 'Vacuna Triple Felina',             'Rinotraqueítis, calicivirus y panleucopenia felina',                     12 UNION ALL
    SELECT 'Vacuna Contra Leucemia Felina',    'Protección contra FeLV',                                                 12 UNION ALL
    SELECT 'Vacuna Contra Bordetella',         'Prevención de la tos de las perreras',                                   12 UNION ALL
    SELECT 'Vacuna Contra Parvovirus Canino',  'Protección específica contra parvovirus',                                12 UNION ALL
    SELECT 'Vacuna Contra Moquillo Canino',    'Protección específica contra moquillo',                                  12 UNION ALL
    SELECT 'Vacuna Contra Leptospirosis',      'Protección contra serotipos de leptospira',                              12 UNION ALL
    SELECT 'Vacuna Contra Coronavirus Canino', 'Previene la infección por coronavirus canino',                           12 UNION ALL
    SELECT 'Vacuna Contra Panleucopenia Felina','Protección específica contra panleucopenia',                            12 UNION ALL
    SELECT 'Vacuna Contra Calicivirus Felino', 'Protección específica contra calicivirus felino',                        12 UNION ALL
    SELECT 'Vacuna Contra Rinotraqueítis Felina','Protección específica contra rinotraqueítis felina',                   12
    ORDER BY NOMBRE;
END;
GO

CREATE PROCEDURE SP_REGISTRAR_VACUNA_APLICADA
    @ID_MASCOTA      INT,
    @NOMBRE          VARCHAR(50),
    @DESCRIPCION     VARCHAR(255),
    @PERIODO_MESES   INT,
    @FECHA_APLICACION DATE
AS
BEGIN
    DECLARE @FECHA_PROXIMA DATE = DATEADD(MONTH, @PERIODO_MESES, @FECHA_APLICACION);
    INSERT INTO VACUNA_APLICADA
        (ID_MASCOTA, NOMBRE, DESCRIPCION, PERIODO_MESES, FECHA_APLICACION, FECHA_PROXIMA)
    VALUES
        (@ID_MASCOTA, @NOMBRE, @DESCRIPCION, @PERIODO_MESES, @FECHA_APLICACION, @FECHA_PROXIMA);
    SELECT SCOPE_IDENTITY() AS ID_VACUNA;
END;
GO

CREATE PROCEDURE SP_OBTENER_VACUNAS_APLICADAS_POR_MASCOTA
    @ID_MASCOTA INT
AS
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.DESCRIPCION, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = @ID_MASCOTA
    ORDER BY VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_OBTENER_HISTORIAL_VACUNACION
    @ID_MASCOTA INT
AS
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE, VA.DESCRIPCION, VA.FECHA_APLICACION, VA.FECHA_PROXIMA,
           CASE
               WHEN VA.FECHA_PROXIMA < GETDATE()                               THEN 'VENCIDA'
               WHEN DATEDIFF(DAY, GETDATE(), VA.FECHA_PROXIMA) <= 30           THEN 'POR VENCER'
               ELSE 'VIGENTE'
           END AS ESTADO,
           DATEDIFF(DAY, GETDATE(), VA.FECHA_PROXIMA) AS DIAS_RESTANTES
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = @ID_MASCOTA
    ORDER BY VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_OBTENER_VACUNAS_PROXIMAS_A_VENCER
    @DIAS_ANTICIPACION INT = 30
AS
BEGIN
    SELECT VA.ID_VACUNA, M.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE,
           VA.NOMBRE AS NOMBRE_VACUNA, VA.FECHA_APLICACION, VA.FECHA_PROXIMA,
           DATEDIFF(DAY, GETDATE(), VA.FECHA_PROXIMA) AS DIAS_RESTANTES,
           C.ID_CLIENTE, C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_CLIENTE,
           C.TELEFONO, C.CORREO_ELECTRONICO
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE C ON M.ID_CLIENTE  = C.ID_CLIENTE
    WHERE VA.FECHA_PROXIMA BETWEEN GETDATE() AND DATEADD(DAY, @DIAS_ANTICIPACION, GETDATE())
    ORDER BY VA.FECHA_PROXIMA;
END;
GO

CREATE PROCEDURE SP_OBTENER_VACUNAS_PROXIMAS
AS
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE AS TIPO_VACUNA,
           M.NOMBRE AS MASCOTA,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS CLIENTE,
           CL.CEDULA AS CEDULA_CLIENTE,
           VA.FECHA_PROXIMA, VA.FECHA_APLICACION, VA.DESCRIPCION,
           CONCAT(VA.NOMBRE, ' - ', FORMAT(VA.FECHA_PROXIMA, 'dd/MM/yyyy'), ' - ', M.NOMBRE) AS DISPLAY_TEXT
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
    WHERE VA.FECHA_PROXIMA >= GETDATE()
    ORDER BY VA.FECHA_PROXIMA;
END;
GO

CREATE PROCEDURE SP_VERIFICAR_VACUNA_APLICADA
    @ID_MASCOTA   INT,
    @NOMBRE_VACUNA VARCHAR(50)
AS
BEGIN
    SELECT TOP 1 VA.ID_VACUNA, VA.NOMBRE, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = @ID_MASCOTA AND VA.NOMBRE = @NOMBRE_VACUNA
    ORDER BY VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_VERIFICAR_VACUNA_APLICADA_POR_MASCOTA
    @ID_MASCOTA    INT,
    @NOMBRE_VACUNA VARCHAR(50)
AS
BEGIN
    SELECT TOP 1 VA.ID_VACUNA, VA.NOMBRE, VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = @ID_MASCOTA AND VA.NOMBRE = @NOMBRE_VACUNA
    ORDER BY VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_VACUNA_APLICADA
    @ID_VACUNA       INT,
    @NOMBRE          VARCHAR(50),
    @DESCRIPCION     VARCHAR(255),
    @PERIODO_MESES   INT,
    @FECHA_APLICACION DATE,
    @FECHA_PROXIMA   DATE
AS
BEGIN
    UPDATE VACUNA_APLICADA
    SET NOMBRE = @NOMBRE, DESCRIPCION = @DESCRIPCION, PERIODO_MESES = @PERIODO_MESES,
        FECHA_APLICACION = @FECHA_APLICACION, FECHA_PROXIMA = @FECHA_PROXIMA
    WHERE ID_VACUNA = @ID_VACUNA;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_OBTENER_DETALLES_VACUNA
    @ID_VACUNA INT
AS
BEGIN
    SELECT VA.ID_VACUNA, VA.NOMBRE AS NOMBRE_VACUNA, VA.DESCRIPCION,
           VA.FECHA_APLICACION, VA.FECHA_PROXIMA,
           M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA,
           CONCAT(CL.NOMBRE, ' ', CL.APELLIDO) AS NOMBRE_CLIENTE,
           CL.TELEFONO, CL.CORREO_ELECTRONICO
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
    WHERE VA.ID_VACUNA = @ID_VACUNA;
END;
GO

-- ════════════════════════════════════════════════════════════
--  ALERTAS Y RECORDATORIOS
-- ════════════════════════════════════════════════════════════

CREATE OR ALTER PROCEDURE SP_OBTENER_CITAS_POR_RANGO_FECHAS
    @FECHA_INICIO DATE,
    @FECHA_FIN    DATE
AS
BEGIN
    SELECT C.ID_CITA, C.ID_CLIENTE,
           CL.NOMBRE + ' ' + CL.APELLIDO AS NOMBRE_CLIENTE,
           C.ID_MASCOTA, M.NOMBRE AS NOMBRE_MASCOTA, -- Corregido de MC a C
           C.ID_SERVICIO, S.NOMBRE_SERVICIO,
           C.FECHA_HORA, C.ESTADO, C.OBSERVACIONES,
           CASE C.ESTADO
               WHEN 'PENDIENTE'  THEN 'Pendiente'
               WHEN 'REALIZADA'  THEN 'Realizada' -- Corregido de COMPLETADA
               WHEN 'CANCELADA'  THEN 'Cancelada'
           END AS ESTADO_DESCRIPCION,
           CASE WHEN S.NOMBRE_SERVICIO LIKE '%Vacuna%' THEN 'Vacunación' ELSE 'Consulta' END AS TIPO_CITA
    FROM CITA C
    INNER JOIN CLIENTE CL ON C.ID_CLIENTE = CL.ID_CLIENTE
    INNER JOIN MASCOTA M  ON C.ID_MASCOTA = M.ID_MASCOTA -- Alias 'M'
    INNER JOIN SERVICIO S  ON C.ID_SERVICIO = S.ID_SERVICIO
    WHERE CONVERT(DATE, C.FECHA_HORA) BETWEEN @FECHA_INICIO AND @FECHA_FIN
    ORDER BY C.FECHA_HORA;
END;
GO

CREATE PROCEDURE SP_VERIFICAR_RECORDATORIOS
    @ID_USUARIO INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @ID_CITA INT, @ID_VACUNA INT, @TIPO VARCHAR(20),
            @FECHA_EVENTO DATETIME, @MENSAJE_BASE VARCHAR(255), @MENSAJE_FINAL VARCHAR(500),
            @NOMBRE_CLIENTE VARCHAR(100), @NOMBRE_MASCOTA VARCHAR(50),
            @CEDULA_CLIENTE VARCHAR(10), @NOMBRE_SERVICIO VARCHAR(50),
            @VETERINARIOS NVARCHAR(MAX);

    DECLARE @Pendientes TABLE (
        ID INT IDENTITY(1,1), TIPO VARCHAR(20), ID_EVENTO INT,
        FECHA_EVENTO DATETIME, ANTICIPACION VARCHAR(20), MENSAJE_BASE VARCHAR(255),
        NOMBRE_CLIENTE VARCHAR(100), NOMBRE_MASCOTA VARCHAR(50),
        CEDULA_CLIENTE VARCHAR(10), NOMBRE_SERVICIO VARCHAR(50)
    );

    -- Citas pendientes
    INSERT INTO @Pendientes
        (TIPO, ID_EVENTO, FECHA_EVENTO, ANTICIPACION, MENSAJE_BASE,
         NOMBRE_CLIENTE, NOMBRE_MASCOTA, CEDULA_CLIENTE, NOMBRE_SERVICIO)
    SELECT 'CITA', C.ID_CITA, C.FECHA_HORA, RC.ANTICIPACION, RC.MENSAJE,
           CL.NOMBRE + ' ' + CL.APELLIDO, M.NOMBRE, CL.CEDULA, S.NOMBRE_SERVICIO
    FROM CITA C
    INNER JOIN CLIENTE      CL ON C.ID_CLIENTE  = CL.ID_CLIENTE
    INNER JOIN MASCOTA      M  ON C.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN SERVICIO     S  ON C.ID_SERVICIO = S.ID_SERVICIO
    CROSS JOIN RECORDATORIO_CONFIG RC
    WHERE C.ESTADO = 'PENDIENTE' AND RC.TIPO_RECORDATORIO = 'CITA' AND RC.ACTIVO = 1
      AND NOT EXISTS (
          SELECT 1 FROM RECORDATORIO_ENVIADO RE
          WHERE RE.ID_CITA = C.ID_CITA AND RE.TIPO = 'CITA'
            AND CAST(RE.FECHA_ENVIO AS DATE) = CAST(GETDATE() AS DATE)
      )
      AND (
          (RC.ANTICIPACION = '15_DIAS'     AND DATEDIFF(DAY,    GETDATE(), C.FECHA_HORA) = 15) OR
          (RC.ANTICIPACION = '7_DIAS'      AND DATEDIFF(DAY,    GETDATE(), C.FECHA_HORA) = 7)  OR
          (RC.ANTICIPACION = '1_MES'       AND DATEDIFF(MONTH,  GETDATE(), C.FECHA_HORA) = 1)  OR
          (RC.ANTICIPACION = '12_HORAS'    AND DATEDIFF(HOUR,   GETDATE(), C.FECHA_HORA) = 12) OR
          (RC.ANTICIPACION = '10_HORAS'    AND DATEDIFF(HOUR,   GETDATE(), C.FECHA_HORA) = 10) OR
          (RC.ANTICIPACION = '5_MINUTOS'   AND DATEDIFF(MINUTE, GETDATE(), C.FECHA_HORA) = 5)  OR
          (RC.ANTICIPACION = '30_SEGUNDOS' AND DATEDIFF(SECOND, GETDATE(), C.FECHA_HORA) = 30)
      );

    -- Vacunas próximas
    INSERT INTO @Pendientes
        (TIPO, ID_EVENTO, FECHA_EVENTO, ANTICIPACION, MENSAJE_BASE,
         NOMBRE_CLIENTE, NOMBRE_MASCOTA, CEDULA_CLIENTE, NOMBRE_SERVICIO)
    SELECT 'VACUNA', VA.ID_VACUNA, VA.FECHA_PROXIMA, RC.ANTICIPACION, RC.MENSAJE,
           CL.NOMBRE + ' ' + CL.APELLIDO, M.NOMBRE, CL.CEDULA, VA.NOMBRE
    FROM VACUNA_APLICADA VA
    INNER JOIN MASCOTA M ON VA.ID_MASCOTA = M.ID_MASCOTA
    INNER JOIN CLIENTE CL ON M.ID_CLIENTE = CL.ID_CLIENTE
    CROSS JOIN RECORDATORIO_CONFIG RC
    WHERE RC.TIPO_RECORDATORIO = 'VACUNA' AND RC.ACTIVO = 1
      AND NOT EXISTS (
          SELECT 1 FROM RECORDATORIO_ENVIADO RE
          WHERE RE.ID_VACUNA = VA.ID_VACUNA AND RE.TIPO = 'VACUNA'
            AND RE.MENSAJE LIKE RC.MENSAJE + '%'
            AND CAST(RE.FECHA_ENVIO AS DATE) = CAST(GETDATE() AS DATE)
      )
      AND (
          (RC.ANTICIPACION = '15_DIAS'     AND DATEDIFF(DAY,    GETDATE(), VA.FECHA_PROXIMA) = 15) OR
          (RC.ANTICIPACION = '7_DIAS'      AND DATEDIFF(DAY,    GETDATE(), VA.FECHA_PROXIMA) = 7)  OR
          (RC.ANTICIPACION = '1_MES'       AND DATEDIFF(MONTH,  GETDATE(), VA.FECHA_PROXIMA) = 1)  OR
          (RC.ANTICIPACION = '12_HORAS'    AND DATEDIFF(HOUR,   GETDATE(), VA.FECHA_PROXIMA) = 12) OR
          (RC.ANTICIPACION = '10_HORAS'    AND DATEDIFF(HOUR,   GETDATE(), VA.FECHA_PROXIMA) = 10) OR
          (RC.ANTICIPACION = '5_MINUTOS'   AND DATEDIFF(MINUTE, GETDATE(), VA.FECHA_PROXIMA) = 5)  OR
          (RC.ANTICIPACION = '30_SEGUNDOS' AND DATEDIFF(SECOND, GETDATE(), VA.FECHA_PROXIMA) = 30)
      );

    DECLARE @Total INT = (SELECT COUNT(*) FROM @Pendientes), @Idx INT = 1;

    WHILE @Idx <= @Total
    BEGIN
        SELECT @TIPO = TIPO,
               @ID_CITA    = CASE WHEN TIPO = 'CITA'   THEN ID_EVENTO ELSE NULL END,
               @ID_VACUNA  = CASE WHEN TIPO = 'VACUNA' THEN ID_EVENTO ELSE NULL END,
               @FECHA_EVENTO = FECHA_EVENTO, @MENSAJE_BASE = MENSAJE_BASE,
               @NOMBRE_CLIENTE = NOMBRE_CLIENTE, @NOMBRE_MASCOTA = NOMBRE_MASCOTA,
               @CEDULA_CLIENTE = CEDULA_CLIENTE, @NOMBRE_SERVICIO = NOMBRE_SERVICIO
        FROM @Pendientes WHERE ID = @Idx;

        SET @VETERINARIOS = '';
        IF @TIPO = 'CITA'
        BEGIN
            -- Obtenemos el nombre del veterinario específico de LA CITA
            SELECT @VETERINARIOS = V.NOMBRE + ' ' + V.APELLIDO
            FROM CITA C
            INNER JOIN VETERINARIO V ON C.ID_VETERINARIO = V.ID_VETERINARIO
            WHERE C.ID_CITA = @ID_CITA;

            SET @MENSAJE_FINAL = @MENSAJE_BASE + '. Detalles: ' +
                CONVERT(VARCHAR, @FECHA_EVENTO, 103) + ' ' + LEFT(CONVERT(VARCHAR, @FECHA_EVENTO, 108), 5) +
                ' - Servicio: ' + @NOMBRE_SERVICIO +
                '. Mascota: ' + @NOMBRE_MASCOTA +
                '. Veterinario: ' + ISNULL(@VETERINARIOS, 'Por asignar');
        END
        ELSE
        BEGIN
            SET @MENSAJE_FINAL = @MENSAJE_BASE + '. Detalles: ' +
                'Vacuna: ' + @NOMBRE_SERVICIO +
                ' - Próxima aplicación: ' + CONVERT(VARCHAR, @FECHA_EVENTO, 103) +
                ' - Mascota: ' + @NOMBRE_MASCOTA +
                ' - Cliente: ' + @NOMBRE_CLIENTE + ' (' + @CEDULA_CLIENTE + ')';
        END

        INSERT INTO RECORDATORIO_ENVIADO (ID_USUARIO, ID_CITA, ID_VACUNA, TIPO, MENSAJE)
        VALUES (@ID_USUARIO, @ID_CITA, @ID_VACUNA, @TIPO, @MENSAJE_FINAL);

        SET @Idx += 1;
    END

    IF @ID_USUARIO IS NOT NULL
        SELECT ID_RECORDATORIO, MENSAJE, FECHA_ENVIO, LEIDO
        FROM RECORDATORIO_ENVIADO
        WHERE ID_USUARIO = @ID_USUARIO AND LEIDO = 0
        ORDER BY FECHA_ENVIO DESC;
END;
GO

CREATE PROCEDURE SP_OBTENER_RECORDATORIOS_PENDIENTES
    @ID_USUARIO INT
AS
BEGIN
    SELECT ID_RECORDATORIO, ID_USUARIO, ID_CITA, ID_VACUNA,
           TIPO, MENSAJE, FECHA_ENVIO, LEIDO
    FROM RECORDATORIO_ENVIADO
    WHERE ID_USUARIO = @ID_USUARIO AND LEIDO = 0
    ORDER BY FECHA_ENVIO DESC;
END;
GO

CREATE PROCEDURE SP_MARCAR_RECORDATORIO_LEIDO
    @ID_RECORDATORIO INT
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;
        UPDATE RECORDATORIO_ENVIADO
        SET LEIDO = 1, CONTADOR_MOSTRADO = 0
        WHERE ID_RECORDATORIO = @ID_RECORDATORIO;
        IF @@ROWCOUNT > 0
        BEGIN COMMIT TRANSACTION; SELECT 1 AS RESULTADO; END
        ELSE
        BEGIN ROLLBACK TRANSACTION; SELECT 0 AS RESULTADO; END
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        SELECT 0 AS RESULTADO;
    END CATCH
END;
GO

CREATE PROCEDURE SP_INCREMENTAR_CONTADOR_RECORDATORIO
    @ID_RECORDATORIO INT
AS
BEGIN
    UPDATE RECORDATORIO_ENVIADO
    SET CONTADOR_MOSTRADO = CONTADOR_MOSTRADO + 1
    WHERE ID_RECORDATORIO = @ID_RECORDATORIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_CONTADOR_RECORDATORIO
    @ID_RECORDATORIO INT
AS
BEGIN
    SELECT CONTADOR_MOSTRADO FROM RECORDATORIO_ENVIADO WHERE ID_RECORDATORIO = @ID_RECORDATORIO;
END;
GO

CREATE PROCEDURE SP_OBTENER_TODOS_RECORDATORIOS
    @FECHA_INICIO DATETIME,
    @FECHA_FIN    DATETIME
AS
BEGIN
    SELECT ID_RECORDATORIO, ID_USUARIO, ID_CITA, ID_VACUNA,
           TIPO, MENSAJE, FECHA_ENVIO, LEIDO, CONTADOR_MOSTRADO
    FROM RECORDATORIO_ENVIADO
    WHERE FECHA_ENVIO BETWEEN @FECHA_INICIO AND @FECHA_FIN
    ORDER BY FECHA_ENVIO DESC;
END;
GO

CREATE PROCEDURE SP_REGISTRAR_RECORDATORIO
    @CORREO_USUARIO VARCHAR(100) = NULL,
    @ID_CITA        INT          = NULL,
    @ID_VACUNA      INT          = NULL,
    @TIPO           VARCHAR(20),
    @MENSAJE        VARCHAR(500),
    @ANTICIPACION   VARCHAR(20)  = NULL
AS
BEGIN
    DECLARE @ID_USUARIO INT = NULL;
    IF @CORREO_USUARIO IS NOT NULL
        SELECT @ID_USUARIO = ID_USUARIO FROM USUARIO WHERE CORREO_ELECTRONICO = @CORREO_USUARIO;

    INSERT INTO RECORDATORIO_ENVIADO
        (ID_USUARIO, ID_CITA, ID_VACUNA, TIPO, MENSAJE, FECHA_ENVIO)
    VALUES (
        @ID_USUARIO, @ID_CITA, @ID_VACUNA, @TIPO, @MENSAJE,
        CASE
            WHEN @ANTICIPACION = '15_DIAS' THEN DATEADD(DAY, -15,
                CASE WHEN @TIPO = 'CITA' THEN (SELECT FECHA_HORA    FROM CITA            WHERE ID_CITA   = @ID_CITA)
                     ELSE                     (SELECT FECHA_PROXIMA FROM VACUNA_APLICADA WHERE ID_VACUNA  = @ID_VACUNA) END)
            WHEN @ANTICIPACION = '7_DIAS'  THEN DATEADD(DAY, -7,
                CASE WHEN @TIPO = 'CITA' THEN (SELECT FECHA_HORA    FROM CITA            WHERE ID_CITA   = @ID_CITA)
                     ELSE                     (SELECT FECHA_PROXIMA FROM VACUNA_APLICADA WHERE ID_VACUNA  = @ID_VACUNA) END)
            WHEN @ANTICIPACION = '1_MES'   THEN DATEADD(MONTH, -1,
                CASE WHEN @TIPO = 'CITA' THEN (SELECT FECHA_HORA    FROM CITA            WHERE ID_CITA   = @ID_CITA)
                     ELSE                     (SELECT FECHA_PROXIMA FROM VACUNA_APLICADA WHERE ID_VACUNA  = @ID_VACUNA) END)
            ELSE GETDATE()
        END
    );
    SELECT SCOPE_IDENTITY() AS ID_RECORDATORIO;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_RECORDATORIO
    @ID_RECORDATORIO INT,
    @MENSAJE         VARCHAR(500),
    @LEIDO           BIT = NULL
AS
BEGIN
    UPDATE RECORDATORIO_ENVIADO
    SET MENSAJE = @MENSAJE, LEIDO = ISNULL(@LEIDO, LEIDO)
    WHERE ID_RECORDATORIO = @ID_RECORDATORIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_ELIMINAR_RECORDATORIO
    @ID_RECORDATORIO INT
AS
BEGIN
    DELETE FROM RECORDATORIO_ENVIADO WHERE ID_RECORDATORIO = @ID_RECORDATORIO;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO

CREATE PROCEDURE SP_OBTENER_CONFIG_RECORDATORIOS
AS
BEGIN
    SELECT ID_CONFIG, TIPO_RECORDATORIO, ANTICIPACION, MENSAJE, ACTIVO
    FROM RECORDATORIO_CONFIG
    ORDER BY TIPO_RECORDATORIO, ANTICIPACION;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_CONFIG_RECORDATORIO
    @ID_CONFIG INT,
    @MENSAJE   VARCHAR(255),
    @ACTIVO    BIT
AS
BEGIN
    UPDATE RECORDATORIO_CONFIG
    SET MENSAJE = @MENSAJE, ACTIVO = @ACTIVO
    WHERE ID_CONFIG = @ID_CONFIG;
    SELECT @@ROWCOUNT AS FILAS_AFECTADAS;
END;
GO
