-- ============================================================
--  MÓDULO 7 | SPs de Historial Médico
-- ============================================================
USE DB_VidaAnimal;
GO

CREATE PROCEDURE SP_REGISTRAR_HISTORIAL
    @ID_MASCOTA        INT,
    @ID_CITA           INT = NULL,
    @ID_ATENCION_MEDICA INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO HISTORIAL_MEDICO (ID_MASCOTA, ID_CITA, FECHA, ID_ATENCION_MEDICA)
    VALUES (@ID_MASCOTA, @ID_CITA, GETDATE(), @ID_ATENCION_MEDICA);
    SELECT SCOPE_IDENTITY() AS ID_HISTORIAL;
END;
GO

CREATE PROCEDURE SP_OBTENER_HISTORIAL_MEDICO_POR_MASCOTA
    @ID_MASCOTA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        AM.ID_ATENCION_MEDICA, AM.FECHA, C.ID_CITA, S.NOMBRE_SERVICIO,
        V.NOMBRE + ' ' + V.APELLIDO AS VETERINARIO,
        AM.DIAGNOSTICO, AM.TRATAMIENTO,
        AM.OBSERVACIONES AS OBSERVACIONES_ATENCION,
        (SELECT STRING_AGG(IM.NOMBRE, ', ')
         FROM INSTRUMENTO_USADO IU
         JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO = IM.ID_INSTRUMENTO
         WHERE IU.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA) AS INSTRUMENTOS_USADOS,
        (SELECT STRING_AGG(MED.NOMBRE + ' (' + MR.DOSIS + ', ' + MR.FRECUENCIA + ', ' + MR.DURACION + ')', ' | ')
         FROM MEDICAMENTO_RECETADO MR
         JOIN MEDICAMENTO MED ON MR.ID_MEDICAMENTO = MED.ID_MEDICAMENTO
         WHERE MR.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA) AS MEDICAMENTOS_RECETADOS
    FROM HISTORIAL_MEDICO HM
    INNER JOIN ATENCION_MEDICA AM ON HM.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    LEFT  JOIN CITA            C  ON AM.ID_CITA            = C.ID_CITA
    LEFT  JOIN SERVICIO        S  ON C.ID_SERVICIO         = S.ID_SERVICIO
    LEFT  JOIN VETERINARIO     V  ON AM.ID_VETERINARIO     = V.ID_VETERINARIO
    WHERE HM.ID_MASCOTA = @ID_MASCOTA
    ORDER BY AM.FECHA DESC;
END;
GO

CREATE PROCEDURE SP_OBTENER_HISTORIAL_COMPLETO_POR_MASCOTA
    @ID_MASCOTA INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Datos de la mascota y propietario
    SELECT M.NOMBRE AS NOMBRE_MASCOTA, M.ESPECIE, M.RAZA, M.SEXO, M.FECHA_NACIMIENTO,
           C.NOMBRE + ' ' + C.APELLIDO AS NOMBRE_PROPIETARIO, C.CEDULA
    FROM MASCOTA M
    INNER JOIN CLIENTE C ON M.ID_CLIENTE = C.ID_CLIENTE
    WHERE M.ID_MASCOTA = @ID_MASCOTA;

    -- Historial: instrumentos usados
    SELECT HM.ID_HISTORIAL, HM.FECHA, C.ID_CITA, S.NOMBRE_SERVICIO,
           V.NOMBRE + ' ' + V.APELLIDO AS VETERINARIO,
           IM.NOMBRE AS INSTRUMENTO_USADO,
           NULL AS MEDICAMENTO, NULL AS DOSIS, NULL AS FRECUENCIA, NULL AS DURACION,
           AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES AS OBSERVACIONES_ATENCION
    FROM HISTORIAL_MEDICO HM
    LEFT  JOIN CITA              C  ON HM.ID_CITA            = C.ID_CITA
    LEFT  JOIN SERVICIO          S  ON C.ID_SERVICIO         = S.ID_SERVICIO
    LEFT  JOIN ATENCION_MEDICA   AM ON HM.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    LEFT  JOIN VETERINARIO       V  ON AM.ID_VETERINARIO     = V.ID_VETERINARIO
    LEFT  JOIN INSTRUMENTO_USADO IU ON AM.ID_ATENCION_MEDICA = IU.ID_ATENCION_MEDICA
    LEFT  JOIN INSTRUMENTO_MEDICO IM ON IU.ID_INSTRUMENTO    = IM.ID_INSTRUMENTO
    WHERE HM.ID_MASCOTA = @ID_MASCOTA

    UNION ALL

    -- Historial: medicamentos recetados
    SELECT HM.ID_HISTORIAL, HM.FECHA, C.ID_CITA, S.NOMBRE_SERVICIO,
           V.NOMBRE + ' ' + V.APELLIDO AS VETERINARIO,
           NULL AS INSTRUMENTO_USADO,
           MED.NOMBRE AS MEDICAMENTO, MR.DOSIS, MR.FRECUENCIA, MR.DURACION,
           AM.DIAGNOSTICO, AM.TRATAMIENTO, AM.OBSERVACIONES AS OBSERVACIONES_ATENCION
    FROM HISTORIAL_MEDICO HM
    LEFT  JOIN CITA                 C   ON HM.ID_CITA            = C.ID_CITA
    LEFT  JOIN SERVICIO             S   ON C.ID_SERVICIO         = S.ID_SERVICIO
    LEFT  JOIN ATENCION_MEDICA      AM  ON HM.ID_ATENCION_MEDICA = AM.ID_ATENCION_MEDICA
    LEFT  JOIN VETERINARIO          V   ON AM.ID_VETERINARIO     = V.ID_VETERINARIO
    LEFT  JOIN MEDICAMENTO_RECETADO MR  ON AM.ID_ATENCION_MEDICA = MR.ID_ATENCION_MEDICA
    LEFT  JOIN MEDICAMENTO          MED ON MR.ID_MEDICAMENTO     = MED.ID_MEDICAMENTO
    WHERE HM.ID_MASCOTA = @ID_MASCOTA

    ORDER BY FECHA DESC;

    -- Ficha médica
    SELECT ALERGIAS, ENFERMEDADES_CRONICAS, OBSERVACIONES, ULTIMA_ACTUALIZACION
    FROM FICHA_MEDICA WHERE ID_MASCOTA = @ID_MASCOTA;

    -- Vacunas aplicadas
    SELECT VA.ID_VACUNA, VA.NOMBRE AS NOMBRE_VACUNA,
           VA.FECHA_APLICACION, VA.FECHA_PROXIMA
    FROM VACUNA_APLICADA VA
    WHERE VA.ID_MASCOTA = @ID_MASCOTA
    ORDER BY VA.FECHA_APLICACION DESC;
END;
GO

CREATE PROCEDURE SP_ACTUALIZAR_FICHA_MEDICA
    @ID_MASCOTA           INT,
    @ALERGIAS             VARCHAR(255) = NULL,
    @ENFERMEDADES_CRONICAS VARCHAR(255) = NULL,
    @OBSERVACIONES        TEXT         = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        IF NOT EXISTS (SELECT 1 FROM MASCOTA WHERE ID_MASCOTA = @ID_MASCOTA)
        BEGIN
            RAISERROR('La mascota especificada no existe', 16, 1);
            ROLLBACK TRANSACTION;
            RETURN 0;
        END

        IF EXISTS (SELECT 1 FROM FICHA_MEDICA WHERE ID_MASCOTA = @ID_MASCOTA)
            UPDATE FICHA_MEDICA
            SET ALERGIAS              = ISNULL(@ALERGIAS, ALERGIAS),
                ENFERMEDADES_CRONICAS = ISNULL(@ENFERMEDADES_CRONICAS, ENFERMEDADES_CRONICAS),
                OBSERVACIONES         = ISNULL(@OBSERVACIONES, OBSERVACIONES),
                ULTIMA_ACTUALIZACION  = GETDATE()
            WHERE ID_MASCOTA = @ID_MASCOTA;
        ELSE
            INSERT INTO FICHA_MEDICA (ID_MASCOTA, ALERGIAS, ENFERMEDADES_CRONICAS, OBSERVACIONES)
            VALUES (@ID_MASCOTA, @ALERGIAS, @ENFERMEDADES_CRONICAS, @OBSERVACIONES);

        COMMIT TRANSACTION;
        RETURN 1;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
        RETURN 0;
    END CATCH
END;
GO
